### ISSUE TITLE
Logging objects

### ISSUE THREAD

**Issue by guettli** [hynek/structlog#100]
This is a question. I hope it is ok to ask here. If not, please tell me where I an can ask.

I want to log objects (instances from custom classes) to structlog.

I am unsure where to do the serialization.

My preferred solution, would be that I (the application programmer) don't need to do it.

Example:

`logger.info('meet me here', point=point)
`

Where `point` is a instance of a class `Point`. For example it has a member `x` and a member `y`.

What do you think? 

Is this possible with structlog?

A different solution would be:

`logger.info('meet me here', point=point.to_dict())
`

But the first solution looks cleaner for my eyes.

**Comment by hynek** [comment]
You could add a `__structlog__` method to the class or (much better) use single dispatch: https://hynek.me/articles/serialization/ within a processor.

**Comment by guettli** [comment]
@hynek  I am still on Python 2.7, and happy that there is backport for singledispatch: https://pypi.python.org/pypi/singledispatch

Thank you for sharing this "secret" :-)
