### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by philtay** [hynek/structlog#104]
Latest release is almost a year old and the `stdlib` bug (fixed on master) is biting us. Thanks.

**Comment by hynek** [comment]
Yes you’re right.  I’m currently in a pit of misery from procrastinating on #79, #95, and #98 which I want to include but just can’t get around to learn enough to finish/integrate them.

I’ll use work time tomorrow to finish it up.  I’m leaving on Wednesday for a vacation, so I can’t 100% promise that I’ll drop a heavy release and leave coutry. :|

I’m sorry.

**Comment by philtay** [comment]
Do what you can. Thanks a lot for your work and happy vacation!

My 2 cents on stdlib integration. Have a look here:

https://github.com/pypa/warehouse/blob/master/warehouse/logging.py

A `StructlogFormatter` can solve the problem.

**Comment by philtay** [comment]
ping @hynek

**Comment by hynek** [comment]
I’m waiting for #105 to be resolved; will release right after.

**Comment by hynek** [comment]
17.1 is on PyPI – sorry for the delays! :(
