### ISSUE TITLE
Structlog needs a logo

### ISSUE THREAD

**Issue by freakboy3742** [hynek/structlog#107]
From a [conversation on Twitter](https://twitter.com/hynek/status/856731787875295232):

@ewdurbin: Does it have a sticker?
@hynek: doesn't even have a logo
@freakboy3742: Some sort of cyber-beaver, perhaps?

**Comment by freakboy3742** [comment]
/me throws his hat into the ring with:
![screenshot 2017-04-26 06 55 07](https://cloud.githubusercontent.com/assets/37345/25425198/b8d9206a-2a9d-11e7-9598-8e743b52488c.png)

**Comment by hynek** [comment]
thanks ✨
