### ISSUE TITLE
add_logger_name processor does not work in ProcessorFormatter's pre_chain

### ISSUE THREAD

**Issue by gilbsgilbs** [hynek/structlog#111]
Hi,

### Steps to reproduce
1. Take [this](http://structlog.readthedocs.io/en/stable/standard-library.html?highlight=add_logger_name#rendering-using-structlog-based-formatters-within-logging) example from the doc.
2. Add `structlog.stdlib.add_logger_name` processor to pre_chain.
3. Run the example.

### Expected behaviour
The logger name (`root` in the doc example) should be added to the event dict with the key `logger`.

### Actual behaviour
Crashes as soon as you log anything using logging module. Here is the stacktrace:
```
>>> logging.getLogger('foo').warning('bar')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)logging.getLogger('foo').warning("bar")
  File "/usr/lib64/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/gilbsgilbs/Projects/structlog/src/structlog/stdlib.py", line 423, in format
    ed = proc(None, meth_name, ed)
  File "/home/gilbsgilbs/Projects/structlog/src/structlog/stdlib.py", line 349, in add_logger_name
    event_dict['logger'] = logger.name
AttributeError: 'NoneType' object has no attribute 'name'
Call stack:
  File "test.py", line 66, in <module>
    logging.getLogger('foo').warning('bar')
Message: 'bar'
Arguments: ()
```

### Comments
This is because `ProcessorFormatter` passes `None` as the logger to pre_chain processors. From inside the processor, we have lost track of the record, which was our only hope to get the logger name (`record.name`).

How this should be fixed according to you? I can contribute to fix this faster. Probably won't use `ProcessorFormatter` for now because of this issue.

**Comment by hynek** [comment]
Hm, that’s an interesting one!  We simply don't have no way to obtain the logger from a record if I see it correctly, but we *do* have full access to the record.

What do you think about adding (and later removing!) the record to the event_dict and making the stdlib processors hybrid?

**Comment by gilbsgilbs** [comment]
Indeed, the logger instance is not attached to a record. Yet, it should be possible to re-create a logger instance using `getLogger(record.name)`. With logger caching, chances are that it would return the exact same object that was used to produce the record. But I'm pretty sure this would be quite bad performance-wise since we would have to do this each time a vanilla record is emitted.

If this happens to be impossible or too slow or undesirable for any reason, we would have to find a way to pass some sort of context to processors. Passing the record to the event dict and removing it afterwards is a way to pass a context and it will do the trick. It sounds like abusing the event_dict to me though. Anyhow, the first technique I mentioned is not super-elegant either.

I'll do your suggestion for now and we keep in mind that there certainly are better solutions, but they may involve bigger refactorings and maybe even breaking changes. We probably don't want this for the tiny usage we have at the moment for a proper context.
