### ISSUE TITLE
Can logger.bind to be persisted globally?

### ISSUE THREAD

**Issue by QingsongYao** [hynek/structlog#121]
I run this code:

log = get_logger()
log.bind(user="anonymous", some_key=23)
log = get_logger()
log.info("user.logged_in", happy=True)

which did not contains the two keys I bind before.   I wonder how can I persist the two keys globally so that all get_logger() call will have the two keys?

**Comment by hynek** [comment]
Have you looked at http://www.structlog.org/en/stable/thread-local.html ?
