### ISSUE TITLE
Do I need std lib logging?

### ISSUE THREAD

**Issue by arnuschky** [hynek/structlog#124]
The documentation has me confused. I expected that I can use structlog in a sort-of standalone mode, but I don't see how. Using the std lib seems to be presented as optional, but the only other option I see is twisted, which I don't use. Also the examples are all based on the std lib logging. So do I need it or can I somehow lose it?

**Comment by hynek** [comment]
No, if you don’t configure structlog to use the stdlib, it won’t be used.

Twisted & stdlib are two frameworks that can be integrated but are completely optional.  The default configuration for example doesn't use either.

**Comment by arnuschky** [comment]
Ok, thanks. I need to re-read the documentation then.
