### ISSUE TITLE
Setting log levels by package names

### ISSUE THREAD

**Issue by arnuschky** [hynek/structlog#125]
Coming from std lib logging, I am used to initializing logger names using class names, and then using configuration to setup logging levels on a per-package basis.

How could I achieve a similar functionality using struct log? Of course I can configue each individual logger on instantiation, but that seems backwards. I found `ignore_frame_names` but this only acts as a filter, right?

**Comment by arnuschky** [comment]
Or should I simply set Level per package name using the std lib as before?

I noticed that when using the suggested configuration from http://structlog.readthedocs.io/en/stable/standard-library.html I don't get any output at all unless I call something like `logging.basicConfig(format='%(message)s', level='DEBUG')`

I think I am still very confused about how structlog interfaces with the std lib (and whether it's necessary at all, see #124

**Comment by hynek** [comment]
As we’ve established in the other ticket, it’s not necessary at all.  *If* you want structlog to interface with stdlib logging, the log level is in any case still determined by stdlib logging, because structlog calls into it.  If stdlib logging decides that a call is below the necessary level, it’s a nop.

If using stlib integration, you *should* be able to use `structlog.get_logger(__name__)`!?

**Comment by arnuschky** [comment]
I managed to do this by simply using the logger configuration of the stdlib logging (per-logger level etc). I am happy with what I got now, it serves my purpose and makes it easier for other devs use the system by  still controlling logging through levels and package names.

Out of curiosity, what would be the best way to replicate a similar functionality using structlog? It doesn't support logging levels by itself, right? (If this is a bother to explain, feel free to just close this issue ;) )

**Comment by hynek** [comment]
structlog is generally very unopinionated re such concepts.  It understands itself more of a structured facade for whatever you’re using yourself.  It wouldn’t be hard to build a kick-ass logging package out of its primitives, it’s just that nobody has done it yet. :)

**Comment by arnuschky** [comment]
Ok, I see. :) Well, I guess I'll have stick to the stdlib for now. Thanks!
