### ISSUE TITLE
Default logger doesn't support logger.log with level

### ISSUE THREAD

**Issue by joeyfeldberg** [hynek/structlog#129]
Here is a simple code fragment:

```
import structlog
import logging
logger = structlog.get_logger()
logger.log(logging.INFO, "hello")
```

This will produce an error:
`TypeError: _proxy_to_logger() takes from 2 to 3 positional arguments but 4 were given`

This is happening because it's using the default PrintLogger I guess, but is this expected?

**Comment by hynek** [comment]
Yes, in it’s core structlog is completely agnostic to what logging system is used.  If you want to interoperate with stdlib, you have to configure it as such.
