### ISSUE TITLE
How to wrap structlog around loggers from imported code

### ISSUE THREAD

**Issue by arnuschky** [hynek/structlog#131]
How to wrap structlog around loggers from imported code? Currently log messages of imported packages show up if I set a sufficient log level for them, but they aren't formatted in the same way as the my app's msgs.

I am using structlog with the stdlib and the suggested config from http://www.structlog.org/en/stable/development.html

**Comment by hynek** [comment]
I presume the “imported code” is using the Python standard library’s logging module?   There are three documented ways how format those log entries, please refer to  http://www.structlog.org/en/stable/standard-library.html  (if you want to touch the logging module as little a possible, I guess the [third way](http://www.structlog.org/en/stable/standard-library.html#rendering-within-structlog) is the best for you).

**Comment by arnuschky** [comment]
Thank you, I'll take a look.

**Comment by arnuschky** [comment]
Sorry, forgot to close it. For the record: the second way fit my case best.

**Comment by hynek** [comment]
Cool, that’s why we have three of them. :)
