### ISSUE TITLE
Calling BoundLogger.exception when passing error instance results in TypeError

### ISSUE THREAD

**Issue by dylangleason** [hynek/structlog#135]
## Summary

Executing the `log.exception` method using after instantiating the structlog logger via the `get_logger` wrapper procedure results in an exception due to a string concatenation error.

## Environment

- OS: Ubuntu 16.04, 4.8.0-58-generic x86_64 GNU/Linux 
- Python: 3.5.3 (via pyenv)
- Structlog version: 17.2.0

## Steps to Reproduce
 
Run the simple test script and observe that, while a call to the normal `logging` library's `exception` method works as expected, the structlogger wrapper does not:

```python
import logging
from structlog import get_logger, configure
from structlog.stdlib import LoggerFactory


print('logging')
print('-------')
logging.basicConfig()
log = logging.getLogger()
log.exception(Exception('Uh oh'))

print('\nstructlog')
print('----------')
configure(logger_factory=LoggerFactory())
log = get_logger()
log.exception(Exception('Uh oh'))
```

## Error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.pyenv/versions/app-env/lib/python3.5/site-packages/structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "~/.pyenv/versions/app-env/lib/python3.5/site-packages/structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "~/.pyenv/versions/app-env/lib/python3.5/site-packages/structlog/dev.py", line 183, in __call__
    event += self._styles.reset
TypeError: unsupported operand type(s) for +=: 'Exception' and 'str'
```

## Resolution

Modifying the code at the line indicated above (line 183) using string formatting instead of concatenation appears to resolve this issue:

```python
event = '{}{}'.(event, self._styles.reset)
```

Or, on line 179, performing the cast upon initial assignment:
```python
event = str(event_dict.pop("event"))
```

**Comment by hynek** [comment]
That's not how to use it. :)

You want `log.exception("omg", exception=...)`. 

Or if you're in an except block, `log.exception("omg")` should work too.

**Comment by dylangleason** [comment]
My mistake. Looking back at the `logging.exception` documentation indeed indicates that the first argument should be a `msg` (presumably a string) and not an `Exception` type.

Nonetheless, the fact that the behavior is different between the two I think merits a change if you are aiming for compatibility... my two cents.

**Comment by dylangleason** [comment]
It appears that passing the keyword argument `exception`, per your recommendation, results in - ahem -
 an exception as well:

```python
print('\nstructlog')
print('----------')
configure(logger_factory=LoggerFactory())
log = get_logger()
log.exception('Uh oh', exception=Exception('Uh oh'))
```

Output:
```
structlog
----------
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    log.exception('Uh oh', exception=Exception('Uh oh'))
  File "~/.pyenv/versions/app-env/lib/python3.5/site-packages/structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "~/.pyenv/versions/app-env/lib/python3.5/site-packages/structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "~/.pyenv/versions/app-env/lib/python3.5/site-packages/structlog/dev.py", line 211, in __call__
    sio.write("\n" + exc)
TypeError: Can't convert 'Exception' object to str implicitly
```

Additionally, the native `Logger.exception` does not appear to support this named keyword argument at all, so this would be another point of API incompatibility.

**Comment by hynek** [comment]
Yes sorry I misspoke.  I'm on vacation and writing from my phone.  The exception field is by convention a formatted trace back.  What you want is setting exc_info to an exception or a exc_info tuple and the exception formatting processor.

**Comment by hynek** [comment]
I’m assuming this is fixed.  Speak up if there’s something left to be done.
