### ISSUE TITLE
Documentation: How to use pipelines and formatters?

### ISSUE THREAD

**Issue by jdinunzio** [hynek/structlog#136]
Am I the only one confused with the documentation going from "this is the way of using the library":

```python
from structlog import get_logger
log = get_logger()
log.info("key_value_logging", out_of_the_box=True, effort=0)
```

To "by the way, if you want to use formatters, here's this totally different and unconnected piece of code":

```python
from structlog.processors import JSONRenderer
JSONRenderer(sort_keys=True)(None, None, {'a': 42, 'b': [1, 2, 3]})
```

How to I go from `log.info` to `JSONRenderer(something)(a couple of Nones, some_data)`?

May I reccomend to add a couple of examples showing **how** to use those features with the log object in the `Getting started` section?

**Comment by hynek** [comment]
Yes the Getting Started chapter should probably take things farther.

**Comment by hynek** [comment]
I have expanded the introduction a bit; do you find that helpful?

**Comment by jdinunzio** [comment]
Excellent, thank you very much! 

Those examples are spot on. I think most people's first contact with structlog will be looking for JSON logging, and showing that user case will save future users a lot of time.
