### ISSUE TITLE
Unable to use other processors when using KeyValueRenderer

### ISSUE THREAD

**Issue by deinzconie** [hynek/structlog#137]
I'm building a flask app and wanted to use context for incoming requests but I also wanted to log my entries in json format with timestamps etc.

I've modified the flask example provided by adding processors like so (keeping it simple reproduces the issue):
```
    structlog.configure(
        processors=[
            structlog.processors.KeyValueRenderer(
                key_order=["event", "request_id"],
            ),
            structlog.processors.JSONRenderer(serializer=simplejson.dumps),
            structlog.processors.TimeStamper(fmt="iso"),

        ],
        context_class=structlog.threadlocal.wrap_dict(dict),
        logger_factory=structlog.stdlib.LoggerFactory(),
    )
```

And when trying to log something I get this:

```* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2017-08-04 13:46:26,066] ERROR in app: Exception on /login [GET]
Traceback (most recent call last):
  File "flask/app.py", line 1982, in wsgi_app
  File "flask/app.py", line 1614, in full_dispatch_request
  File "flask/app.py", line 1517, in handle_user_exception
  File "flask/_compat.py", line 33, in reraise
  File "flask/app.py", line 1612, in full_dispatch_request
  File "flask/app.py", line 1598, in dispatch_request
  File "structtest.py", line 22, in some_route
    log.info("user logged in", user="test-user")
  File "structlog/_base.py", line 176, in _proxy_to_logger
  File "structlog/_base.py", line 136, in _process_event
  File "structlog/processors.py", line 232, in stamper
TypeError: 'str' object does not support item assignment
```

Is there something else in the config that I'm missing that will fix this or is this genuinely a bug?

**Comment by hynek** [comment]
Your problem is that you only can use *one* renderer (because the renderer converts the event dictionary into something the wrapped logger can work with [usually a str]), and that renderer must come *last*.  Processors are a pipeline and in your example the KeyValueRenderer converted the event dict into a string, that string got rendered into JSON and finally TimeStamper got that string and tried to use it as a dictionary which led to the error you’ve received.

Makes sense?

**Comment by deinzconie** [comment]
Yeah, that makes more sense. I didn't realize it works this way (processors order and 1 renderer)

Is there a way to setup structlog so I can do the following:
- have context for flask routes (endpoints) and the functions that they are being called (just like in the flask example)
- capture all of the stdout from flask (ie: " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)") and format it the same way like other log entries created with structlog
- have all of the entries in json

For example:

```
{"event": "* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)", 
"level": "info", 
"logger":  "__main__", 
"timestamp": "2017-08-05T11:25:43.256097Z"}

{"event": "user logged in", 
"request_id": "2c522f3b-a0d7-4194-aa5c-c5ccddbf80df",
"user": "test-user", 
"level": "info",
"logger":  "__main__", 
"timestamp": "2017-08-05T11:25:57.291036Z"}

{"event": "user did something",
"request_id": "2c522f3b-a0d7-4194-aa5c-c5ccddbf80df",
"something": "shot_in_foot", 
"level": "error", 
"logger":  ".some_module",
"timestamp": "2017-08-05T11:25:57.291327Z"}
```

**Comment by deinzconie** [comment]
Ok, I found my answer here: https://blog.sneawo.com/blog/2017/07/28/json-logging-in-python/
It works like a charm and does pretty much what I wanted.

**Comment by hynek** [comment]
Please note that nowadays there’s more options on how to achieve 100% json logs: http://www.structlog.org/en/stable/standard-library.html#suggested-configurations
