### ISSUE TITLE
ProcessorFormatter stdlib logging with bind()

### ISSUE THREAD

**Issue by jendagroovy** [hynek/structlog#142]
Hi,

I have setup `logging` to render via `structlog` as described at http://www.structlog.org/en/17.2.0/standard-library.html#rendering-using-structlog-based-formatters-within-logging

All works well, but I wanted to ask whether it is possible to make use of `structlog`'s `bind`, like so:

```
logging.config.dictConfig( ... setup via ProcessorFormatter, like the docs say)
log = structlog.get_logger()
log.bind(user_id=555)
logging.info("test")
```

The logged message is rendered using `structlog` but the context with `user_id` is lost.

Thanks,
Jan

**Comment by hynek** [comment]
bind returns a new logger.  you need to write it like `log = log.bind(user_id=555)`

**Comment by jendagroovy** [comment]
So do I need to reconfigure `logging` to use new logger overtime I bind ?

Btw I use thread local dict context, so if I'm not mistaken, the bind updates the context dict so even the old logger can see `user_id`.

**Comment by hynek** [comment]
Ah wait I misread.  What you want is sadly impossible.  ProcessorFormatter knows nothing about the context since that only makes sense for thread local context.  I guess you could write a processor that grabs and adds it.  you'd then add it only to the foreign chain.

**Comment by jendagroovy** [comment]
Thanks, I was thinking I'd have to do something like this. Just wanted to confirm I'm not missing some better way.

So I will grab the context like this:
`get_logger()._context._dict`

And just update `event_dict` in foreign processor.

**Comment by maiamcc** [comment]
> Btw I use thread local dict context, so if I'm not mistaken, the bind updates the context dict so even the old logger can see user_id.

@jendagroovy if you're using thread local context as described in [the docs](http://structlog.readthedocs.io/en/stable/thread-local.html), I'm pretty sure the docs are in error (will be submitting a pull request shortly). The docs say you ought to do:

```
from structlog.threadlocal import wrap_dict
WrappedDictClass = wrap_dict(dict)
structlog.configure(context_class=WrappedDictClass())
```
i.e. using an _instance_ of the class as the `context_class`. However, pretty sure that you have to use _the class itself_ rather than an instance, i.e.:

```
structlog.configure(context_class=WrappedDictClass)
```

Can you send your specific configuration call along?

**Comment by jendagroovy** [comment]
I have something like this:

```
processors = [
    structlog.stdlib.add_log_level,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.TimeStamper('iso'),
    structlog.processors.ExceptionPrettyPrinter(),
    structlog.processors.UnicodeDecoder(),
    structlog.dev.ConsoleRenderer(pad_event=25),
]

structlog.configure_once(
    processors=processors,
    logger_factory=structlog.PrintLoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    context_class=structlog.threadlocal.wrap_dict(dict),
)
```

which is the right config, according to what you write. Anyway I have managed to achieve what I needed, just wanted to know if I have used the right API to do so.

**Comment by maiamcc** [comment]
Ah gotcha, I didn't catch that the problem was the interaction btwn `structlog` and `logging`. Never mind, then!

**Comment by hynek** [comment]
I’m gonna close this, thanks everyone for cooperating. :)
