### ISSUE TITLE
Failure in TestExtractStuffAndWhy with Twisted 17.9

### ISSUE THREAD

**Issue by vincentbernat** [hynek/structlog#144]
Hello,

Following bug [#876988 in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876988), when I try to run tests with Twisted 17.9 installed, I get the following error:

```
================================================= FAILURES =================================================
_______________________________ TestExtractStuffAndWhy.test_handlesFailures ________________________________

self = <tests.test_twisted.TestExtractStuffAndWhy object at 0x7f2a8a4917d0>

    def test_handlesFailures(self):
        """
            Extracts failures and events.
            """
        f = Failure(ValueError())
>       assert (
            (f, "foo", {}) ==
            _extractStuffAndWhy({"_why": "foo",
                                 "_stuff": f})
        )
E       AssertionError: assert (<twisted.pyt... >, 'foo', {}) == (<twisted.pyth... >, 'foo', {})
E         At index 0 diff: <twisted.python.failure.Failure exceptions.ValueError: > != <twisted.python.failure.Failure exceptions.ValueError: >
E         Full diff:
E         (<twisted.python.failure.Failure exceptions.ValueError: >, 'foo', {})

tests/test_twisted.py:117: AssertionError
============================= 1 failed, 229 passed, 10 skipped in 0.50 seconds =============================
```

Putting some print arounds, the problem is that `isinstance(_stuff, BaseException)` is true, so we create a new encapsulate `_stuff` twice. I'll propose a fix shortly.

**Comment by hynek** [comment]
I don’t have the time to deal with it immediately, but it seems like it's related to:

- https://twistedmatrix.com/trac/ticket/5519
- https://twistedmatrix.com/trac/ticket/9307

I’ll need a moment to read/understand what’s actually going on.

**Comment by vincentbernat** [comment]
Any news? After looking at the first ticket, I think my fix is correct: `Failure` now inherits of `BaseException` and therefore, the condition should be updated. Maybe you are worried of other side-effects of this change?
