### ISSUE TITLE
Overwriting exc_info in `exception()`

### ISSUE THREAD

**Issue by Hardtack** [hynek/structlog#149]
_structlog_ set the `exc_info` keyword argument to `True` in `exception()` (https://github.com/hynek/structlog/blob/c7a59257cab8a008ebf2b8e363612e2b1ef33f75/src/structlog/stdlib.py#L89-L95)
This always make logger to load `exc_info` from `sys.exc_info()`. But sometimes, I want to log exception with another `exc_info`.
I surely can use `error()` instead. But _logging_ module, the builtin logging library of Python, does not overwrite given `exc_info` and just give default value for that.
``` python
def exception(msg, *args, exc_info=True, **kwargs):
    """
    Log a message with severity 'ERROR' on the root logger, with exception
    information. If the logger has no handlers, basicConfig() is called to add
    a console handler with a pre-defined format.
    """
    error(msg, *args, exc_info=exc_info, **kwargs)
```
The difference between _structlog_ and _logging_ module makes user confuse.
I've been used builtin logging library for a long time, and I've always used `exception()` for logging `exc_info`. So I mistakenly use `exception()` with `exc_info` very often.
Could you make _structlog_ not to overwrite given `exc_info`?

Just like this
``` python
def exception(self, event=None, *args, **kw):
    """
    Process event and call :meth:`logging.Logger.error` with the result,
    after setting ``exc_info`` to `True`.
    """
    kw.setdefault('exc_info', True)
    return self.error(event, *args, **kw)
```

**Comment by hynek** [comment]
It sounds reasonable to make it conditional.
