### ISSUE TITLE
how to use pytest caplog with structlog?

### ISSUE THREAD

**Issue by rachmadaniHaryono** [hynek/structlog#150]
i'm trying to test the debug message using [pytest's caplog](https://docs.pytest.org/en/latest/logging.html?highlight=caplog)

```python
import structlog
log = structlog.getLogger(__name__)


def f1():
    log.debug('text', v=1)


def test_f1(caplog):
    f1()
    assert caplog.records
```

when running this test the caplog's records should contain the message from log instead empty list

is there any setting to be configured so it can catch the debug message?

packages:

- pytest==3.3.2
- structlog==17.2.0

**Comment by hynek** [comment]
structlog doesn't use stdlib logging by default, therefore caplog won’t ever see it.

Either configure structlog to use stdlib or use `capsys` instead.

**Comment by rachmadaniHaryono** [comment]
thanks for the answer. here is the result when using capsys

```python
import structlog
import re
log = structlog.getLogger(__name__)


def f1():
    log.debug('text', v=1)


def test_f1(capsys):
    f1()
    out = capsys.readouterr().out
    # '\x1b[2m2018-01-18 22:34.39\x1b[0m \x1b[1mtext                          \x1b[0m \x1b[36mv\x1b[0m=\x1b[35m1\x1b[0m\n'
    ansi_escape = re.compile(r'\x1B\[[0-?]*[ -/]*[@-~]')
    cleaned = ansi_escape.sub('', out)
    print(cleaned)
    #  '2018-01-18 22:29.43 text                           v=1\n'
    assert 'text                           v=1\n' == cleaned.split(' ', 2)[2]
```

method to remove ansi escape sequence taken from here

https://stackoverflow.com/questions/14693701/how-can-i-remove-the-ansi-escape-sequences-from-a-string-in-python

**Comment by wimglenn** [comment]
If you want to assert on events (Python dicts) instead of the rendered console output (text) then check out my plugin [`pytest-structlog`](https://github.com/wimglenn/pytest-structlog).
