### ISSUE TITLE
Optional sanitizaition of secrets in structlog

### ISSUE THREAD

**Issue by janmasarik** [hynek/structlog#152]
Do you think that something like [this in sentry](https://github.com/getsentry/raven-python/blob/68487496abc11a2c62effebc7e9dec1a16ef0544/raven/processors.py#L68) could be also possible in structlog?

It could for example try to get `dict` or `load` every dumped dict, sanitize it and dump it again. 

This could however have some potential drawbacks in performance, so it would probably be only optional feature with warning.

What do you think @hynek ?

**Comment by hynek** [comment]
That’s precisely what structlog processors are for.

```python
def sanitize_secrets(_, __, ed):
    ed["password"] = "***"
    return ed
```

**Comment by janmasarik** [comment]
You are right:(, i was blind. Thanks for answer and sorry for bothering!
