### ISSUE TITLE
Default configuration does not include log level

### ISSUE THREAD

**Issue by stefanv** [hynek/structlog#154]
The default configuration does not include information about log level.  This makes for surprising behavior when doing `log.info`, `log.error`, etc. and not seeing any difference in the output.

This may very well be by design, but if so it may be helpful to add a snippet to the documentation to show how to add those levels back in:

```
structlog.get_config()['processors'].insert(0, structlog.stdlib.add_log_level)
```
I'm not sure it's "safe" use of the API to modify that dictionary directly, but wasn't sure how to "update" the current configuration otherwise.

**Comment by hynek** [comment]
The default configuration doesn’t use stdlib at all which means it doesn’t have a concept of log levels. I’m confused. :)

**Comment by stefanv** [comment]
Yes, I think for a newcomer it is a bit confusing because the API has these methods (`log.info`, `log.error`, etc.) and then you run across `level_styles` and `get_default_level_styles` in the docs, but they seemingly have no effect.  Until you add the log level that is.  A note guiding the user to the right place may be all that's needed.

**Comment by ncraike** [comment]
I'm evaluating `structlog` for a particular use case, and I'm also confused by the state of log levels. I'm considering writing a custom logger, but it's unclear from the documentation what the minimum methods I should implement on a custom class.

> The default configuration doesn’t use stdlib at all which means it doesn’t have a concept of log levels.

You've said this, but even loggers which have nothing to do with the stdlib like [`PrintLogger`](https://github.com/hynek/structlog/blob/master/src/structlog/_loggers.py#L79) and [`ReturnLogger`](https://github.com/hynek/structlog/blob/master/src/structlog/_loggers.py#L127) include methods `debug`, `info`, `warn`, `error`, `critical` and others, although in those cases they are all aliases to `msg`.

Are these to maintain compatibility with stdlib/Twisted loggers somehow? Should all loggers include these aliases? If I leave them out, can I expect `structlog` to never try calling them?

**Comment by hynek** [comment]
Yes, they're mostly there to maintain drop-in compatibility with Twisted/stdlib logging. We might add an own level system for performance reasons one day, but nothing is there yet.

> Should all loggers include these aliases?
> If I leave them out, can I expect structlog to never try calling them?

`structlog` propagates the name of the logging method from the frontend that you've used in your BoundLogger. So if you don't call a method in the frontend, it never gets called in the backend: https://github.com/hynek/structlog/blob/3b534afd4f27067502ebacd686cb190c26c6e5f8/src/structlog/_base.py#L167-L192

So for your own projects you can do whatever you want.

**Comment by anentropic** [comment]
I have been skimming through the docs and could not work out how log levels are supposed to work

All of the log level methods seem to just be aliases of `log.msg`
https://www.structlog.org/en/stable/_modules/structlog/_loggers.html#PrintLogger.msg
or here:
https://www.structlog.org/en/stable/_modules/structlog/testing.html#ReturnLogger.msg

I don't see how any info about log level gets any further than this?

Is the idea that I should bind the log-level as a variable and use different derived loggers for different levels, just calling `log.msg` on each?

**Comment by anentropic** [comment]
Ah no, it must be this:
https://www.structlog.org/en/stable/getting-started.html#structlog-and-standard-library-s-logging

the `LoggerFactory` must give you something different from the loggers I found above, the example clearly shows using `log.warning` and having that info passed through to the underlying stdlib logger and output as WARNING

**Comment by hynek** [comment]
Log levels only work with stdlib logging therefore you have to look in the stdlib module: https://github.com/hynek/structlog/blob/8b7223324d670d64b7924255ed5903711d88f6f5/src/structlog/stdlib.py#L57 et seq

**Comment by anentropic** [comment]
Thanks for this library - it is good and does everything that I need 👍  
(it just had a bunch of things I needed to get my head around initially)

**Comment by hynek** [comment]
`add_log_level` has been "copied" to `processors` and is part of the default config now.

Y'all using native log levels should also have a look at the new [LevelFilter processor](https://www.structlog.org/en/latest/api.html#structlog.processors.LevelFilter).
