### ISSUE TITLE
Extract renderers into a separate API from processors?

### ISSUE THREAD

**Issue by brutasse** [hynek/structlog#16]
First, structlog is awesome :)

Integrating structlog in a Django project I wrote a `get_logger` function that formats logs with `KeyValueRenderer` in development and `JSONRenderer` + some extra stuff for logstash in production.

```python
def get_logger(name):
    processors = [format_exc_info]

    if settings.DEBUG:
        processors.append(KeyValueRenderer())
    else:
        processors.extend([logstash_processor, JSONRenderer()])

    return wrap_logger(logging.getLogger(name), processors=processors)
```

However at first I didn't add the `KeyValueRenderer` in dev. It's only when looking at the default processors that I saw it. Without it I got exceptions when logging stuff because the signature of `BoundLoggerBase._process_event` changes depending on the type returned by the last processor:

https://github.com/hynek/structlog/blob/master/structlog/_base.py#L141-L144

With only `[format_exc_info]` the processor returns a dict, making `_process_event()` return the same dict and breaking this call (unpacking error):

https://github.com/hynek/structlog/blob/master/structlog/_base.py#L170

And then after reading the docs I found [this paragraph](http://www.structlog.org/en/0.4.0/processors.html#adapting-and-rendering) which highlights the importance of the last processor :)

In the end it's not a bug in structlog but rather me failing to read and understand.

However… do you think the processors API be split into processors (which process and return dicts all the time) and a "renderer" that does something with the final structure? My `get_logger` would become:

```python
def get_logger(name):
    processors = [format_exc_info]

    if settings.DEBUG:
        renderer = KeyValueRenderer()
    else:
        processors.append(logstash_processor)
        renderer = JSONRenderer()

    return wrap_logger(logging.getLogger(name), processors=processors, renderer=renderer)
```

I'd find the API nicer with such a separation :)

**Comment by hynek** [comment]
I feel like this is solved especially after #26 has landed.  Renderers are just optional and a processor; not hing more. *shrug*
