### ISSUE TITLE
Permission to generate stubs for structlog in typeshed

### ISSUE THREAD

**Issue by waseem18** [hynek/structlog#165]
Hi Hynek,

I would like to add stubs for structlog to https://github.com/python/typeshed, a repository used to store PEP 484 type signatures for the Python stdlib and popular third party libraries. As per PEP 484, permission is required from the library owner before merging type signatures into typeshed - https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo

These stubs will be used by mypy and Pycharm. I'll start working on creating stubs after I get permission from you and do let me know if you have any suggestions.

Thanks

**Comment by hynek** [comment]
Actually I would prefer if you’d contribute them to structlog proper! Packages can ship their own stubs now.

If you’d agree to do that, I’d add an AbstractBoundLogger first.

**Comment by waseem18** [comment]
@hynek Good to know that packages can ship their own stubs now. Will surely go in that way.

However I didn't get what you meant by 
> If you’d agree to do that, I’d add an AbstractBoundLogger first.

**Comment by hynek** [comment]
Re: AbstractBoundLogger: I suspect it’s easier to build stubs if there’s an abstract interface that fits all bound loggers.

The docs for stubs-via-package are here btw: http://mypy.readthedocs.io/en/latest/installed_packages.html

**Comment by waseem18** [comment]
@hynek Thanks for the link

It would surely be efficient if there's an abstract interface for bound loggers.

So what all loggers do you think would be better to abstract out?

**Comment by hynek** [comment]
So I just noticed that untypically for me, I already have a base class that all loggers derive from: `structlog.BoundLoggerBase`!

So just use that, I may or may not add an abc at some point, but it’s nothing you need to wait for.

***

One more thing: unless you can come up with a good reason, I’d say we don’t use a `.pyi` file and write the annotations into the code in Python 2-style: http://mypy.readthedocs.io/en/latest/python2.html

Let me know if you need anything or anything is unclear.

**Comment by hynek** [comment]
Any progress? 😇

**Comment by waseem18** [comment]
Hi @hynek 

I was on a vacation and completely forgot about this. 

I've started going through the code base and I'm loving it. I'm planning to start on type-hinting from this weekend.

**Comment by haizaar** [comment]
Good day guys,
Do you know if there was any progress on this issue?

**Comment by sebpiq-kialo** [comment]
@waseem18 any progress on this ?

**Comment by waseem18** [comment]
Sorry folks, I couldn't get to work on it. Anyone interested can pick it up.

Thanks

**Comment by sebpiq-kialo** [comment]
@waseem18 ok thanks for the update. I might pick it :)

**Comment by lg-kialo** [comment]
@hynek 

Concerning the preference of Python 2-style type comments over `.pyi` stubs: with type comments, it's not possible (AFAIK) to have conditional typing based on the Python version.
This seems to be a problem, given that the types of the `logging` package are different in Python 2 and 3 (see [link](https://github.com/python/typeshed/blob/master/stdlib/2and3/logging/__init__.pyi)), making it difficult-if-not-impossible to properly add typings to `structlog`.
Is this a good enough reason to switch to `.pyi` typings?

**Comment by hynek** [comment]
I honestly don't have too strong feelings about it, so if you have good reasons, go wild.

**Comment by paravoid** [comment]
Isn't this issue moot given #282 was merged?

**Comment by hynek** [comment]
Very much so! I wasn't aware it's still open – thank you for pointing it out.
