### ISSUE TITLE
ConsoleRenderer sorts keys when formatting

### ISSUE THREAD

**Issue by psviderski** [hynek/structlog#166]
I try to use `ConsoleRenderer` in my project and found it really nice looking. But there is one inconvenience that my intended order of `event_dict` keys is ignored when `ConsoleRenderer` formats them.

I have several questions on this matter:
* Was that done deliberately that it sorts keys when formatting? https://github.com/hynek/structlog/blob/master/src/structlog/dev.py#L226
* Can we have an option to have control on that like `sort_keys` in `KeyValueRenderer`?
* Is this a good idea to use `ConsoleRenderer` not only for development purpose but also in production for formatting logs that are written to a file? (the configuration is similar to specified in the [documentation](http://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging))

**Comment by hynek** [comment]
This has been fixed.
