### ISSUE TITLE
How to integrate structlog with Apache-Airflow?

### ISSUE THREAD

**Issue by caddac** [hynek/structlog#170]
We're using [Apache-Airflow](https://airflow.apache.org/) in Docker (using this [image](https://github.com/puckel/docker-airflow)) and would like to get structured logging output. Airflow has its own logging configuration (as its a full application(s) as opposed to a library). 

Any guidance or suggestions you have around integrating structlog with a python _application_ would be greatly appreciated. Can you suggest the best integration scheme for this scenario?

**Comment by hynek** [comment]
This is a kinda difficult question because I’ve never used Airflow. Does it have *some* initialization hook or any other way to run code on startup?

**Comment by hynek** [comment]
If you haven't figured it out, please try StackOverflow with the `structlog` tag. Chances are higher that someone who knows a thing about Airflow finds it there than here!
