### ISSUE TITLE
How to replace renderer or sort keys for single log call

### ISSUE THREAD

**Issue by md1023** [hynek/structlog#176]
I've got single case where keys have to be sorted:
```
    info = {
        'username": 'unknown',
        'metric_name': 'create'
    }
    structlog.get_logger().info(
        sort_keys=True,
        **info
    )
```
Would output:
```
{"metric_name": "create", "username": "unknown"}
```
Unfortunately, keys aren't sorted this way and I don't want to put `sort_keys=True` into global config's `JSONRenderer`. Is there a way to do this locally only here?

**Comment by hynek** [comment]
You could write yourself a processor that looks for `sort_keys` being `True`, remove it from the event_dict and return an Ordered Dict I guess? Shouldn’t be more than 5 LoC.
