### ISSUE TITLE
How to log boto3 messages?

### ISSUE THREAD

**Issue by lighthill** [hynek/structlog#177]
Is there a way to redirect [boto3](https://boto3.readthedocs.io/en/latest/_modules/boto3.html) log messages to structlog?

**Comment by hynek** [comment]
Probably if you use structlog's standard library integration: http://www.structlog.org/en/stable/standard-library.html ?

**Comment by kristofferpeterhansel** [comment]
As far as I can tell that page tells you to do 1 of 3 things:
1) Output  and render though Python logging and don't get a bunch of formatting features from structlib
2) Output though Python logging but attempt to use structlib for rendering for both, and seemingly loose structlib functionality
3) Output though Python logging but only render structlib messages in structlib - and not get any control over what comes from 3rd party dependencies

Common for all three options is you are going to have to use other things than just structlib to get the logging you want

**Comment by kristofferpeterhansel** [comment]
Seems to be related to the closed #131  BTW

**Comment by hynek** [comment]
The [third option](https://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging) got *a lot* more powerful in the past years. I think this is the best we can do without starting to monkeypatch.
