### ISSUE TITLE
Standard way to get current context ?

### ISSUE THREAD

**Issue by oceyral** [hynek/structlog#183]
Hi,

I'm currently using structlog similarly to what is documented [here](http://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging).

I am also using `structlog.threadlocal.wrap_dict` in order to have persistent context throughout the application without passing stuff around.

This is works pretty well, except for the fact that, obviously, my dependencies use the standard library python logging, which means that those logs do not have the context attached.

I got around to it by adding a processor in front of the `foreign_pre_chain` of `structlog.stdlib.ProcessorFormatter` to inject the current event dict into the log, just like the doc proposes for timestamps and log level : 
```python
    handler = logging.StreamHandler()
    handler.setFormatter(
        structlog.stdlib.ProcessorFormatter(
            processor,
            foreign_pre_chain=[inject_event_dict] + procs
        )
    )
```
and the function :
```python
import structlog

log = structlog.get_logger()

def inject_event_dict(test, level, event_dict):
    event_dict.update(log._context._dict)
    return event_dict
```

This works perfectly well as far as I can see, except for the fact that accessing those underscore-prefixed variables makes me feel like I'm doing something very wrong here.

Is there a more "standard" way to access the event dict for the current context ? I haven't seen anything like it in the documentation, maybe I missed something ?

Full config just in case it's any use : 
```python
import logging

import structlog

log = structlog.get_logger()

def configure_logging():
    procs = [
        structlog.stdlib.add_log_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
    ]

    try:
        import colorama
        renderer=structlog.dev.ConsoleRenderer()
    except ImportError:
        renderer=structlog.processors.JSONRenderer()

    handler = logging.StreamHandler()
    handler.setFormatter(
        structlog.stdlib.ProcessorFormatter(
            renderer,
            foreign_pre_chain=[inject_event_dict] + procs
        )
    )
    root_logger = logging.getLogger()
    root_logger.addHandler(handler)
    root_logger.setLevel(logging.INFO)

    structlog.configure(
        processors=procs + [
            structlog.stdlib.ProcessorFormatter.wrap_for_formatter
        ],
        context_class=structlog.threadlocal.wrap_dict(dict),
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True,
    )

def inject_event_dict(test, level, event_dict):
    event_dict.update(log._context._dict)
    return event_dict
```

**Comment by hynek** [comment]
`structlog.threadlocal.wrap_dict(dict)` creates your thread-local dictionary. So if you save it in a global variable before passing into `context_class` you should be able to access it?

**Comment by lucas-james** [comment]
In case anyone else looks at this, here's a way I solved it without needing a global variable:
```
context_class = structlog.get_config().get('context_class')
if context_class:
    return context_class()
return {}
```
You can obviously do your own thing if context class hasn't been configured, e.g. raise an exception instead, but for my purposes this worked perfectly.
