### ISSUE TITLE
Using structlog in unittest assertions

### ISSUE THREAD

**Issue by rmagier1** [hynek/structlog#185]
In the past I have used libraries such as https://testfixtures.readthedocs.io/en/latest/logging.html and https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertLogs to assert that a log message was created during a specific test. 

It seems however that structlog isn't detected in these libraries. Is there a way in unittests to assert a specific message is generated in the structlog object?

**Comment by hynek** [comment]
Yeah um so um I have to admit that this is one of the oldest things I wanted to do: #14 I found it good enough to just use pytest’s log recorder and check for substrings/`in`. There are some hints in #14 how others do it; the reason we don’t have anything official is 100% my laziness.

**Comment by hynek** [comment]
Support fort this has been merged and will be released soon: http://www.structlog.org/en/latest/testing.html
