### ISSUE TITLE
ConsoleRender accepts only string as input

### ISSUE THREAD

**Issue by tyler46** [hynek/structlog#186]
Hello :)

First of all I would like to thank you for this very handy package. 

I have observed the following:

```python
import structlog

structlog.configure(
    processors=[
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.dev.ConsoleRenderer()
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

mylogger = structlog.get_logger('foo').new()

mylogger.info('bar')
>> 2018-11-08T10:49:46.903028Z [info  ] bar              [foo]

mylogger.info({'value': 'bar'})
>> Raises TypeError: unsupported operand type(s) for +: 'dict' and 'str'
```

After checking the code for ConsoleRender, it seems that it has been implemented to accept only str as value to log. On the other hand when using JSONRenderer, it logs without any problem a single dictionary as log message. Is this by design ? Am I missing something ?

**Comment by hynek** [comment]
Hmm, I feel like I’ve answered this before but can't find it. 🤔

Anyhow, event names should indeed be strings, structlog offers you to structure the whole record as a dict, so why would you want the name to be a dict? in your case it should be `mylogger.info("something-happened", value="bar")`.

What's your use case here, or is it just about dumping data?

**Comment by therefromhere** [comment]
I just hit this as well, it's not a huge issue but it is a hiccup in migrating from stdlib logging, since that would automatically stringify the first parameter.

Would you accept a PR to have ```event = str(event_dict.pop("event"))``` here?

https://github.com/hynek/structlog/blob/a28d34c3663a391ee10093e840262b610ba9da47/src/structlog/dev.py#L201-L205

**Comment by hynek** [comment]
At this point I guess I would since it's the development logger whose performance is secondary and people seem to keep running into it.
