### ISSUE TITLE
Inconsistency of BoundLogger with logging.Logger

### ISSUE THREAD

**Issue by decaz** [hynek/structlog#190]
There are no public attributes of `logging.Logger` available within `BoundLogger` (`propagate` for instance).
Also there are no attributes or methods of `logging.Filterer` (which is parent class of `logging.Logger`) available within `BoundLogger`.

**Comment by hynek** [comment]
That’s on purpose…what would you expect them to do?

**Comment by decaz** [comment]
@hynek I expect them to proxy to original attributes or methods.

The problem occured when I tried to replace my Flask app's default logger with `BoundLogger`. I use `raven` library and it checks `propagate` attribute of logger: https://github.com/getsentry/raven-python/blob/master/raven/contrib/flask.py#L297. Of course it leads to an error.

**Comment by decaz** [comment]
Another one example of logger's `name` attribute usage: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web.py#L394 (raises exception if `BoundLogger` was specified at `aiohttp.web.run_app(access_log=...)`).

**Comment by hynek** [comment]
I suppose the easiest way for you would be to use the dynamic default logger that will just proxy everything to the wrapped logger? I’m not sure it’s worth it to play whack-a-mole with the whole API to catch all possible usages. 🤔

**Comment by decaz** [comment]
What do you mean by "dynamic default logger" and how it can be used with the `BoundLogger`?

**Comment by hynek** [comment]
If I’m not mistaken, it should be enough to _not_ configure `wrapper_class`. Then you'll get https://www.structlog.org/en/stable/api.html#structlog.BoundLogger which will forward every unknown method call (i.e. everything except bind/unbind/new) to the wrapped logger.
