### ISSUE TITLE
"Best practices" documentation should explicitly state they refer to server-side logging

### ISSUE THREAD

**Issue by itamarst** [hynek/structlog#191]
Talking to someone who was confused about what to do for logging in a CLI tool after reading structlog's best practices. So maybe clarify the domain it applies to; just a sentence would do.

**Comment by hynek** [comment]
Hm, what would you suggest? I use it a ton in CLI tools but mostly in the default config because it looks nice. :)

**Comment by itamarst** [comment]
Sorry, should've been more clear. All the advice in that page is server-specific - stdout, centralized logging, etc.. So header saying "Server best practices" would clarify that's not for CLI.

I do have thoughts on client best practices, but that's slightly distinct issue.
