### ISSUE TITLE
Help with processor for new sentry sdk

### ISSUE THREAD

**Issue by viperfx** [hynek/structlog#193]
Sentry has a new unified SDK - https://github.com/getsentry/sentry-python

They also have a new way to set context scopes and isolated scopes usings "hubs". 

See:
- https://docs.sentry.io/enriching-error-data/context/?platform=python
- https://docs.sentry.io/enriching-error-data/scopes/?platform=python

 I found an old gist you made @hynek - https://gist.github.com/hynek/a1f3f92d57071ebc5b91

But I was hoping you could help me update to the new sentry SDK?

I am currently using a Django middleware too, to set request ID to all new request-response cycles.

```
import uuid
import logging
from structlog import wrap_logger
import sentry_sdk

logger = wrap_logger(logger=logging.getLogger("structlog_logger"))


class RequestIdMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        # If there's an `X-Request-Id` header on the request,
        # bind it to our Sentry SDK scope.
        request_id = request.META.get("HTTP_X_REQUEST_ID", str(uuid.uuid4()))
        if request_id:
            with sentry_sdk.configure_scope() as scope:
                scope.set_tag("request_id", request_id)
        logger_values = dict(request_id=request_id)
        logger.new(**logger_values)
        return self.get_response(request)
```

It would be great to understand what the best practice for using structlog together with sentry. I am thinking right now, I would like to replace my `client.captureException()` calls with structlog's `log.exception()` calls, that goes to a sentry structlog processor and passes along the request ID and logs the exception in sentry too.

**Comment by hynek** [comment]
TBH I've moved away from submitting exceptions automatically as in the gist.

What I do nowadays is writing an explicit middleware that catches errors and then depending on the error reports it or not. Doing it automatically just gave me too many uninteresting errors.

If you'd like to pass structlog's context along with the error, you could probably just pull it out when reporting? As in `logger._context` – maybe we should add an official API for it after all.

**Comment by viperfx** [comment]
Thanks for the quick reply. 

Here is my config so far:

```
structlog.configure_once(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.UnicodeDecoder(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    context_class=structlog.threadlocal.wrap_dict(dict),
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

```

So I have tested out the sentry sdk, the most recent release. What happens so far (with no processor btw).

- log.exception("msg"), structlog puts log line with context and strack trace as expected.
- sentry picks up this exception and sends it.
- I see structlog entries in the breadcrubs.
- The last breadcrumb is the exception log, with the `exception` key attached with traceback.

This is actually not too bad so far. 

The only thing I would like to change, all the structlog breadcrumbs are json - I did not tell it to format as JSON?

The message/title of the sentry message is the final exception log, with JSON formatted. This is quite unreadable. I would like to get sentry to use the `msg` in `log.exception("msg")`.

Any thoughts on those two points?

It would be great if you could share your current processor (if you are using latest sentry sdk) - if its not too specific to a project. I think an official API is not a bad idea at all, or atleast a page on best practices, because sentry is so popular in the python world.

**Comment by viperfx** [comment]
Here is my work around for now:

```

structlog.configure_once(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.UnicodeDecoder(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    context_class=structlog.threadlocal.wrap_dict(dict),
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
import logging

sentry_sdk.init(
    dsn="DSN",
    integrations=[
        DjangoIntegration(),
        LoggingIntegration(level=logging.INFO, event_level=None)
    ],
)
```

```
try:
   .....
except:
   log.exception(u"failed sending report to {name}".format(name=name))
   capture_exception()
```

**Comment by viperfx** [comment]
Any progress on this? 

I recently found that structlog was not propagating some stack traces. This was happening for background workers such as heuy and celery. 

I found the stack traces in the logs, but sentry was not getting them.

Any ideas why?

**Comment by hynek** [comment]
Is this some kind of regression to a previous behavior? structlog doesn't propagate exceptions on itself, it sound like some kind of `logging` setups thing?

**Comment by viperfx** [comment]
This is the logging config in Django.

```
LOGGING = {
    "version": 1,
    "formatters": {
        "simple": {"format": "%(message)s", "datefmt": "%y %b %d, %H:%M:%S"},
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "fmt": "%(name)s %(asctime)s %(message)s",
        },
        "verbose": {
            "format": "%(levelname)s|%(asctime)s|%(module)s|%(process)d|%(thread)d|%(message)s",
            "datefmt": "%d/%b/%Y %H:%M:%S",
        },
        "plain": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(colors=False),
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "logfile": {
            "level": "DEBUG",
            "class": "my_timber.TimberHandler",
            "filename": os.path.join(BASE_DIR, "logs", "django.log"),
            "maxBytes": 1024 * 1024 * 10,
            "formatter": "json",
        },
        "log_generic_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "django.log"),
            "maxBytes": 1024 * 1024 * 10,
            "formatter": "plain",
        },
    },
    "loggers": {
        "celery": {"handlers": ["console"], "level": "INFO"},
        "loggly_logs": {"handlers": ["logfile"], "level": "DEBUG", "propagate": True},
        "structlog_logger": {
            "handlers": ["log_generic_file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}
```


This is how we usually setup struct log at the top of each file

```
slog = wrap_logger(logger=logging.getLogger("structlog_logger"))
```

**Comment by hynek** [comment]
This means that you don't configure structlog at all? It's most likely eating your exceptions.

I would _strongly_ suggest to configure structlog to play nice with stdlib and everything should work perfectly fine: https://www.structlog.org/en/stable/standard-library.html

**Comment by j-walker23** [comment]
@viperfx I don't use django but with flask and sentry I just pop off the `event` key which is the message and use it to replace the full dict that is being logged.

I use the `before_send` and `before_breadcrumb` to accomplish this.

I also use the default `LoggingIntegration`, not sure if you're keyword args being added change anything.

**Comment by JanBednarik** [comment]
Inspired and based on Gist from @hynek we have made processor for new Sentry SDK. It may be helpful for solving this issue: https://github.com/kiwicom/structlog-sentry

**Comment by hynek** [comment]
Cool, thanks! I have added it to https://github.com/hynek/structlog/wiki/Third-party-Extensions
