### ISSUE TITLE
Customise format of ConsoleRenderer

### ISSUE THREAD

**Issue by viperfx** [hynek/structlog#194]
Currently in production, I am using 
```
LOGGING["formatters"]["colored"] = {
    "()": structlog.stdlib.ProcessorFormatter,
    "processor": structlog.dev.ConsoleRenderer(colors=True),
    "format": "%(message)s [%(module)s.%(funcName)s:%(lineno)d]",
}
```
To get no color output and logged to a file.

```
[info     ] Running report  account_status=trialing is_automated=False report_slug=3HYUFB
```

Currently, I use datadog for my logging and if there is a level=info key, it will pick it up and mark correct log level.

I tried to add the following as a processor but it did not seem to add a level key to the log line.

```
def add_log_level_to_event(logger, method, event_dict):
    event_dict['level'] = method
    return event_dict
```

Is it also possible to remove the `[info]` at the start?

**Comment by hynek** [comment]
ConsoleRenderer ist absolutely not for production use. Why don't you use [KeyValueRenderer](https://www.structlog.org/en/stable/api.html#structlog.processors.KeyValueRenderer)?

**Comment by viperfx** [comment]
Thanks. I opted to use JSONRenderer in production.
