### ISSUE TITLE
Best practices for command line interface?

### ISSUE THREAD

**Issue by gsemet** [hynek/structlog#196]
Hi. We intensively use structlog in our programs and has been a real game changer for structured logging.
However, I often have to do the same big boilerplate to have the following behavior for command line interface:
- by default, only print the event name, no values, no timestamps. This is a bit trick to do actually, I donot know how to do it cleanly because all my code use structlog's getlogger that can reconfigure the output
- a -vvv or --debug option that unleash structlog rendering and that's the cool part of it.

However most of my users complains they the a simple logging (like basic_config()) is not clear enough. I hacked into the renderer to support lazy logger calls (`log.debug("my event name with some data %s and %s", data1, data2)`) but that not satisfying enough.

What is you opinion on how should I do? I really like the structlog logger for debug output but I still want a clean non-debug output.

**Comment by gsemet** [comment]
The boilerplate is:
```python
    if verbose:
        logging.basicConfig(
            format="%(message)s", stream=sys.stdout, level=logging.DEBUG
        )
        structlog.configure(
            processors=[
                structlog.stdlib.add_log_level,
                structlog.stdlib.PositionalArgumentsFormatter(),
                structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M.%S"),
                structlog.processors.StackInfoRenderer(),
                structlog.processors.format_exc_info,
                structlog.dev.ConsoleRenderer()  # <===
            ],
            context_class=dict,
            logger_factory=structlog.stdlib.LoggerFactory(),
            wrapper_class=structlog.stdlib.BoundLogger,
            cache_logger_on_first_use=True,
        )
    else:
        logging.basicConfig(
            format="%(message)s", stream=sys.stdout, level=logging.INFO
        )
        structlog.configure(
            processors=[
                structlog.stdlib.filter_by_level,
                structlog.stdlib.add_logger_name,
                structlog.stdlib.add_log_level,
                structlog.stdlib.PositionalArgumentsFormatter(),
                structlog.processors.StackInfoRenderer(),
                structlog.processors.format_exc_info,
                structlog.processors.UnicodeDecoder(),
                structlog.stdlib.render_to_log_kwargs,
            ],
            context_class=dict,
            logger_factory=structlog.stdlib.LoggerFactory(),
            wrapper_class=structlog.stdlib.BoundLogger,
            cache_logger_on_first_use=True,
        )
```

I still use "print" in my CLI to interact with people, but I wonder if "logging" could not do this job completely

**Comment by hynek** [comment]
Hm I personally mix and match structlog and `click.echo()` + `click.style()` depending on what's happening.

For example when I'm running a deployment, I use structlog with the additional tidbit that I overwrite timestamps with data coming from APIs and use the k/v pairs for deployment IDs, states etc.

When telling the user simple things, I just go for `click.echo()`.

One thing to consider is whether the timestamps are _that_ bad. Sometimes it can be useful to be able to check back, how long a certain action took. I'm gonna say follow your gut and your user's aesthetics? `¯\_(ツ)_/¯`
