### ISSUE TITLE
Website preview / thumbnail for https://www.structlog.org/en/stable/

### ISSUE THREAD

**Issue by dimaqq** [hynek/structlog#197]
`structlog` logo is seriously kick-ass. also pretty weird. but more awesome than creepy.

I wish https://www.structlog.org/en/stable/ had a working preview (slack) / thumbnail (facebook) to show off the logo and title when posting this URL :)

**Comment by hynek** [comment]
I guess that's a feature request for https://github.com/bitprophet/alabaster? 🤔

**Comment by hynek** [comment]
https://www.structlog.org/en/latest/ has now basic OG/Twitter metadata.
