### ISSUE TITLE
Add support of aiologger

### ISSUE THREAD

**Issue by decaz** [hynek/structlog#199]
It would be nice to support the async/await syntax of `aiologger`: https://github.com/B2W-BIT/aiologger#using-aiologger-with-the-asyncawait-syntax.

**Comment by hynek** [comment]
JFTR it's more likely that structlog will grow native asyncio support once we drop Python 2 (aka soon™).

Since a lot can happen in our processors, we need to delegate to a thread executor ASAP and not just for printing out the event.

**Comment by hynek** [comment]
It has many releases ago. :) https://www.structlog.org/en/stable/api.html#structlog.stdlib.AsyncBoundLogger
