### ISSUE TITLE
Feature: journal output option

### ISSUE THREAD

**Issue by philips** [hynek/structlog#2]
This might be a nice thing to add- a JournalLogger class:

https://github.com/systemd/python-systemd

Cool project! I wish I used more Python so I could make use of it.

**Comment by cjw296** [comment]
I bet you do by now ;-)

**Comment by hynek** [comment]
Almost! :)  We’re in the process of upgrading to Xenial and logging is a part of that.  I hope to get around this ASAP.

**Comment by cjw296** [comment]
@hynek - glad to see you're alive, tried to say hi on irc but tumbleweed...

**Comment by hynek** [comment]
heh just came back from PyCon ZA

**Comment by paravoid** [comment]
[Daiquiri's JournalHandler code](https://github.com/jd/daiquiri/blob/080a7b9076ede4d4c5e300be13f4c9a34c271bb5/daiquiri/handlers.py#L60) is a good example of how that could be done. It's 38 lines of code, so it's not that complicated.

Essentially it boils down to just `journal.send(message, {"KEY1": "value1", "KEY2": "value2"}`, but with the quirk that it needs uppercase keys, and that there are some special well-known keys (like `PRIORITY`) that would be good to support.

**Comment by paravoid** [comment]
Also, the systemd module provides a [logging.handler JournalHandler](https://github.com/systemd/python-systemd/blob/a402d08da41413507a4ebebf18de897f7ddf1dd2/systemd/journal.py#L504) that is reasonable. So one can rely on the logging module for this.

This example is gross, but works:
```python
    logging.basicConfig(format="%(message)s", handlers=(systemd.journal.JournalHandler(),))
    structlog.configure(
        processors=[
            structlog.stdlib.add_log_level,
            lambda _, __, d: {k.upper() if k != "event" else k: v for k, v in d.items()},
            structlog.stdlib.render_to_log_kwargs,
        ],
        context_class=structlog.threadlocal.wrap_dict(dict),
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
    )

**Comment by hynek** [comment]
I wonder if we should add this to http://www.structlog.org/en/stable/logging-best-practices.html?

**Comment by hynek** [comment]
At this point I think this should be an external package. I don't care about this, it adds a dependency, and the headaches I have from standard library logging are bad enough.

I'll be happy to help anyone, who would like to tackle that.

**Comment by andrewshadura** [comment]
To be fair, it can be implemented internally, without an external dependency.

**Comment by hynek** [comment]
Right let it put me this way then: If some shows up with a good PR that doesn't introduce too much complexity, I will consider merging it. Either way, if someone cares enough, they can publish it separately so there's no risk to do work in vain.

I do not want to have it in my public todo list anymore, though.

**Comment by hynek** [comment]
Oh and one last thing: in my other projects I've started experimenting with GitHub discussions which is a bit better medium for cases like this. If y'all who care about this want to talk/coordinate you can of course do it here; I'm not locking the issue. But I could also be convinced to activate Discussions for structlog. I don't want to stop anyone from communicating; I just want to manage my blood pressure.
