### ISSUE TITLE
Get LogRecord info inside processors

### ISSUE THREAD

**Issue by fusillicode** [hynek/structlog#206]
Hi, it seems that right now there is no way to get a `LogRecord` reference inside processors.

As a result some information like the module, function and line where the log event was generated can't be leveraged and logged out.

I tried to work around this issue but the closest thing that I was able to get is the actual stack trace of the log function call by using `logger.findCaller()`.

Is there maybe something that I'm missing? 🤔

P.S: I apologize in advance if the issue is malformed or if it lacks some info. In any case do not hesitate to ask for additional info and/or corrections.

**Comment by hynek** [comment]
If I read it correctly in https://github.com/hynek/structlog/blob/55293fb36966e416029d402fd8423af13ba488f1/src/structlog/stdlib.py#L512-L532

You should have the record available as `_record`?

**Comment by fusillicode** [comment]
Hi thanks a lot for your support and sorry for the lateness of my reply :(

I see that the record is indeed available inside `ProcessorFormatter`s but it seems that "basic" function" processors doesn't have access to the `_record`.

For example, if I try to add a processor `_add_additional_info` inside my list of predefined processors it seem that I can't get the `_record`.

```
def _set_up_structlog():
    if not structlog.is_configured():
        structlog.configure(
            processors=[
                structlog.stdlib.filter_by_level,
                structlog.stdlib.add_log_level,
                structlog.processors.StackInfoRenderer(),
                structlog.processors.format_exc_info,
                structlog.processors.UnicodeDecoder(),
                structlog.processors.TimeStamper(fmt="iso"),
                _add_additional_info,
                _reorder_keys,
                structlog.processors.JSONRenderer(sort_keys=False),
            ],
            context_class=structlog.threadlocal.wrap_dict(dict),
            logger_factory=structlog.stdlib.LoggerFactory(),
            wrapper_class=structlog.stdlib.BoundLogger,
            cache_logger_on_first_use=True,
        )


def _add_additional_info(_logger, _log_method, event_dict):
    event_dict["process_name"] = multiprocessing.current_process().name
    event_dict["process_id"] = os.getpid()
    event_dict["thread_name"] = threading.current_thread().name
    event_dict["thread_ident"] = threading.get_ident()
    return event_dict
```

I'm sure that I'm missing something but sincerely I do not know what exactly. I mean I would really love to be able to "just" create a function rather than a new brand new `ProcessorFormatter` just to add the mentioned bit of info that I need :(

**Comment by hynek** [comment]
If I understand you correctly, there's a misunderstanding here: if you use structlog directly, there is no logrecord until structlog passes it off to stdlib logging at the very end. structlog doesn't create a logrecord, logging will once structlog is done with it.
