### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by cup** [hynek/structlog#211]
I see no install instruction here:

https://github.com/hynek/structlog

or here:

http://structlog.org

only here you find it:

http://structlog.org/en/stable/getting-started.html

this might seem like a small thing but I think its important to show new users
how to install the thing, right up front.

**Comment by hynek** [comment]
I agree completely, but the docs have a three step "first steps" enumeration where the second step links right to "Getting Started". I think that's good enough, but I'll try to come up with a way to link Getting Started from the README, so thank you for bringing it up.
