### ISSUE TITLE
Simpler color syntax

### ISSUE THREAD

**Issue by cup** [hynek/structlog#212]
It seems this is the simplest for color output:

~~~py
import structlog
structlog.configure(
   logger_factory = structlog.stdlib.LoggerFactory(),
   processors = [
      structlog.stdlib.add_log_level, structlog.dev.ConsoleRenderer()
   ]
)
structlog.get_logger().warn('aaaaa')
~~~

http://structlog.org/en/stable/development.html

compare with other projects that default with color:

~~~py
from logzero import logger
logger.warning('abcde')
~~~

**Comment by hynek** [comment]
This is incorrect. As http://www.structlog.org/en/stable/development.html says:

> structlog’s default configuration already uses it

It has the prerequisite of an installed colorama though so I've slightly clarified the wording.

**Comment by cup** [comment]
@hynek can you please clarify? If I use the above syntax, I get:

~~~
[warning  ] aaaaa
~~~

with "warning" in yellow. If I use this syntax:

~~~py
import structlog
structlog.get_logger().warn('aaaaa')
~~~

I get this:

~~~
2019-05-20 18:08.50 aaaaa
~~~

with no color, even with colorama installed.

**Comment by hynek** [comment]
When you say no color, do you mean that it literally doesn't look like fruit salad? Your output should have a dark timestamp and a bold/bright "aaaaa". More colors come into play when you add k/v pairs:

![image](https://user-images.githubusercontent.com/41240/58089562-5ec12200-7bc5-11e9-9696-e9ec3f6e20cd.png)

**Comment by cup** [comment]
@hynek when doing a warning, the word "warn" or "warning" should be present and
in color, perhaps yellow. This is how its done with several other packages:

~~~py
import colorlog
colorlog.warning('abcde')
~~~

~~~py
from logzero import logger
logger.warning('abcde')
~~~

~~~py
import coloredlogs, logging
logging.warning('abcde')
~~~

- https://github.com/borntyping/python-colorlog
- https://github.com/metachris/logzero
- https://github.com/xolox/python-coloredlogs

**Comment by hynek** [comment]
Log levels are a stdlib-specific feature and structlog doesn't force anyone to use the standard library which is very slow and should be avoided if possible. If not possible, the configuration is right there…

**Comment by cup** [comment]
@hynek thats a non Sequitur.

StructLog can output the word "warn" or "warning", in color, without using
stdlib. Just because other libraries might use stdlib to accomplish that doesnt
mean StructLog has to.

My previous point stands: regardless of how its implemented, when doing a
warning, the word "warn" or "warning" should be present and in color, perhaps
yellow.
