### ISSUE TITLE
Is better context manager possible?

### ISSUE THREAD

**Issue by slavashvets** [hynek/structlog#218]
Hello everyone. I'm looking for the better way how to add context values to log messages. The existing `tmp_bind` doesn't look perfect for me because it forces me to pass logger as an argument to another function.

After some experimentation, I got the following:

```python
class bind():
  def __init__(self, *args, **kwargs):
    self.kwargs = kwargs

  def __enter__(self):
    global logger
    logger = logger.bind(**self.kwargs)
  
  def __exit__(self, exc_type, exc_val, exc_tb):
    global logger
    logger = logger.unbind(*self.kwargs.keys())

def create_bucket(bucket: str):
  with bind(bucket=bucket):
    logger.info("Creating bucket")
    minio.make_bucket(bucket)

def create_buckets(buckets: list):
  with bind(action='creating'):
    for bucket in buckets:
      create_bucket(bucket)
    logger.info("Completed for all buckets")

create_buckets(['test-private'])
```
In the logs I see:
```
[info     ] Creating bucket             action=creating bucket=test-private
[info     ] Completed for all buckets   action=creating
```
Exactly what I need.
However, I don’t like to use "global" keyword. Do you know a better way?

**Comment by hynek** [comment]
I assume you're using threadlocals here? You don't need the logger variable for writing, so you should be able to just make the functiin bodies `logger.bind()` and `logger.unbind()`?

**Comment by hynek** [comment]
BTW, I know it's not exactly what you wanted, but depending on your use case #225 might be interesting to you nevertheless!

**Comment by fernandobrito** [comment]
This page is the first Google result for "structlog context manager", so I'm sharing my approach here:

```python
@contextlib.contextmanager
def bind_on_logger(**kwargs):
    structlog.threadlocal.bind_threadlocal(**kwargs)
    try:
        yield
    finally:
        structlog.threadlocal.unbind_threadlocal(*kwargs.keys())
```

And then I can just do:
```python
logger = get_logger()

logger.info("outer")

with bind_on_logger(a=1):
    logger.info("inner 1")

    with bind_on_logger(b=2):
        logger.info("inner 2")

# Also available as a decorator

@bind_on_logger(c=3)
def my_func():
    logger.info("function call")


my_func()
```

to get:

![image](https://user-images.githubusercontent.com/196840/140549753-e2b24518-3d47-4734-9fa9-249f87a7ad36.png)

**Comment by fernandobrito** [comment]
Also, something else I ended up having to do was a context manager just to clean up some bindings. My use case was that I wanted to bind a value that was provided to my function as an argument.

1) I couldn't use `bind_on_logger` above as decorator because the value was not known beforehand (it's a parameter of the wrapped function)
2) I didn't want to wrap my entire function body inside `bind_on_logger` as a context manager

So I simply did a
```python
@contextlib.contextmanager
def unbind_from_logger(*args):
    try:
        yield
    finally:
        structlog.threadlocal.unbind_threadlocal(*args)
```

And even though I bind it explicitly, I let the unbiding be handled by the decorator:

```python
@unbind_from_logger("variable")
def my_func2(value):
    structlog.threadlocal.bind_threadlocal(variable=value)
    logger.info("function 2 call")

my_func2(4)

logger.info("after function 2")
```

![image](https://user-images.githubusercontent.com/196840/140551365-bacf13a3-cba3-474f-aee1-104439b8294d.png)

**Comment by fernandobrito** [comment]
I'm back 😅

Just for fun, I actually wrote a decorator that introspects the values passed on the wrapped function call and binds it to the logger. It makes my comment above redundant.

```python
class logger_autobind_from_args:
    """
    A decorator that temporarily binds values on structlog loggers (thread local) by extracting the values
    from the wrapped function arguments.

    It accepts named arguments where the argument name is the key to be used when binding to the logger and the value
    is the name of the parameter of the wrapped function where the value is extracted from

    Example:
        @logger_autobind_from_args(name="n")
        def func(n):
            logger.info("Inside function")

        func('Joe')

    Will bind `name=Joe` on the logged line.
    """

    def __init__(self, **bind_config):
        self.bind_config = bind_config

    def __call__(self, wrapped):
        @functools.wraps(wrapped)
        def wrapper(*args, **kwargs):
            # Extracts the actual values used in the wrapped function call
            callargs = inspect.getcallargs(wrapped, *args, **kwargs)
            bind_key_pair = {bind_name: callargs[arg_name] for bind_name, arg_name in self.bind_config.items()}

            with logger_autobind(**bind_key_pair):
                return wrapped(*args, **kwargs)

        return wrapper
```

**Comment by hynek** [comment]
Hi @fernandobrito I'm glad to see how the new thread-local APIs make things like this possible. :)

It would make sense to add a version of your `logger_autobind` to structlog I think, but not a fan of the name. Bummer that `tmp_bind` is taken. :(

**Comment by hynek** [comment]
Maybe:

```python
with structlog.threadlocal.bound(x=42):
    foo()
```


? 🤔

**Comment by fernandobrito** [comment]
@hynek sounds great! I can try to open a PR this weekend. I'm too new to this project to have a good feeling on which name would make sense considering the overall context, but I can start with `.bound` in the PR and we discuss there? 😁. Also, do you think it's fine to use `@contextlib.contextmanager` to have it both as a decorator and as a context manager?

**Comment by hynek** [comment]
thinking further, the name should be `with threadlocal_bound(x=42):` for consistency.

But yeah we can discuss on a PR. contextmanager is fine, yes.

**Comment by fernandobrito** [comment]
I opened a draft PR: https://github.com/hynek/structlog/pull/371.
