### ISSUE TITLE
How can I format the order of processors in STDOUT using JSON renderer?

### ISSUE THREAD

**Issue by RoscoeTheDog** [hynek/structlog#224]
I've been reading the docs and there's a lot to absorb as a beginner. I thought the processor chain would be displayed in order of the list, but that does not seem to be the case. _See block_1_

**block_1**
```
import structlog
from structlog.stdlib import *
from structlog.processors import *
import sys
import logging

logging.basicConfig(stream=sys.stdout, format="%(message)s", level=0)

log = structlog.wrap_logger(
    logging.getLogger(__name__),
    processors=[
        filter_by_level,
        add_log_level,
        TimeStamper(fmt='iso'),
        JSONRenderer(indent=1, sort_keys=True),
    ]
)

log.warning('testing warning message')

# prints
>> {
>> "event": "testing warning message",
>> "level": "warning",
>> "timestamp": "2019-09-05T04:33:26.620082Z"
>>}

log.info('testing info message', some_dict={'somekey': 'value', 'other key': 'value2'})

# prints
>>{
>> "event": "testing info message",
>> "level": "info",
>> "some_dict": {
>>  "other key": "value2",
>>  "somekey": "value"
>> },
>> "timestamp": "2019-09-05T04:33:26.620082Z"
>>}
```

_about block_1:_
The `TimeStamp` processor is output very last in stdout, even though it is the third item in the processor chain list. I want `some_dict{}` to follow the order that corresponds to positional arguments being passed to `log.info()`. According to the docs, we can technically create our own processors to maybe resolve this issue manually, but we shouldn't have to do that when the module already provides a processor that handles it already.

_Another issue..._
I also noticed that dictionaries do not correspond to the log.info() positional arguments but other data types will. When I tested logging two different dictionaries, they actually printed in reversed order to how they were passed to the logger. _See block_2_

**block_2**
```
log.info('testing info message', 
some_dict={'somekey': 'value', 'other key': 'value2'}, 
other_dict={'key': 'value'}
)
```

_Prints:_
```
{
 "event": "testing info message",
 "level": "info",
 "other_dict": {    # 'some_dict' should be placed here instead
  "key": "value"
 },
 "some_dict": {    # 'other_dict' should be placed here instead
  "other key": "value2",
  "somekey": "value"
 },
 "timestamp": "2019-09-05T04:50:12.911365Z"    # 'timestamp' should be third JSON key after 'level'
}
```

**Comment by hynek** [comment]
You're passing `sort_keys=True` to JSONRenderer, and `o` comes before `s` which comes before `t`. Also: the third item _is_ the last processor before formatting!?


All that to say that json logs aren't made to be read by people first and you shouldn't care about the order of keys.

**Comment by RoscoeTheDog** [comment]
Thanks for your reply. When I was following along the documentation, I must have missed that very obvious arg somehow.

> Also: the third item is the last processor before formatting!?

I meant third key term from the top of the list (ie event: 1, level: 2, timestamp: 3). Sorry if I misspoke or it was a little unclear.

Now that `sort_keys=True` is removed, I see it working correctly but it also created a new problem for me. It seems that the passed terms to `log.info()` are being displayed first before the formatting of the processors.

What I am trying to achieve is something like this:
```
{
 "event": "testing info message",  # have all of our processor formatting up here
 "level": "info",
 "timestamp": "2019-09-05T09:07:23.495800Z"

 "some_dict": {  # pass relevant information to the logged event here, such as file metadata
  "somekey": "value",
  "other key": "value2"
 },
 "other_dict": {
  "key": "value"
 },
 "test1": "string",
 "test2": 10,
 "test3": true,
}
```

The reason being that I am dealing with a lot of media decoding/encoding and database handling in my program and it will be easier to see this displayed in JSON. I planned to make separate event logs or filters for handling performance, function tracing and other stuff that will most likely not be in JSON.

By no means am I an expert at logging practices yet. I read the 'best practices' and I'm still interpreting and figuring out what is the best way to approach my program. It seems there are many ways I could organize it.

But for now, getting the JSON to read as processors, then args is a good start :)

**Comment by RoscoeTheDog** [comment]
I apologize. After spending another day with the docs and reading some of the recommended setups, I figured out a configuration that works for me. Formatting on the standard logging handlers and wrapping as a processor works great. 

```
import structlog
from structlog.processors import *
import logging

# STRUCTLOG CONFIG
#
#
# basic structlog configuration with processor chain
structlog.configure(
    processors=[
        ExceptionPrettyPrinter(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
)


# FILE HANDLER
#
#
# declare a standard file handler
file_handler = logging.FileHandler('samplify.log')

# declare a custom formatter for our log file
file_formatter = structlog.stdlib.ProcessorFormatter(
    processor=structlog.processors.JSONRenderer(),
)

# set our custom formatter for the log file
file_handler.setFormatter(file_formatter)   # In theory, jsonlogger.JsonFormatter() could be used instead with custom override methods that allow us to re-order keys to how we'd like


# STREAM HANDLER
#
#
# declare our stream handler
stream_handler = logging.StreamHandler()


# declare a custom formatter for our stream
stream_formatter = structlog.stdlib.ProcessorFormatter(
    processor=structlog.dev.ConsoleRenderer(),
)

# set our custom formatter for the stream
stream_handler.setFormatter(stream_formatter)




# STANDARD LOGGER CONFIG
#
#
# get a standard logger
root_logger = logging.getLogger()

# add handlers to standard logger
root_logger.addHandler(stream_handler)
root_logger.addHandler(file_handler)


# STANDARD LOGGER LEVELS
#
#
# set global log level
root_logger.setLevel(logging.DEBUG)

# set log level for stdout/stderr stream
stream_handler.setLevel(logging.INFO)


# LOG MESSAGES WITH STRUCTLOG
#
#
# declare our logger using structlog
logger = structlog.get_logger('samplify.log')

# log something to both stdout/log-file!
logger.info('event message',
         some_dict={'somekey': 'value', 'other key': 'value2'},
         other_dict={'key': 'value'},
         test1='string',
         test2=10,
         test3=True)


# ALSO: LOG MESSAGES WITH STANDARD LOGGER
#
#
# declare our logger using logging (standard logging does not allow additional args)
logger = logging.getLogger('samplify.log')

# log something to both stdout/log-file!
logger.info('event message')  # we lose a lot of functionality using the standard logger (args & processors), but it will sent to both STDOUT/File still.
```
