### ISSUE TITLE
Adding line number and file name to logs context

### ISSUE THREAD

**Issue by viperfx** [hynek/structlog#226]
Hi there, 

I am using structlog with Django and I would like to add something globally with the config so that structlog can include the line number and file name to the logs, as context.

Is this possible?

**Comment by hynek** [comment]
Possible: definitely. You can either write a processor that walks up the stack to look for the line or you write your own version of a logger that does the same.  Check out https://github.com/hynek/structlog/blob/d85172bfbb2a002c462a6c31edd1b86c18ed496c/src/structlog/processors.py#L363-L381 and the functions it calls,  most notably https://github.com/hynek/structlog/blob/d85172bfbb2a002c462a6c31edd1b86c18ed496c/src/structlog/_frames.py#L28-L47

There may be other, more elegant ways.

**Comment by viperfx** [comment]
@hynek I created a processor to use your provided functions

```
class StackInfoRenderer(object):

    def __call__(self, logger, name, event_dict): 
        event_dict["file_name"] = _find_first_app_frame_and_name()[1]
        return event_dict 
```

However, it added the following `file_name=project.settings` to the log. Which is my project's settings file.

I wanted it to print the file name for where the log was originated.

**Comment by yiye93** [comment]
Hello author, I encountered the same problem， but i don't know how to solve it.

**Comment by hynek** [comment]
Have y'all tried adding project.settings to `additional_ignores`? That the point of that option.

**Comment by chiragjn** [comment]
I wrote a custom processor that uses structlog's already built-in `findCaller`, I am using it for lineno and module, but easy to change to filename

```
def add_line_no_and_module(logger: structlog.stdlib.BoundLogger, method_name: str, event_dict: Dict[str, Any]):
    record = event_dict.get('_record')
    if record is None:
        pathname, lineno, *_ = logger.findCaller(stack_info=False)
        try:
            filename = os.path.basename(pathname)
            module = os.path.splitext(filename)[0]
        except (TypeError, ValueError, AttributeError):
            module = pathname
    else:
        module, lineno = record.module, record.lineno
    event_dict['module'] = module
    event_dict['lineno'] = lineno
    return event_dict
```

**Comment by Charlie-iProov** [comment]
Hi, really enjoying the structlog framework. To jump on this topic in a similar vein, I am instantiating a logger like this:
```python
logging.basicConfig(level=os.getenv("LOG_LEVEL", "INFO").upper(), format="%(message)s")
structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.processors.JSONRenderer(sort_keys=True, **kwargs),
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)
```
this allows me to generate nice json logs but if I add more to the format line here:

```python
logging.basicConfig(level=os.getenv("LOG_LEVEL", "INFO").upper(), format="%(message)s - [%(filename)s:%(lineno)d]"
```
it will place the `[%(filename)s:%(lineno)d]` outside of the json formatted body. Is there a way of getting the filename and line number into this json output with each call of ```log.msg()```?
