### ISSUE TITLE
Consistently name threadlocal and contextvars helper functions

### ISSUE THREAD

**Issue by MarkusH** [hynek/structlog#238]
The threadlocal and contextvars integrations use a different naming for their functions to bind, unbind, merge and clear the context. This came up as part of #236 and e3a6213afb2844572c8890693a83e142c41b1f0b.

I'd like to propose the following function names:

- `contextvars`
  - `merge_contextvars_context`
  - `clear_contextvars_context`
  - `bind_to_contextvars_context`
  - `unbind_from_contextvars_context`
- `threadlocal`
  - `merge_threadlocal_context`
  - `clear_threadlocal_context`
  - `bind_to_threadlocal_context`
  - `unbind_from_threadlocal_context` -- doesn't exist but should probably be added

**Comment by hynek** [comment]
Hmm that seems a little bit too repetitive and wordy. 🤔

Maybe the best way forward is to just drop the `context` from merge and be done with it? Typing `bind_to_contextvars_context()` whenever you do something doesn't seem like a pragmatic API. :)

**Comment by hynek** [comment]
> * `unbind_from_threadlocal_context` -- doesn't exist but should probably be added

lol https://github.com/hynek/structlog/pull/239

**Comment by c-wilson** [comment]
While it might be late to the party, my understanding of the contextvars implementation is that it could be summarized with the suffix `global` instead of `contextvars`. 

Just a thought, I know that "global" is potentially an overloaded term and maybe the implementation detail "contextvars" description makes it clearer.

**Comment by hynek** [comment]
Yeah I'm just gonna drop all the contexts unless someone wants to stop me.

**Comment by MarkusH** [comment]
> Yeah I'm just gonna drop all the contexts unless someone wants to stop me.

Sounds good to me 👍
