### ISSUE TITLE
Use contextvars instead of thread.local to support asyncio task-local logging

### ISSUE THREAD

**Issue by n1ywb** [hynek/structlog#248]
Python 3.7 added a new contextvars module to present a unified context-local storage API for both threaded and async programs.

https://docs.python.org/3.7/library/contextvars.html

> Context managers that have state should use Context Variables instead of threading.local() to prevent their state from bleeding to other code unexpectedly, when used in concurrent code.

This seems to tie into the ongoing async logging work

**Comment by hynek** [comment]
`structlog` had support for contextvars since 20.1: http://www.structlog.org/en/stable/contextvars.html

**Comment by n1ywb** [comment]
thanks, I had missed that. closing.
