### ISSUE TITLE
building object for event key with BoundLogger

### ISSUE THREAD

**Issue by teaglebuilt** [hynek/structlog#252]
In my python library i am building an object to send to ELK. one of the ECS fields is event.  If i use the event key.

```
self.logger.bind(event={"id": 123, "type": "test"})
```

event needs to show up in kibana as

```
event.id = 123
event.type = test
```

 if i switched event to user, it would work because user is not a default parameter as event is...
how can i override this?

**Comment by hynek** [comment]
Does this help you: https://github.com/hynek/structlog/issues/35#issuecomment-591321744 ?
