### ISSUE TITLE
structlog logging same record a few times.

### ISSUE THREAD

**Issue by teaglebuilt** [hynek/structlog#255]
To start off, I am not sure if this is a problem with structlog. I am wondering if this could be an error on my behalf. Although, I am logging to elasticsearch and I am getting the same log 3 times. Originally, i thought this issue was because i was binding and logging in a loop.  After logging in a loop several different ways and the issue persisting. I decided to create my own iterator to have control over the logger sending the events to ELK...

```
class EventDistribution:

    def __init__(self, data):
        self.logger = get_logger(__name__)
        self.builtin = BuiltIn()
        self.index = 0
        self.data = data

    @property
    def selib(self):
        return self.builtin.get_library_instance("seleniumwire")

    def __iter__(self):
        return self

    def __next__(self):
        if self.index >= len(self.data):
            raise StopIteration()
        rslt = self.data[self.index]
        performance = self.selib.driver.execute_script(f"return 
        window.performance.getEntriesByName('{self.data[self.index].path}');")
        self.data[self.index].__dict__['_data']['performance'] = performance
        self.logger.bind(web=self.data[self.index].__dict__['_data'])
        self.logger.info(f"request {self.data[self.index].path} ")
        self.index += 1
        return rslt
```

```
   def expected_services_called_on_page_load(self):
        scoped_requests = self.selib.get_scoped_requests()
        requests = list()
        for i in EventDistribution(scoped_requests):
            requests.append(urlparse(i.path).path)
        assert_equal(set(requests), set(self.selib.driver.scopes))
```

So now i am controlling the iteration and sending the logs to elk with the EventDistribution class. Ive set breakpoints and watch each log go to kibana. Before I go any further, let me show you my logging setup

```
def get_logger(name):
    log = logging.getLogger(name)
    log.setLevel(logging.INFO)
    handler = ElasticHandler([os.environ['ESHOST']])
    handler.setFormatter(jsonlogger.JsonFormatter())
    log.addHandler(handler)
    logger = wrap_logger(
        log,
        processors=[
            structlog.stdlib.filter_by_level,
            add_log_level,
            structlog.stdlib.PositionalArgumentsFormatter(),
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,
            structlog.processors.UnicodeDecoder(),
            structlog.processors.TimeStamper(), 
            structlog.stdlib.render_to_log_kwargs,
            ECSProcessor()
        ],
        context_class=structlog.threadlocal.wrap_dict(dict),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True
        )
    return logger
```

As you can see the last processor is my own class where i am building the msg by modeling it to fit  [Elastic Common Schema](https://www.elastic.co/blog/introducing-the-elastic-common-schema) fields.

Im not sure if this could be relevant to the issue, but all i am doing here is mapping the event by structlogs bind method here in the iterator class....

```

self.logger.bind(web=self.data[self.index].__dict__['_data'])
self.logger.info(f"request {self.data[self.index].path} ")

```

so the web keyword in the bind method sends the msg to the processor and the processor sends it to the correct modeling class by which key is present in the extra object. 

```
class ECSProcessor:

    def __init__(self):
        self.ecs = {
            'web': Web,
            'keyword': Keyword,
            'test': TestCase,
            'suite': Suite
        }

    def __call__(self, logger, method, event_dict):
        for k, v in event_dict['extra'].items():
            try:
                event_dict['extra'] = self.ecs[k](event_dict['msg'], v)
            except KeyError:
                pass
        return event_dict
```

The main point is, I am logging over a list of request objects. In Kibana, there are multiples of the same logging event / request object and i cannot figure out how when i am binding and logging each request in the iteration....

Is there something I am missing, or is there details about structlog that I am not aware of that could cause such a problem? Or could this be an issue.

Also, If any one has any suggestions on how to target the problem, your input is appreciated.

**Comment by hynek** [comment]
Did you figure it out?
