### ISSUE TITLE
AttributeError: 'BoundLogger' object has no attribute 'msg'

### ISSUE THREAD

**Issue by sarangsbabu367** [hynek/structlog#260]
My code is simple,
```
log = structlog.get_logger()
log.msg("heloooooooooooooooo")
```
anyone have an idea ??

**Comment by hynek** [comment]
Not if you don't show us your configuration.

**Comment by sarangsbabu367** [comment]
@hynek 
![image](https://user-images.githubusercontent.com/48784283/81465006-37070780-91e4-11ea-997d-58489e3e4fa6.png)

**Comment by hynek** [comment]
Stdlib’s BoundLogger mirrors the API or `logging.Logger` and therefore doesn’t have a ‘msg’ method.  The closest is probably `info`.

**Comment by sarangsbabu367** [comment]
Sorry didnt look closely.
