### ISSUE TITLE
Logs remain colorized after output redirect

### ISSUE THREAD

**Issue by askurihin** [hynek/structlog#264]
Hi, thank you for structlog, it is cool and easy to use.

Straight to business:

1. create test.py
```python

import structlog
log = structlog.get_logger()
log.msg("greeted", whom="world", more_than_a_string=[1, 2, 3])
```

2. run it
```shell
$ python test.py > some_log_file.log
$ cat some_log_file.log

^[[2m2020-06-17 20:08.14^[[0m ^[[1mgreeted                       ^[[0m ^[[36mmore_than_a_string^[[0m=^[[35m[1, 2, 3]^[[0m ^[[36mwhom^[[0m=^[[35mworld^[[0m
```
ANSI is written to the log file.

It is not expected for me, to see escape codes in log file after using stream redirect (>).

I tried reproducing this with colorama and print, but it works correctly:

1. create test_colorama.py
```python

from colorama import Fore, init, Style
print(Fore.RED + 'some red text')
print(Style.RESET_ALL)
```

2. run it 

```shell
$ python test_colorama.py > some_other_file.log
$ cat some_other_file.log

some red text
```

## Versions
Name: structlog
Version: 20.1.0

Name: colorama
Version: 0.4.3

OS: Centos 7.4

**Comment by hynek** [comment]
Ugh, this is caused by the delayed initialization magic we had to add in 19.2. I guess we have to do the tty-detection ourselves now.

**Comment by askurihin** [comment]
In my system, I did exactly that, I changed `colors` arguement to `ConsoleRendere`r based on tty detection.

**Comment by hynek** [comment]
Yeah it doesn't even help to play with force-colors because colorama only needs the call to init on Windows. _sad trombone_

**Comment by askurihin** [comment]
Thank you for the quick fix!

Could you please clarify, I have to do tty detection manually (like in your fix) if I'm Initializing
ConsoleRenderer myself in custom config?

**Comment by hynek** [comment]
Given colorama's docs, it seems like that. They're implying that init is a nop on Linux, LMK if you understand it differently.

**Comment by askurihin** [comment]
I understood it the same way you did.
I suppose it will be a good thing to mention this in the docs, what do you think?
