### ISSUE TITLE
AttributeError when deepcopying object using structlog

### ISSUE THREAD

**Issue by stefanbschneider** [hynek/structlog#268]
I really like `structlog` and have been using it in my classes like this:

```python
class Test:
    def __init__(self, id, works=True):
        self.id = id
        self.works = works
        self.log = structlog.get_logger(id=self.id)

    def example(self):
        self.log.info('Works')
```

This way I have separate loggers for different objects to which I can bind different attributes (here `id`). And it used to work fine.

Now, I need to deepcopy my objects and it breaks:

```python
test = Test(1)
copied_test = deepcopy(test)
```

This fails with the following error: `AttributeError: 'PrintLogger' object has no attribute '__deepcopy__'`

Is there some other best practice how to use `structlog` with classes and objects? Or some way to fix the problem?

This seems related to https://github.com/hynek/structlog/issues/126 and https://github.com/hynek/structlog/issues/71.
I have `structlog 20.1.0` with Python 3.8 on Ubuntu 20.04 (on WSL on Win 10).

**Comment by hynek** [comment]
Yeah I suppose we'll have to implement an `__deepcopy__` analogously to the pickle code.

**Comment by stefanbschneider** [comment]
Any way I can help with this?

**Comment by hynek** [comment]
You could submit a PR that does it? 😇 Shouldn't be too complicated, I think.

The bigger problem will probably be to hunt down all classes that need this treatment. 🤔

**Comment by stefanbschneider** [comment]
Hm, fixing PrintLogger worked, but I still get errors: https://github.com/hynek/structlog/pull/270 Do you have any idea what the cause could be?
