### ISSUE TITLE
docs: Logging of Exceptions

### ISSUE THREAD

**Issue by guettli** [hynek/structlog#27]
Please provide a recipe in the docs how to handle logging of exceptions.

I guess this use case is wide spread and most users of structlog handle it in a custom way.

I could solve it my way, but a common recipe or even API would help other new users, too.

Thank you for this module!

**Comment by guettli** [comment]
Hi hynek,

do you handle exceptions with structlog? 

if yes: how?

if no: why not?

**Comment by hynek** [comment]
What exactly do you mean by “handle”? I render them into my log entries (JSON) and submit them to Sentry https://gist.github.com/hynek/a1f3f92d57071ebc5b91 .  Anything else?

**Comment by guettli** [comment]
Nothing else. I was just curious. Thank you for your answer.

**Comment by hynek** [comment]
You’re very welcome, feel free to open an issue if you have a concrete complaint.
