### ISSUE TITLE
setting log level and redirecting output to file

### ISSUE THREAD

**Issue by meshko** [hynek/structlog#273]
I am trying to create a pretty basic setup where logging would go to a file and I would be able to set log level.
It doesn't seem to be possible because structlog.stdlib.filter_by_level doesn't work with structlog.PrintLoggerFactory and stdlib.LoggerFactory  doesn't know how to send output to a file.  
Is there a simple way of getting this to work?

**Comment by hynek** [comment]
Currently vanilla structlog has no concept of log levels unless you use stdlib integration. It wouldn't be very hard to add but I haven't gotten around to do it.

**Comment by xtay573269555** [comment]
I have the same question, and  got it now. Thanks.
