### ISSUE TITLE
Deactivate structlog defines in external lib

### ISSUE THREAD

**Issue by delijati** [hynek/structlog#275]
Hi,

i have a problem i use an external dependency that uses structlog, unfortunately i can't get it deactivated `structlog.reset_defaults`.

1. globally defined log in a log.py of an external library
2. import that lib to have the log defined
3. call structlog.reset_defaults() to clean up _CONFIG

The steps above does not work.

Thanks

**Comment by hynek** [comment]
What exactly do you want?

Do you want structlog to stop logging? Or does your dependency configure structlog (which it shouldn't)?

**Comment by delijati** [comment]
I want structlog to stop logging

**Comment by hynek** [comment]
```python
def drop_all(*args, **kw):
    raise structlog.DropEvent

structlog.reset_defaults()
structlog.configure(processors=[drop_all])
```

Should do the trick.

**Comment by delijati** [comment]
Thanks perfect that did the trick
