### ISSUE TITLE
New release (20.2) has a backward incompatibility that's not called out

### ISSUE THREAD

**Issue by lambacck** [hynek/structlog#292]
It changes the [default wrapper](https://www.structlog.org/en/stable/changelog.html#changes) which is called out, but the default change means it loses the `.log` method that was present on the [PrintLogger](https://www.structlog.org/en/stable/api.html#structlog.PrintLogger).

**Comment by lambacck** [comment]
Actually seems it's the BoundLogger change.

**Comment by hynek** [comment]
This is the thing: no BoundLogger did change either (IIRC it used the generic logger before). The only thing that changed is the default configuration by using a different wrapper which _is_ called out. Its log levels are based on the stdlib levels and `log` has a special meaning there, so I didn't want to take it over.

What exactly would you like to happen?

**Comment by lambacck** [comment]
I'm not sure *why* it's failing but when I use `structlog.configure(wrapper_class=structlog.BoundLogger)` it works:
```
$ python
Python 3.6.12 (default, Nov 11 2020, 14:05:19)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import structlog
>>> structlog.__version__
'20.2.0'
>>> log = structlog.get_logger()
>>> log.log('message', level=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/clambacher/.virtualenvs/connect/lib/python3.6/site-packages/structlog/_config.py", line 396, in __getattr__
    return getattr(bl, name)
AttributeError: 'BoundLoggerFilteringAtNotset' object has no attribute 'log'
```
vs 
```
$ python
Python 3.6.12 (default, Nov 11 2020, 14:05:19)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import structlog
>>> structlog.__version__
'20.2.0'
>>> structlog.configure(wrapper_class=structlog.BoundLogger)
>>> log = structlog.get_logger()
>>> log.log('message', level=1)
2021-01-05 09:19.53 [log      ] message
>>>
```

**Comment by hynek** [comment]
I just told you. :) And you mentioned it in your first message too: the default config doesn't use `structlog.BoundLogger` (= warpper) anymore.

**Comment by lambacck** [comment]
Yeah, I know, but it's not listed in the breaking changes. It's listed as a no consequence change.

**Comment by lambacck** [comment]
So either it should be listed in the Backward-incompatible changes because it implies that methods disappear if you are using straight defaults, or the new default should have the same methods. I don't have a problem with the method going away. My concern is that others are going to skim the release notes and think it'll be fine and run into the same problem.

**Comment by lambacck** [comment]
I dug into it a bit and the difference that is surprising is that BoundLogger proxied to the underlying Logger and therefor had all the methods of the underlying logger. The new default provides a subset of the methods that are available in the default PrintLogger. In particular `log`, `failure`, and `err` are not defined in the `BoundLoggerFilteringAt*` classes that are generated by the new default. This consequence is not called out in the release notes as a backward incompatibility and is likely to be skimmed over, in fact I interpreted the comment about the new default as a consequence free optimization over the existing behavior.

It's probably a low risk since you have to be using default configuration and one of those "weird" methods (I was using log to programatically select level) so I'll close this.

**Comment by hynek** [comment]
Yeah hence my question what your favorite solution would be. Does it make so much sense to add it to the changelog _now_? I legit don't know. I mean that would be literally a one-line change.

**Comment by lambacck** [comment]
I think a call out in the changlog would be all that's necessary. It's really easy to fix it with a configure call. Putting it in the changelog could help someone pro-actively fix it or figure out what happened more quickly if they encounter issues.

**Comment by hynek** [comment]
Done in bf39fb4c85ed962ab4083857f1c5edd9982eaaf9 – I hope it's OK like this.

**Comment by lambacck** [comment]
That's perfect. Thanks for adding that.
