### ISSUE TITLE
Question: Is there a way to adapt the BoundLogger?

### ISSUE THREAD

**Issue by berislavlopac** [hynek/structlog#293]
Python's `logging` has a useful concept of `LoggerAdapter`, which [injects additional information](https://docs.python.org/3.9/howto/logging-cookbook.html#using-loggeradapters-to-impart-contextual-information) into the adapted logger within a specific context. Is there something similar available in structlog? I've looked through the documentation but couldn't find anything similar.

**Comment by RonnyPfannschmidt** [comment]
The bound logger in structlog is the adapter from stdlib logging perspective

**Comment by hynek** [comment]
That, and processors. Especially in combination with threadlocal data/contextvars if you want it implicitly.

Check out the updated Flask example: https://www.structlog.org/en/stable/examples.html#flask-and-thread-local-data

**Comment by berislavlopac** [comment]
Yes, I see it now. Sadly there are quite a few differences between how different loggers implement the logging protocol, but that's wider than just structlog. Thanks!
