### ISSUE TITLE
Type annotation compatibility for context_class

### ISSUE THREAD

**Issue by kkozmic** [hynek/structlog#294]
I'm just in the process or upgrading to version `20.2.0` and I've got mypy complaining about the following

```python
    context_class = structlog.threadlocal.wrap_dict(dict)

    structlog.configure(
        context_class=context_class,
        ...,
    )
```

`structlog.threadlocal.wrap_dict` return type is annotated as `Type[MutableMapping[str, Any]]`
`context_class` parameter of `structlog.configure()` is annotated as `Optional[Type[Union[Dict[str, Any], Dict[Any, Any]]]]`

So I'm getting `MutableMapping[str, Any]` where `Dict[str, Any]` is expected.
The code works just fine (it's pretty much the same as [this example from the documentation](https://www.structlog.org/en/stable/api.html#structlog.threadlocal.tmp_bind)) so I'm guessing the issue really is just overzealous type annotation?

Or is what I'm doing no longer valid/recommended (and if so what's the alternative)?

**Comment by hynek** [comment]
Yes, I'm sorry that's a bug that has been fixed. You can mute it with a `# type: ignore` for now.

That said, nowadays I would advice against using `wrap_dict` and strongly suggest using the new APIs instead. See [updated Flask](https://www.structlog.org/en/stable/examples.html#flask-and-thread-local-data) example.

**Comment by kkozmic** [comment]
> That said, nowadays I would advice against using wrap_dict and strongly suggest using the new APIs instead. See updated Flask example.

Oooh, thanks. I must have missed that.

**Comment by kkozmic** [comment]
@hynek I just want to point out that the updated Flask example you linked still has `context_class=structlog.threadlocal.wrap_dict(dict),` 🤷

**Comment by hynek** [comment]
Thanks for pointing that out, I've fixed it!
