### ISSUE TITLE
The `threadlocal.wrap_dict` doesn't play nicely with `fork`

### ISSUE THREAD

**Issue by libre-man** [hynek/structlog#296]
We encountered the following issue, of which we unfortunately couldn't really determine the root cause.

When using structlog with `cache_logger_on_first_use` set to `True`, and `context_class` set to `structlog.threadlocal.wrap_dict(dict)` it seems that loggers that already have been initialized use an old context dict after forking. The weird thing is that I can only reproduce this within docker (maybe because of thread idents?). So code like this:

```python
def make_a():
    logger = get_logger():
    return lambda: logger.info('a')

a = make_a()
a()

def make_b():
    logger = get_logger():
    return lambda: logger.info('b')

def in_child():
    logger = get_logger()
    logger.new(new='Yes')
    logger.info('hi')
    make_b()()
    a()

if fork() == 0:
    in_child()
```

Doesn't log `a` with `new=Yes` when called in the child. We can fix this by either disabling `cache_logger_on_first_use`, or when creating our own `ThreadLocal` object that wraps `structlog.threadlocal.ThreadLocal` but creates a new one on fork.

**Comment by hynek** [comment]
Hm yeah fork is nasty in _many_ ways and you would strongly urge you to delay initialization for global data to until after the fork. Your example is neither runable nor complete but I suspect that you log out something in the old process and _then_ fork which copies the finalized loggers into the new process…

Have you seen the new threadlocal APIs btw? They are much nicer and probably not susceptible to this problem. Here's an example: https://www.structlog.org/en/stable/examples.html#flask-and-thread-local-data

**Comment by libre-man** [comment]
Sorry about the example, I will fix it later today.

I can't really delay configuring my logging as I want to log some stuff before forking, or at least have it configured so that I can log in the case forking goes wrong.

I will try the new threadlocal API later today (or this weekend), but that would require large changes to our codebase as currently we use `logger.bind` in quite some places.

**Comment by hynek** [comment]
I think I'm gonna close this, since the solution is using new APIs and/or avoiding fork().

For those who end up here and wonder what's up with fork(): https://www.microsoft.com/en-us/research/uploads/prod/2019/04/fork-hotos19.pdf

**Comment by hynek** [comment]
I've also added a warning in https://github.com/hynek/structlog/commit/4137fddf99bb6b681205b73f69fea04cad9ec652
