### ISSUE TITLE
Passing information to workerthread - eg contextvars

### ISSUE THREAD

**Issue by seanv507** [hynek/structlog#297]
Hi
I initialise some global information (eg request id)  and then use threads to process parts of the request in parallel
How can I pass the context to the worker threads.

I am currently using contextvars, and the information is lost in the worker threads/processes (using joblib)

My solution would be to extract the context vars and store the context globally/as function parameter
AFAIK, I would have to therefore use _get_context
Is there a better way (ie not using private function)?

https://github.com/hynek/structlog/blob/fa120c28a4fd512d2177a868c6c72b94b8f555be/src/structlog/contextvars.py#L82
https://github.com/joblib/joblib/issues/1017

**Comment by hynek** [comment]
Currently there isn't and we're doing it the same way in our async logger:

https://github.com/hynek/structlog/blob/fa120c28a4fd512d2177a868c6c72b94b8f555be/src/structlog/stdlib.py#L467-L482
