### ISSUE TITLE
[Bug][20.2.0] log.exception not showing traceback in 20.2.0 with KeyValueRenderer and stdlib.LoggerFactory

### ISSUE THREAD

**Issue by Maartincm** [hynek/structlog#299]
Hello there.
I found an issue while trying to log an exception from an `Exception` block where the traceback is not printed. The issue is presented when `structlog` is configured with a `KeyValueRenderer` and a stdlib `LoggerFactory`

## Context

Python version: 3.6 (New virtualenv)
Structlog version: 20.2.0

Structlog configuration snippet:

```python
import structlog

structlog.configure(
    processors=[
        structlog.processors.KeyValueRenderer(),
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
)

logger = structlog.get_logger(__name__)
```

## Process

1. Configure structlog with the snippet presented above
2. Use `log.exception` in an `Exception` block
3. Run the code with the `log.exception`

Example code:

```python
import structlog

structlog.configure(
    processors=[
        structlog.processors.KeyValueRenderer(),
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
)

logger = structlog.get_logger(__name__)


def fail():
    try:
        1 / 0
    except Exception:
        logger.exception("Can't divide by zero")


if __name__ == "__main__":
    fail()
```

## Expected result

The log prints the traceback.
Example output using the above code and running `python test.py` with `structlog==20.1.0`:

```bash
$ python test.py             
event="Can't divide by zero"
Traceback (most recent call last):
  File "test.py", line 15, in fail
    1 / 0
ZeroDivisionError: division by zero
```

## Current result

The log is not printing the traceback.
Example output using the above code and running `python test.py` with `structlog==20.2.0`:

```bash
$ python test.py                
exc_info=True event="Can't divide by zero"
```

## Workaround

For now we will use the following configuration which is working as expected

```python
import structlog

structlog.configure(
    wrapper_class=structlog.BoundLogger,
    processors=[
        structlog.processors.KeyValueRenderer(),
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
)

logger = structlog.get_logger(__name__)
```

## Possible Fix

-> TODO

**Comment by hynek** [comment]
You need to add `structlog.processors.format_exc_info` to your processors to have exceptions formatted.

**Comment by Maartincm** [comment]
Since the behavior is different upgrading from 20.1.0 to 20.2.0...
Should this be an entry in the changelog?

**Comment by hynek** [comment]
I'm somewhat puzzled by the old behavior myself. The changelog calls out a change in the default logger, I just didn't anticipate every single consequence of especially since there are so many combinations. :(

**Comment by hynek** [comment]
I have added another blurb in https://github.com/hynek/structlog/commit/716970990694aec75db2ba8535cc5d838538fbb1 but it's impossible to enumerate all possible breakages, so I'll have to leave it at that.
