### ISSUE TITLE
Logging levels for an application

### ISSUE THREAD

**Issue by ayoshi** [hynek/structlog#30]
Hi.

I couldn't find a simple example of setting a logging level properly  for the whole application.
This is something which turned out to be non-trivial.

If I used wrap at the top level, the loggers for modules would still use PrintLogger, and the logger which has level defined wouldn't be picked up by submodules.
The only way I could make it work is to pass a factory to a structlog.config.

Is there a canonical/easy way out ?

**Comment by alph486** [comment]
@hynek Did this ever make it onto the official docs somewhere?

**Comment by hynek** [comment]
It’s in the FAQ for now: http://www.structlog.org/en/stable/faq.html

**Comment by joar** [comment]
I can't find the FAQ anymore.

**Comment by hynek** [comment]
The no FAQ anymore since we got good stdlib integration now so the docs moved there.

**Comment by wimglenn** [comment]
I love structlog but it could be a bit clearer/easier for users migrating a large existing app that has stdlib logging.  The relevent section of the [docs](https://structlog.readthedocs.io/en/stable/standard-library.html#stdlib-config) needs a better description of how to correctly replace `logging.basicConfig`.  If you don't do it properly you get debug logging all over the place, or your logs disappear entirely, not such a pleasant transition.

**Comment by tony** [comment]
Agreed. I'm converting from standard library logging (using `basicConfig`) and getting this:

```
  File "/Users/t/work/w/p/application/app.py", line 181, in create_app
    logger.setLevel(logging.DEBUG)
  File "/Users/t/work/w/p/.venv/lib/python2.7/site-packages/structlog/_base.py", line 191, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/Users/t/work/w/p/.venv/lib/python2.7/site-packages/structlog/_base.py", line 151, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/Users/t/work/w/p/.venv/lib/python2.7/site-packages/structlog/dev.py", line 201, in __call__
    event += self._styles.reset
TypeError: unsupported operand type(s) for +=: 'int' and 'str'"
```

```
.venv ❯ pip show structlog
Name: structlog
Version: 18.2.0
Summary: Structured Logging for Python
Home-page: https://www.structlog.org/
Author: Hynek Schlawack
Author-email: hs@ox.cx
License: MIT or Apache License, Version 2.0
Location: /Users/t/work/peergrade/peergrade.io/.venv/lib/python2.7/site-packages
Requires: six
Required-by:
```

```
.venv ❯ python -V
Python 2.7.15
```

Code:

```python
import logging
import structlog

logger = logging.getLogger(__name__)
logging.basicConfig()
logger.setLevel(logging.DEBUG)
```

**Comment by tony** [comment]
I guess I'll try to look into structlog more later, I was enticed by seeing `getLogger()` was kept, but was kind of hoping for something that'd would at least give a warning and run, or at least an error with something specific, if I was coming over from a common (I think?) standard library pattern. I'm not quite sure what I did wrong.

**Comment by hynek** [comment]
Did you try to log out a number? Your error is unrelated to stdlib integration.

**Comment by williamfzc** [comment]
also happened on python3, same as @tony 

```python
logger = structlog.getLogger(__name__)
logger.setLevel(logging.INFO)
```

It didn't work on python console or script. I got:

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python36\lib\site-packages\structlog\_base.py", line 191, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "C:\Python36\lib\site-packages\structlog\_base.py", line 151, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "C:\Python36\lib\site-packages\structlog\dev.py", line 201, in __call__
    event += self._styles.reset
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
```

and I didn't try to log out anything :(

**Comment by williamfzc** [comment]
@hynek got it, thanks!
