### ISSUE TITLE
method name sent to processors no longer correct

### ISSUE THREAD

**Issue by wimglenn** [hynek/structlog#304]
Reproducer:

```
import structlog

def process(logger, method_name, event_dict):
    print("process received method_name", method_name)
    raise structlog.DropEvent

structlog.configure(processors=[process])

log = structlog.get_logger()
log.error("the error")
log.exception("the exception")
```

output in 20.1.0:

```
process received method_name error
process received method_name exception
```

output in 20.2.0:

```
process received method_name error
process received method_name error
```

I encountered this with a processor which would inject the stdlib logging "level" into the event dict.

**Comment by wimglenn** [comment]
git bisect says bad0116427286c59e7d85a0ef16e0db663f8ea1d is the first bad commit
coincidentally, the git hash starts with "bad"  :)

**Comment by hynek** [comment]
So I have double-checked, even in the standard library, `exception` is _not_ a log level:

> Logs a message with level ERROR on the root logger. [...] Exception info is added to the logging message.

So I'm gonna say that our log level normalization is correct (and the old one was wrong)?

**Comment by wimglenn** [comment]
Hmm :-\  I can see argument for both sides - yes, is true that stdlib logs exception events with levelname ERROR.  But `method_name` should be the method name regardless? Seems less magical that way?

If structlog wants to be truly stdlib-agnostic, it shouldn't care that stdlib does this transformation.

**Comment by hynek** [comment]
Yeah I'm sorry and you've got a point, but I don't want to re-change the change. Sorry again for the annoyance! :(

**Comment by hynek** [comment]
Yeah, I'm sorry for the constant ping-pong, however there's been complaints about critical loss of information in #571 et ff. I'm open to suggestions how to make everybody happy, but it seems increasingly impossible. :(

**Comment by wimglenn** [comment]
I think the solution arrived at in 24.1.0 is good. It's actually what I would have liked originally for this issue, i.e. for "method_name" to be just as the variable name describes and not a lie. The "level" should still get the transformation, which I've now done in `pytest-structlog` v0.8 so we're all good here. 

Thanks!

**Comment by hynek** [comment]
_phew_ 😅
