### ISSUE TITLE
Switching from master to main, broke our platforms CI, all our dockers use structlog, so all were down,

### ISSUE THREAD

**Issue by creslinux** [hynek/structlog#305]
A lesson for us, and us alone, but making a note should others find their environments offline, update where you're pulling from. 
Not an issue - just hoping may be helpful for any others!

Morning )

**Comment by hynek** [comment]
I'm sorry. 😔

Out of curiosity: what exactly are you doing there? Separate integration tests? Using HEAD in prod?

**Comment by creslinux** [comment]
The following snip is from our requirements.txt  - I'll have to pick into the platforms history as to why we're grabbing structlog this way rather than pypi
```
python-json-logger
pytest-logger
python-logstash-async
git+https://github.com/hynek/structlog.git@main
```

**Comment by hynek** [comment]
That's some serious YOLO right there. 😅 While I'm flattered and try to keep main stable, please don't do this unless you have to. 😅
