### ISSUE TITLE
Save current function name for all records? 

### ISSUE THREAD

**Issue by sutyrin** [hynek/structlog#309]
Hey, thanks for great package. 

I wonder — is this possible? Probably by a plugin/filter, I suppose. Also, having 3 top stack frames would be great (with no locals). 

Yes, I've googled for this to no avail. Thanks in advance.

**Comment by hynek** [comment]
Have you seen https://www.structlog.org/en/stable/api.html#structlog.processors.StackInfoRenderer ?

**Comment by sutyrin** [comment]
@hynek thousands of thanks, overlooked that.
