### ISSUE TITLE
format_exc_info should add structured data about the exception to the event_dict

### ISSUE THREAD

**Issue by wbolster** [hynek/structlog#31]
The stdlib's `Logger` class has a `.exception()` method that is basically `.error(..., exc_info=True)`. When porting an existing application that used `logger.exception("oops something went wrong")` in many exception handlers, all this code had to be updated to `logger.error("oops...", exc_info=True)`.

Since the whole point of `structlog.stdlib.BoundLogger` is that it emulates the stdlib's `Logger` API, would you consider adding an `.exception()` method?

**Comment by wbolster** [comment]
Fwiw, the stdlib's `Logger` also logs the original exception message, regardless of the message passed to the `.exception(...)` method.

**Comment by wbolster** [comment]
Okay, it seems this is already (mostly) addressed by #22.

The stdlib's `.exception()` also includes the original exception message; I can't quickly see whether structlog's emulation does that as well?

**Comment by hynek** [comment]
Please try and file a bug if it doesn’t. (respectively transform this ticket into that in that case to make use of it :)).

**Comment by hynek** [comment]
(I’m not 100% sure what you mean so I figure it’s faster if you just test it before I start asking clarification questions and test it then to tell you)

**Comment by wbolster** [comment]
This Python file:

```python


logging.basicConfig()
logger = logging.getLogger(__name__)


try:
    raise ValueError("This is the exception message.")
except ValueError:
    logger.exception("This is the log message.")
```

shows this output:

```
ERROR:__main__:This is the log message.
Traceback (most recent call last):
  File "blah.py", line 8, in <module>
    raise ValueError("This is the exception message.")
ValueError: This is the exception message.
```

As you can see, both the log message and the exception message show up in the log. A similar setup with `structlog` loses the exception message.

**Comment by wbolster** [comment]
The `structlog` configuration is from the docs:

```python
    structlog.configure(
        processors=[
            structlog.stdlib.filter_by_level,
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,
            structlog.processors.JSONRenderer(),
        ],
        context_class=dict,
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True,
    )
```

**Comment by hynek** [comment]
So, I’ve tested it with

```python
import logging

import structlog


logging.basicConfig()

structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.JSONRenderer(),
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

logger = structlog.get_logger()

try:
    raise ValueError("This is the exception message.")
except ValueError:
    logger.exception("This is the log message.")
```

And the reformatted output I’m getting is:

```json
{
  "exception": "Traceback (most recent call last):\n  File \"t2.py\", line 22, in <module>\n    raise ValueError(\"This is the exception message.\")\nValueError: This is the exception message.",
  "event": "This is the log message."
}
```

So the error message clearly is there (the stdlib output is completely within the formatted string), but what you’re saying is that you’d like the exception data in a more structured form?

Right now, format_exc_info really just formats the traceback: https://github.com/hynek/structlog/blob/master/structlog/processors.py#L169

It’s totally thinkable to pull data out of the exception I guess?  I’m removing the milestone though because this is a nice but not too important feature (and you can implement it for yourself for now if you want to).

**Comment by wbolster** [comment]
Okay maybe I was just being blind. The original message is part of the formatted traceback, right?

**Comment by hynek** [comment]
Yes, it should.  Scroll to the right above to verify. :)  The job of format_exc_info is to emulate the output you would have gotten on the console.

**Comment by wbolster** [comment]
In that case I must've missed
it the first time in the huge json spaghetti on my screen. I'm sorry for the noise.

Hynek Schlawack <notifications@github.com> schreef op 10 januari 2015 09:40:00 CET:
>Yes, it should.  Scroll to the right above to verify. :)  The job of
>format_exc_info is to emulate the output you would have gotten on the
>console.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hynek/structlog/issues/31#issuecomment-69448676

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wbolster** [comment]
I think extracting the actual error message from a stack trace is not that useful anyway. The message will likely not be that useful without the additional info from the stack trace, so I guess the current output is fine.

Closing this issue.
