### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [hynek/structlog#319]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine src/structlog/stdlib.py and observe `passsed`, however expect to see `passed`.
- Examine src/structlog/dev.py and observe `lenght`, however expect to see `length`.
- Examine tests/test_config.py and observe `initia`, however expect to see `initial`.
- Examine docs/performance.rst and observe `flexibiliy`, however expect to see `flexibility`.
- Examine tests/test_testing.py and observe `contextmanger`, however expect to see `contextmanager`.
- Examine tests/test_stdlib.py and observe `apropriate`, however expect to see `appropriate`.
- Examine docs/thread-local.rst and observe `recomment`, however expect to see `recommend`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/structlog/pull/new/bugfix_typos

Thanks.

**Comment by hynek** [comment]
Thanks! Seems like you ran into a broken update of sphinx-toolbox – oh well.
