### ISSUE TITLE
Please publish a new release :)

### ISSUE THREAD

**Issue by wbolster** [hynek/structlog#32]
...so that I can use #22. :) Thanks!

**Comment by hynek** [comment]
The only blocker is #29 / #23 – since you seem to like the stdlib, would you mind helping out? :)

**Comment by wbolster** [comment]
See #34.

**Comment by hynek** [comment]
Enjoy https://pypi.python.org/pypi/structlog/15.0.0 , you deserved it. :)

**Comment by wbolster** [comment]
great, thanks
