### ISSUE TITLE
Logfmt formatter is missing

### ISSUE THREAD

**Issue by CarlosLVar** [hynek/structlog#322]
Hello there!

Is there a way to remove the single quotes, e.g: `level='info'`to `level=info`? I'm using loki and their logfmt  parser seems not to like it much (and I can't find how to remove them with structlog).

I could also try processing the logs before shipping them to loki, but if structlog can do that I think that's the better option.

Thanks in advance!

**Comment by hynek** [comment]
No there isn't, because it's really an accident that the repr-based formatter is so similar to logfmt!

I've thought a few times about implementing one but since I don't need it myself, I never bothered. Any chance you could feed Loki JSON?

**Comment by CarlosLVar** [comment]
Sure I can!

I was going with logfmt because they recommend it (it is what Go seems to use) and also because of consistency, since I have some other logs in logfmt.
 
I thought maybe it was trivial, and I was just unable to find it, but thanks a lot for the response! And great lib! 
It does make logging less of a chore!

**Comment by hynek** [comment]
I’ll leave this open if someone want to pick it up. Here’s the spec: https://brandur.org/logfmt
