### ISSUE TITLE
More documentation of structured log best practises (or links)

### ISSUE THREAD

**Issue by seanv507** [hynek/structlog#325]
Hi

I would really welcome more  best practises/policies/examples of big projects using structlog (or structured logging in general)
some issues I have: how to make structlog simultaneously human and computer readable
as the number of context variables goes beyond 5
eg we have a whole bunch of parameter settings, environment variables, AWS identifiers, which we want to add to context. however, this gets in the view of human readability.

I feel that there are perhaps some standard policies to address these issues.

*Human readable message*
I get that the "event" message should not contain any variables, but then these variables get lost in the full context.
one possibility I could see is adding a human readable text interpolating the event_dict values.
eg 
```
bind_contextvars(sale_id = 100)
log.info("Processed Sale", amount=100, event_human_readable = "Processed sale {sale_id} amount {amount}")
```

*consistency of context variables*
Since one separates event from state, it becomes especially important to use a consistent set of keys across a project.
[ eg so a query might be .event, .transaction_id, .stage, .sale_id ] - where sale_id is essentially a looping local variable within multiple "events"
currently I tabulate the log output and identify all the keys used.  I feel that there might be a more automatic way within structlog
 

*Nesting*
AWS json cloudwatch logs are nested, and nesting would seem to be part of the solution.  However, there is no API AFAIK to update/access context vars eg

```
bind_contextvars(run_vars={"run_id": 1234}
run_vars = unbind_contextvars("run_vars")
run_vars["VERSION"]="1.0.1"
bind_contextvars(runvars=run_vars)
```

**Comment by hynek** [comment]
Most of these things aren't really structlog-specific and I don't have the time to write a book on structured logging. ;)

I've just linked one best practice guide that i've stumbled over recently and somewhat reworked the docs section: https://www.structlog.org/en/latest/logging-best-practices.html

---

I'm not sure what you mean by updating, are you basically asking for being able to read + update the thread-local context? That seems a dangerous precedent. I think the best way would be to keep run_vars around and whenever they change, you run `bind_contextvars()` on them.

**Comment by seanv507** [comment]
👍
