### ISSUE TITLE
Public access to threadlocal._get_context()

### ISSUE THREAD

**Issue by lucatpa** [hynek/structlog#327]
Similarly to #266, I find myself needing to access the thread-local context (I need to re-estabish some bound variables after a `clean_threadlocal()`).

I tried to use `structlog.get_context()` but it's not returning the threadlocal context. If this would be accepted, I might even come up with a PR.

**Comment by hynek** [comment]
Hm you want to be toying with implementation details, that seems rather dangerous to structlog's feature envelope. It seems like this could be solved better with e.g. a processor? I can't be more concrete since I don't know your use-case, but I usually have a processor to inject certain data for each logger. Or have some kind of web framework middleware that fills out the threadlocal part.

**Comment by lucatpa** [comment]
I don't think a processor could cover for this, but I'm quite new to structlog so I'm not betting on it :)

The use case is very similar to processing requests in flask, but instead of having only one "level" of request processing, I have more than one. In particular I'm dealing with redis streams in case you are familiar with them.

Basically I have a service that process data something in a more hierarchical way, like (pseudo-code):

```py
@contextmanager
def tmp_threadlocal():
    """
    Use a temporary thread-local context.

    The thread-local context will be cleared out to the state it was previous to enter this contextmanager.
    This means all thread-local bindings done inside this contextmanager will be cleared out upon exit.
    """
    # For now there is no way to access the threadlocal context with the public API so we have to use
    # _get_context(). https://github.com/hynek/structlog/issues/327
    previous_context = structlog.threadlocal._get_context().copy()
    try:
        yield
    finally:
        structlog.threadlocal.clear_threadlocal()
        structlog.threadlocal.bind_threadlocal(**previous_context)

# This processing is not so trivial in the real use case, each level of
# iteration is done in different file/classes and sometimes more variables
# are bound to the threadlocal along the way
for stream in streams:
    with tmp_threadlocal():
        bind_threadlocal(stream_key=stream.key)
        for entry in stream:
            with tmp_threadlocal():
                bind_threadlocal(entry_id=entry.id)
                process_entry(entry) # with tmp_threadlocal() is also used inside here to add some new levels
```

I could try to memorize which variables were previously bound myself, but it would get a bit dirty.

If you have any suggestions on how to handle this use case in another way that doesn't require to manually keep track of what was already bound or the use of `_get_context()`, I'd be happy to try it out.

**Comment by hynek** [comment]
Hmm, not sure how I feel about all this, but since we do have `structlog.get_context()`, I think it stands to reason to offer `structlog.threadlocal.get_threadlocal()`.

**Comment by lucatpa** [comment]
Another option would be to just move `tmp_threadlocal()` to `structlog.threadlocal` :wink:

**Comment by hynek** [comment]
I guess that would make sense!

**Comment by jab** [comment]
Should similar be done for reading the context accumulated in `structlog.contextvars`?

**Comment by hynek** [comment]
If that functionality is useful, sure. Trying to keep them in sync. Doesn’t have to come thru the same PR/commit tho.

**Comment by lucatpa** [comment]
> I guess that would make sense!

I can create a PR if you want! Although we just found another use case for it: sending the logging context to sentry. Again, some sort of "sentry extension" could be created in structlog but I'm not sure if adding all possible use cases to structlog is going to scale very well :)

**Comment by hynek** [comment]
Yeah, we really need to add `get_threadlocal()` to mirror `get_context()`. Maybe even `get_merged_threadlocal(bl)` too, since that's the first thing people are gonna ask for next. :)

**Comment by hynek** [comment]
OK I've implemented  get_threadlocal & get_merged_threadlocal over at #331. LMK if that does what you want.

**Comment by jab** [comment]
Nice! +1 for syncing these improvements back to structlog.contextvars when possible, fwiw.

(To reduce maintenance burden from keeping the two in sync, could structlog.thread_local become a shim for structlog.contextvars at some point? Can’t contextvars do everything threadlocals can do, but also work with coroutines, etc.?)

**Comment by hynek** [comment]
Ooof I don't know what the implications would be here and would expect some subtle breakage. Fortunately, the APIs are reasonably simple so I think it's fine to keep them as is for now.

**Comment by lucatpa** [comment]
> OK I've implemented get_threadlocal & get_merged_threadlocal over at #331. LMK if that does what you want.

Awesome, thanks for the PR!

**Comment by hynek** [comment]
Final stretch with contextvars: #337

I hope we've got everything now? If anyone wants to contribute `tmp_threadlocal`, feel free to open a PR!
