### ISSUE TITLE
Traceback is missing 

### ISSUE THREAD

**Issue by vkumar-py** [hynek/structlog#329]
Hi, I am not sure what I am missing in processors but with the below configuration, the traceback is missing.
Suggest me the proper way to get it.
```
import structlog

def processor(logger, method_name, event_dict):
    args = (event_dict.get("event", ""),)
    kwargs = {"extra": event_dict}
    return args, kwargs

structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        processor    
],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

log = structlog.get_logger()

my_logger = structlog.get_logger()
try:
    a = 100
    if a != 10:
        raise ValueError("A is not 10")
except ValueError as e:
    my_logger.exception(e)

```
Output:  `A is not 10`

Expected output(With Traceback)
```
A is not 10
Traceback (most recent call last):
  File "/log_demo.py", line 27, in <module>
    raise ValueError("A is not 10")
ValueError: A is not 10
```

**Comment by hynek** [comment]
The traceback is part of the `event_dict` under the key `exception`.

**Comment by vkumar-py** [comment]
This is the first time that I am using structlog, would you like to tell me where exactly I should change to get the expected behavior.

**Comment by hynek** [comment]
That depends what you want to achieve?

First sorry, I forgot to mention your first problem: you're passing `e` as the event name to `my_logger.exception`. That means the exception gets treated like a string.

Once you write something like `my_logger.exception("fail!")`, you get the formatted exception as part of the `event_dict`.

You're passing that as `extra` to `logging`, but you'll have to use those key/values in that formatter: https://www.structlog.org/en/stable/standard-library.html#rendering-using-logging-based-formatters The other two possibilities follow, but I find [the last one](https://www.structlog.org/en/stable/standard-library.html#rendering-within-structlog) the simplest.

**Comment by hynek** [comment]
(I would suggest you put a `import pdb; pdb.set_trace()` into your `processor` and then watch how the control flows. That might be easier than reading/understanding the docs)

**Comment by vkumar-py** [comment]
I have tried to debug, what I observe are:
1. In `_proxy_to_logger(structlog/_base.py)` function, the method name is coming as an `error`, so it's going to `error` function of `logging/__init__py` and so `exec_info=None` is coming to `_log` func.
2. If the method name come as  an 'exception`  then it would definitely go the `exception` function of logging/__init__py and set `exec_info=True` happen and finally we would have get the traceback.

**Comment by hynek** [comment]
As you can see here:

https://github.com/hynek/structlog/blob/855268212d72aa7a75fe952b1fe176089ea93a9e/src/structlog/stdlib.py#L171-L180

structlog’s `exception` sets `exc_info=True` if it’s not set already.

Your problem is that you don’t use a formatter that that looks at – in this case – `extra`. Try using the configuration from https://www.structlog.org/en/stable/standard-library.html#rendering-within-structlog which will pass formatted strings to stdlib to get a feeling for it.

If you want to leave formatting to `logging`, you have to use/write a `logging` formatter that cares about `extra`. structlog is not involved in that part.

**Comment by vkumar-py** [comment]
You meant  formatter is `structlog.processors.JSONRenderer()`. 
```
configure(
        processors=[
            structlog.stdlib.filter_by_level,
            structlog.stdlib.add_logger_name,
            structlog.stdlib.add_log_level,
            structlog.processors.StackInfoRenderer(),
            structlog.stdlib.PositionalArgumentsFormatter(),
            structlog.processors.TimeStamper(fmt="iso"),
            structlog.processors.format_exc_info,
            structlog.processors.UnicodeDecoder(),
            processor,
            structlog.processors.JSONRenderer()

        ],
        context_class=dict,
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True,
    )
```
Output:
```
[["ValueError('A is not 10')"], {"extra": {"event": "ValueError('A is not 10')", "logger": "__main__", "level": "error", "timestamp": "2021-07-09T13:23:44.718030Z", "exception": "Traceback (most recent call last):\n  File \"<path>/run.py\", line 46, in <module>\n    raise ValueError(\"A is not 10\")\nValueError: A is not 10"}}]
```
It's coming like a list.

**Comment by hynek** [comment]
You have to remove your processor

**Comment by vkumar-py** [comment]
Yeah, after removing my processor, it's coming as JSON.

**Comment by hynek** [comment]
I have added some warnings to stdlib docs and put the simplest case to the top, so people try it first: https://github.com/hynek/structlog/commit/01f48d85d13fa4cd72c248f2662fe94cae31b288
