### ISSUE TITLE
best way to integrate with graylog/gelf

### ISSUE THREAD

**Issue by wbolster** [hynek/structlog#33]
What's the best way to use structlog with GELF (graylog2/logstash)?  It's mentioned in the docs at http://www.structlog.org/en/0.4.0/logging-best-practices.html#graylog2 but doesn't include any futher info. :(

https://www.graylog2.org/resources/gelf/specification

**Comment by hynek** [comment]
I think the easiest/fastest way is to use an existing stdlib `logging`-based GELF-logger and wrap that using structlog.  Your other interactions indicate that you use logging anyway, so it seems a good match.  A django-based example can be found here: http://www.caktusgroup.com/blog/2013/09/18/central-logging-django-graylog2-and-graypy/

**Comment by wbolster** [comment]
Yeah, hooking structlog up to https://github.com/severb/graypy through the stdblib handler is what I experimented with, but it's not really making me happy.

I am not really bound to the stdlib's `logging` module, and structlog's way of structured log messages seem to match the GELF messages much better.

This setup:

```python
logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s %(msg)s')

logging.getLogger().addHandler(graypy.GELFHandler('localhost', 12201))

structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.JSONRenderer(),
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

logger.info("foo", bar='baz')
```

...results in this dict to be sent out over UDP via `graypy` (I've added a `pprint.pprint()` inside graypy's code for this debug output):

```python
{'_function': 'consumer',
 '_pid': 36404,
 '_process_name': 'MainProcess',
 '_thread_name': 'MainThread',
 'facility': 'the.module.name',
 'file': '/path/to/file.py',
 'full_message': '{"bar": "baz", "event": "foo"}',
 'host': 'my-hostname',
 'level': 6,
 'line': 172,
 'short_message': '{"bar": "baz", "event": "foo"}',
 'timestamp': 1421084698.418767,
 'version': '1.0'}
```

As you can see the `short_message` and `full_message` fields are strings (as they are supposed to), but they contain serialised JSON. As I understand it (but I'm new to this stuff), this would be the correct message to be sent out:

```python
{'_bar': 'baz',
 '_function': 'consumer',
 '_pid': 36404,
 '_process_name': 'MainProcess',
 '_thread_name': 'MainThread',
 'facility': 'the.module.name',
 'file': '/path/to/file.py',
 'full_message': 'foo',
 'host': 'my-hostname',
 'level': 6,
 'line': 172,
 'short_message': 'foo',
 'timestamp': 1421084698.418767,
 'version': '1.0'}
```

**Comment by hynek** [comment]
I sympathize and I agree that GELF would be a perfect match for structlog.  You’d have to write it yourself though, if I’m not mistaken, `logger_factory=structlog.stdlib.LoggerFactory(),` is where the magic would have to happen.  If you can use graypy it should even be fairly easy. :)

**Comment by wbolster** [comment]
@hynek Would it make sense to add a GELF formatter and transport to structlog itself?

**Comment by hynek** [comment]
I’m not entirely clear on the scope of structlog but I think third-party integrations beyond twisted and stdlib should stay outside, alone because they may require a quicker release schedule up upstream changes something.  I’m currently planning to write a sentry/raven client and if I’ll get around to it, it’s gonna be separated too.

**Comment by wbolster** [comment]
A quick and apparently correctly working solution is to use this processor as the last one in the chain, e.g. replacing the `JSONRenderer`:

```python
def graypy_structlog_processor(logger, method_name, event_dict):
    args = (event_dict.get('event', ''),)
    kwargs = {'extra': event_dict}
    return args, kwargs
```

When `structlog` is configured to use the stdlib's `logging` module (exactly as in the docs), and the `logging` module has this handler in place for the root logger:

```python
logging.getLogger().addHandler(graypy.GELFHandler('localhost', 12201))
```

...then this results in properly formatted GELF records to be emitted when making log calls like these:

```python
logger.info("This is a message")
logger.info(foo='bar')
try:
    {}['invalid-key']
except KeyError:
    logger.error(
        "foo1",
        bar='baz',
        another_field='some value',
        exc_info=True)
```

The server side receiving the messages could be logstash, e.g. started with this configuration to print debug output:

```terminal
$ cat logstash.conf
input {
  gelf {
    strip_leading_underscore => false
  }
}
output {
  stdout {
    # codec => json
    codec => rubydebug
  }
}

$ logstash -f logstash.conf
```

Feedback highly appreciated. :)

**Comment by hynek** [comment]
What kind of feedback? Seems to me like you made it work? :)  And yep, you don’t want to pass a formatted JSON if you need the structure in graylog. :)

**Comment by wbolster** [comment]
Yeah, it seems to work, but i was just wondering whether this could be more elegant, e.g. live in a better place, not as a processor hooked up to stdlib `logging`, or something else.

The problem with the solution I outlined above is that I can also have a console logger (`StreamHandler` from `logging` on `stderr`), but that will only print the messages (the `event` field from the `event_dict` used by `structlog`) to the console, and none of the structured fields.

**Comment by hynek** [comment]
The most elegant way would be to write an own logger that speaks directly to graylog instead of sending it through stdlib logging first.

**Comment by wbolster** [comment]
Thanks @hynek. Does structlog have any way (maybe I'm missing something) to route existing code using the stdlib `logging` library into structlog? E.g. by having a `StructlogHandler` that can be added to the `logging` module's root logger `logging.getLogger()`?

**Comment by hynek** [comment]
You mean something like #9  ? :-/ I wrote something similar for Twisted but not for stdlib yet.

**Comment by wbolster** [comment]
Closing this issue since the above example code can be used, but since #40 went in I think there's a better way (well, with logstash at least).
