### ISSUE TITLE
(Documentation) Flask logging link rot

### ISSUE THREAD

**Issue by blthayer** [hynek/structlog#336]
Just wanted to note that in [Configuration/Where to Configure](https://www.structlog.org/en/stable/configuration.html#where-to-configure) the Flask [Logging](https://flask.palletsprojects.com/en/master/logging/) link is broken. I believe the correct link is now:

https://flask.palletsprojects.com/en/2.0.x/logging/

**Comment by blthayer** [comment]
While I've got a documentation ticket open I just noticed the copyright is still listed as 2013 😄 

![image](https://user-images.githubusercontent.com/14652512/125866316-2b079c74-f163-4e81-9610-3ac8aefbac7a.png)

**Comment by blthayer** [comment]
Flask link in [this section](https://www.structlog.org/en/stable/thread-local.html#thread-local-contexts) of the structlog docs is also now broken. Here's a working link:

https://flask.palletsprojects.com/en/2.0.x/design/#thread-locals

**Comment by hynek** [comment]
Thanks, I've fixed the links in 1f76a041dbeeb4e23a5128c9465a96a0ef789267!

As for 2013: so far nobody has presented me any legal rational for the annual tradition of adding the current year. As far as I understand copyright law, [the year of the first release is fine](https://www.copyrightlaws.com/copyright-symbol-notice-year/).
