### ISSUE TITLE
Very confused by https://www.structlog.org/en/stable/examples.html

### ISSUE THREAD

**Issue by kaihendry** [hynek/structlog#340]
I grabbed the [first example](https://www.structlog.org/en/stable/examples.html) and tried to minimise it like so:

```
import datetime
import logging
import sys
from structlog import wrap_logger
from structlog.processors import JSONRenderer
from structlog.stdlib import filter_by_level

logging.basicConfig(stream=sys.stdout, format="%(message)s")

log = wrap_logger(
    logging.getLogger(__name__),
    processors=[
        filter_by_level,
        JSONRenderer(indent=1, sort_keys=True)
    ]
)
log.warning("something.not_filtered", id="fob")
```

The output is surprisingly to me:

```
{
 "event": "something.not_filtered",
 "id": "fob"
}
```

I was [expecting something like](https://play.golang.org/p/pRWXvyuE1GJ):

`{"fields":{"id":"foo"},"level":"warn","timestamp":"2009-11-10T23:00:00Z","message":"something.not_filtered"}
`
i.e. level was missing, message was missing and so was a formatted time stamp!

Can you please tell me where I've gone wrong?

**Comment by hynek** [comment]
`structlog` doesn't add anything, unless you tell it to. The way to do that are processors. You've configured it to filter by level and format it as JSON.

If you want timestamps, you'd add <https://www.structlog.org/en/stable/api.html#structlog.processors.TimeStamper>. If you want the log level, you'd go for <https://www.structlog.org/en/stable/api.html#structlog.processors.add_log_level>.

`structlog`'s default configuration does all of that as demonstrated in <https://www.structlog.org/en/stable/getting-started.html>. By stripping down the configuration, you've disabled all of it.

**Comment by hynek** [comment]
I should add that the first example probably shouldn't be the first one. Its main purpose is to demonstrate `wrap_logger` (that isn't used by most people; you'd usually go via configuration + `structlog.get_logger()`) and how easy it is to write your own processors. I will re-arrange them a bit.

**Comment by hynek** [comment]
I don’t believe there’s anything left doing here. The reordering happened in c5fe2e15d10f42939016945faaf28cd7275a89a5.
