### ISSUE TITLE
No way of configuring non-level color styles?

### ISSUE THREAD

**Issue by Ran4** [hynek/structlog#341]
I have a few different applications running at the same time, and I want some of them to use a different "theme" when logging: so I want to change the colors of the timestamp, logger name and the kv_key/kv_value.

This works:

```python
import colorama

console_renderer = ConsoleRenderer()
console_renderer._styles.kv_key = colorama.Fore.RED
console_renderer._styles.kv_value = colorama.Fore.BLUE
processors.extend([
    structlog.stdlib.add_log_level,
    structlog.stdlib.add_logger_name,
    structlog.processors.TimeStamper(fmt="%y%m%d %H:%M.%S"),
    console_renderer,
])
```

but it's not documented and obviously not part of the stable API.

It'd be great if setting these colors was officially supported :)

**Comment by hynek** [comment]
Yuck, it's weird that we only allow to customize levels.

If you want a solution that will most likely keep working, subclass https://github.com/hynek/structlog/blob/c5fe2e15d10f42939016945faaf28cd7275a89a5/src/structlog/dev.py#L90-L105  override what you need, and assign it to `console_renderer._styles` for now.

**Comment by parthvnp** [comment]
I would be happy to work on this issue, if help is still needed!

**Comment by hynek** [comment]
Please everyone interested, look/comment at/on #577.

**Comment by andrei-korshikov** [comment]
A bit off-topic, but still related. Very minor issue:

https://github.com/hynek/structlog/blob/768931a79f2ae08e7a42778289eec2e1b94f8c27/src/structlog/dev.py#L761-L763

@hynek I think you've pressed Enter in the wrong place in 2a6b4c051fd78fe1e2082ac0443447132143730d.

**Comment by hynek** [comment]
> [@hynek](https://github.com/hynek) I think you've pressed Enter in the wrong place in [2a6b4c0](https://github.com/hynek/structlog/commit/2a6b4c051fd78fe1e2082ac0443447132143730d).

indeed, thank you!
