### ISSUE TITLE
Is there a way ensure a handler is added only once?

### ISSUE THREAD

**Issue by jltu** [hynek/structlog#343]
Hi there,

Is there a way to check if a handler has been added in yet, and if it has not then add a new handler to a logger?
Essentially I want to do this (refer to code below), but by using structlog.  

```
if not len(logger.handlers):
    logger.addHandler(fileHandler)
    logger.addHandler(consoleHandler)
```

I tried doing something like this: 
```
    logger = structlog.get_logger(logfile)
         if not len(logger.handlers):
```

But structlog does not have a logger.handlers equivalent, and if I don't do something like this to check if a handler has been added once, then my code is called multiple times.

Also, I am using Python 2.7

Cheers,
Jon

**Comment by hynek** [comment]
What do you mean by "handler" in the context of structlog? A processor? You can use https://www.structlog.org/en/20.1.0/api.html#structlog.get_config to get the current configuration as a whole and then inspect the dict.

**Comment by jltu** [comment]
So what I am trying to do is that I have multiple different python scripts i.e., script1.py, script2.py and script3.py and I want script 1.py and script2.py to both log to the same logfile, let's say logfile1.log, and script3.py to log to a different logfile in logfile2.log. When I I run a main script to call all those 3 scripts, the logs from script1.py and script2.py appear in logfile1.log but also in logfile2.log as well, and the logs from script3.py also appear in both logs. 

So is there way in structlog to make these scripts log to the appropriate logfiles? This can be done with the regular python logging library with the use of the handlers to check.

Here is my config, it is inside a setup_logging script where this config is in a function that is called by each of the logs to be setup in the scripts and then returned as a logger to the scripts to be used.

```
def init(logfile, loglevel="INFO", max_bytes=262144, backup=4, log_console=False):
        
        structlog.configure(
            processors=[
                structlog.stdlib.filter_by_level,
                structlog.stdlib.add_logger_name,
                structlog.stdlib.add_log_level,
                structlog.stdlib.PositionalArgumentsFormatter(),
                structlog.processors.TimeStamper(fmt="iso"),
                structlog.processors.StackInfoRenderer(),
                structlog.processors.format_exc_info,
                structlog.processors.UnicodeEncoder(),
                structlog.processors.JSONRenderer()
            ],
            context_class=dict,
            logger_factory=structlog.stdlib.LoggerFactory(),
            wrapper_class=structlog.stdlib.BoundLogger,
            cache_logger_on_first_use=True,
        )
        
        logger = structlog.get_logger(logfile)
        log_level_num = getattr(logging, loglevel.upper(), None)
        logger.setLevel(log_level_num)
        file_handler = None
        file_handler = logging.handlers.RotatingFileHandler(
            /document + logfile + '.log', maxBytes=max_bytes, backupCount=backup)
        logger.addHandler(file_handler)
        
        return logger
```

**Comment by hynek** [comment]
Since you're using stdlib `logging` for output, you're gonna have to solve it within `stdlib` logging. I don't think that should be hard to achieve, since structlog will duly pass the logger name through.
