### ISSUE TITLE
Context can't be converted to dict

### ISSUE THREAD

**Issue by QuantumDamage** [hynek/structlog#347]
Hi. Thanks for nice piece of software! I'm having small issue, so maybe it will be useful to post it here. 
It seems that I need to convert context into dict for further processing and it doesn't work as I expected.

`dict(structlog.get_context(logger))` gives me TypeError:
TypeError: 'WrappedDict-f1110033-d097-4779-af84-571bee1252f3' object is not subscriptable

But using private `structlog.get_context(logger)._dict` gives nice dict as expected.

Am I missing something or is it bug?

**Comment by hynek** [comment]
Sorry wrong issue. The get_* methods are part of the current release though.
