### ISSUE TITLE
how to get non stdlib async logger 

### ISSUE THREAD

**Issue by bluebrown** [hynek/structlog#354]
Hi, I am trying to understand how to configure this properly.  I was combining this with stdlib before, but I have switched my config now according to the example about [performance](https://www.structlog.org/en/stable/performance.html).  I was wondering how to create an async logger like the `structlog.stdlib.AsyncBoundLogger` with this setup. Because now it's using `make_filtering_bound_logger` which doesn't seem to have an async equivalent.

```python
import logging
import structlog
import orjson

structlog.configure(
    cache_logger_on_first_use=True,
    wrapper_class=structlog.make_filtering_bound_logger(logging.INFO),
    processors=[
        structlog.threadlocal.merge_threadlocal_context,
        structlog.processors.add_log_level,
        structlog.processors.format_exc_info,
        structlog.processors.TimeStamper(fmt="iso", utc=False),
        structlog.processors.JSONRenderer(serializer=orjson.dumps),
    ],
    logger_factory=structlog.BytesLoggerFactory(),
)
```

**Comment by hynek** [comment]
@bluebrown would #457 suit your needs?

**Comment by gjeusel** [comment]
Daaamn, I personally love it.
Can't wait for the next release.
