### ISSUE TITLE
BoundLogger for stdlib wrapper lacks .log() method

### ISSUE THREAD

**Issue by wbolster** [hynek/structlog#36]
The summary says it all.

**Comment by hynek** [comment]
PR? :innocent:

**Comment by wbolster** [comment]
Had a quick look, but doesn't look like there's a test where I can add just one line? Signature is `.log(level, event, *args, **kwargs)`, which is different from the other proxied methods because of the `level` arg.

**Comment by hynek** [comment]
yeah it’s a special case

**Comment by hynek** [comment]
(fyi, I’m on it)

**Comment by wbolster** [comment]
great. i tried and quickly gave up ;)

afaiu the processing chain needs to be called since the parent class can't be used as-is, and the `filter_by_level` processor also broke because the method name is `log`, which is not a log level...

**Comment by hynek** [comment]
I believe #42 should fix that, opinions?

**Comment by wbolster** [comment]
Yes, opinions, written down in #42. ;)
