### ISSUE TITLE
why spaces after the level [info      ] 

### ISSUE THREAD

**Issue by raphaelauv** [hynek/structlog#362]
Probably a newbie question

why so many spaces after the level ?

even in the documentation https://www.structlog.org/en/stable/why.html#easier-logging

is that something that I can remove ?

Thank you

**Comment by hynek** [comment]
It’s to keep the beginning of the log entries aligned and thus easier to read. The padding should be exactly the length of the longest possible log level which I’m guessing is exception. It’s possible tho that nowadays it’s aliased to error and could be shortened a bit.

**Comment by raphaelauv** [comment]
aaaaa it make sense ! thanks I can close the issue
