### ISSUE TITLE
Use another augmented assignment statement

### ISSUE THREAD

**Issue by elfring** [hynek/structlog#366]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/src/structlog/stdlib.py b/src/structlog/stdlib.py
index 51751d8..d6baaa8 100644
--- a/src/structlog/stdlib.py
+++ b/src/structlog/stdlib.py
@@ -592,7 +592,7 @@ class PositionalArgumentsFormatter:
             if len(args) == 1 and isinstance(args[0], dict) and args[0]:
                 args = args[0]
 
-            event_dict["event"] = event_dict["event"] % args
+            event_dict["event"] %= args
 
         if self.remove_positional_args and args is not None:
             del event_dict["positional_args"]
```

**Comment by hynek** [comment]
Hah that's cute, thanks!

**Comment by elfring** [comment]
Thanks for [your integration of a tiny source code adjustment](https://github.com/hynek/structlog/commit/2341bedb8393f9dc10d12506a0a428f3b2d256f4 "PositionalArgumentsFormatter: use augmented assignment").
