### ISSUE TITLE
Is there a simple way to set global log level?

### ISSUE THREAD

**Issue by Gwill** [hynek/structlog#375]
Is there a simple way to set global log level?

**Comment by hynek** [comment]
Depends on you needs and configuration.

- If you use stdlib integration: it's the same config using `logging.basicConfig()` etc.
- If you use structlog's internal loggers, there is only _one_ log level and that is set by constructing an appropriate filtering bound logger using [structlog.make_filtering_bound_logger](https://structlog.org/en/latest/api.html#structlog.make_filtering_bound_logger) and use it to configure `wrapper_class`. Something like `structlog.configure(wrapper_class=structlog.make_filtering_bound_logger(logging.INFO))`.
