### ISSUE TITLE
Narrow return types of `BindableLogger.{bind,unbind,try_unbind,new}` in `FilteringBoundLogger`

### ISSUE THREAD

**Issue by aucampia** [hynek/structlog#390]
I usually use structlog like this:

```python
import structlog
from structlog.types import FilteringBoundLogger

logger: FilteringBoundLogger = structlog.get_logger(__name__)

log = cast(FilteringBoundLogger, logger.bind(something="value")
log.info("event description")
```

It would be nice to not have to cast the result of bind, one option for this would be to just override `{bind,unbind,try_unbind,new}` in `FilteringBoundLogger` to return `FilteringBoundLogger`.

I would be happy to make a PR for this, but this is somewhat of a commitment that I think would be best to discuss before a change is made, so please let me know if you are open to this. I started some work on it [here](https://github.com/hynek/structlog/compare/main...aucampia:iwana-20220103T0035-narrow_return_type), to show the concept.

**Comment by hynek** [comment]
Is it possible to override the methods and still fulfill BindableLogger? 🤔

**Comment by aucampia** [comment]
> Is it possible to override the methods and still fulfill BindableLogger? thinking

As long as the methods are compatible, if I make them incompatible it becomes a typing error, for examplke:

```console
$ git diff
diff --git a/src/structlog/types.py b/src/structlog/types.py
index 209c059..345834b 100644
--- a/src/structlog/types.py
+++ b/src/structlog/types.py
@@ -130,7 +130,7 @@ class FilteringBoundLogger(BindableLogger, Protocol):
     .. versionadded:: 20.2.0
     """
 
-    def bind(self, **new_values: Any) -> "FilteringBoundLogger":
+    def bind(self, **new_values: Any) -> str:
         """
         TODO
 
diff --git a/tox.ini b/tox.ini
index edf1686..644dd7a 100644
--- a/tox.ini
+++ b/tox.ini
@@ -48,7 +48,7 @@ deps =
     mypy
     rich
     twisted
-commands = mypy src typing_examples.py
+commands = mypy --show-error-context --show-error-codes src typing_examples.py
 
 
 [testenv:cog]
$ tox -e mypy
mypy inst-nodeps: /home/iwana/sw/d/github.com/iafork/structlog/.tox/.tmp/package/1/structlog-22.1.0.dev0.tar.gz
mypy installed: attrs==21.4.0,Automat==20.2.0,colorama==0.4.4,commonmark==0.9.1,constantly==15.1.0,coverage==6.2,freezegun==1.1.0,hyperlink==21.0.0,idna==3.3,incremental==21.3.0,iniconfig==1.1.1,mypy==0.930,mypy-extensions==0.4.3,packaging==21.3,pluggy==1.0.0,pretend==1.0.9,py==1.11.0,Pygments==2.11.1,pyparsing==3.0.6,pytest==6.2.5,pytest-asyncio==0.16.0,python-dateutil==2.8.2,rich==10.16.2,simplejson==3.17.6,six==1.16.0,structlog @ file:///home/iwana/sw/d/github.com/iafork/structlog/.tox/.tmp/package/1/structlog-22.1.0.dev0.tar.gz,toml==0.10.2,tomli==2.0.0,Twisted==21.7.0,typing_extensions==4.0.1,zope.interface==5.4.0
mypy run-test-pre: PYTHONHASHSEED='0'
mypy run-test: commands[0] | mypy --show-error-context --show-error-codes src typing_examples.py
src/structlog/types.py: note: In member "bind" of class "FilteringBoundLogger":
src/structlog/types.py:133: error: Return type "str" of "bind" incompatible with return type "BindableLogger" in supertype "BindableLogger"  [override]
typing_examples.py:287: error: "str" has no attribute "info"  [attr-defined]
typing_examples.py:288: error: "str" has no attribute "unbind"  [attr-defined]
Found 3 errors in 2 files (checked 19 source files)
ERROR: InvocationError for command /home/iwana/sw/d/github.com/iafork/structlog/.tox/mypy/bin/mypy --show-error-context --show-error-codes src typing_examples.py (exited with code 1)
__________________________________________________________________________________ summary __________________________________________________________________________________
ERROR:   mypy: commands failed

```

**Comment by hynek** [comment]
In that case, I don't se a reason to not do it?

**Comment by aucampia** [comment]
> In that case, I don't se a reason to not do it?

The only caveat is that with that it would invalidate any implementations of `FilteringBoundLogger` that return `BoundLogger` that do not also implement `FilteringBoundLogger` for `{bind,unbind,try_unbind,new}`.

I don't think it is a very big concern though, and if later on there is a desire to make variants of `{bind,unbind,try_unbind,new}` that return `BoundLogger` (say if there is a desire to make the level also bindable) this may still be possible by using @overload and changing the return type if a specific arg/kwarg value is provided (e.g. overload that if level=... is supplied the return value is only `BoundLogger` and not `FilteringBoundLogger`).

**Comment by aucampia** [comment]
I will try publish PR tonight
