### ISSUE TITLE
How to bind keys that are not valid Python identifier?

### ISSUE THREAD

**Issue by nymous** [hynek/structlog#393]
Hello!

Thank you for building Structlog!

I was wondering how to bind a key to a context, when said key isn't a valid Python identifier.
For example Datadog looks for a `dd.trace_id` key in the JSON log entry (exactly this key, not a `trace_id` key nested in a `dd` object), however I cannot do `log.bind(dd.trace_id="abc123")`.

Adding such keys is still possible in a processor, where we can manipulate directly the event dict:
```py
def tracer_injection(_, __, event_dict: EventDict) -> EventDict:
    # get correlation ids from current tracer context
    span = tracer.current_span()
    trace_id, span_id = (span.trace_id, span.span_id) if span else (None, None)

    # add ids to structlog event dictionary
    event_dict["dd.trace_id"] = str(trace_id or 0)
    event_dict["dd.span_id"] = str(span_id or 0)

    return event_dict
```

Do you have any insight on such needs? Should I work around the issue by binding my context with legal names, then rename those in a custom processor?

Thanks!

**Comment by hynek** [comment]
It's easier than you think :)

```
 >>> structlog.get_context(structlog.get_logger().bind(**{"dd.trace_id": "abc123"}))
{'dd.trace_id': 'abc123'}
```

**Comment by nymous** [comment]
Ooooh, that works... Well, you learn something every day :sweat_smile: 
Thank you!
