### ISSUE TITLE
how to remove color codes getting logged in file while still be able to show rich format in console

### ISSUE THREAD

**Issue by sukeshlaghate** [hynek/structlog#394]
First of all thank you for wonderful library.
I am using structlog with python logging using following configuration. I have rich package installed

```
import logging
import logging.config
import structlog
from typing import  List
from structlog.processors import CallsiteParameter
from structlog.dev import rich_traceback

# Time stamp in our logger
timestamper = structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M:%S")

shared_processors: List[structlog.types.Processor] = [
    structlog.stdlib.add_log_level,
    structlog.stdlib.ExtraAdder(),
    structlog.processors.CallsiteParameterAdder(
        parameters=[
            CallsiteParameter.FILENAME,
            CallsiteParameter.FUNC_NAME,
            CallsiteParameter.LINENO,
        ]
    ),
    timestamper,
]

log_file_name: str = 'logging.log'

logger_name: str = 'structlog'

 logging.config.dictConfig(
        {
            "version": 1,
            "disable_existing_loggers": False,
            "formatters": {
                "plain": {
                    "()": structlog.stdlib.ProcessorFormatter,
                    "processor": structlog.processors.JSONRenderer(sort_keys=True),
                    "foreign_pre_chain": shared_processors,
                },
                "colored": {
                    "()": structlog.stdlib.ProcessorFormatter,
                    "processor": structlog.dev.ConsoleRenderer(colors=True, exception_formatter=rich_traceback),
                    "foreign_pre_chain": shared_processors,
                },
            },
            "handlers": {
                "default": {
                    "level": log_level,
                    "class": "logging.StreamHandler",
                    "formatter": "colored",
                },
                "file": {
                    "level": log_level,
                    "class": "logging.handlers.WatchedFileHandler",
                    "filename": log_file_name,
                    "formatter": "plain",
                },
            },
            "loggers": {
                "": {
                    "handlers": ["default", "file"],
                    "level": "INFO",
                    "propagate": True,
                },
            },
        }
    )
    logger = structlog.get_logger(logger_name)
```
when I use this with the show_off.py it correctly displays beautiful exceptions, however the logging.log file  also registers the ascii color codes.  like so
`{"event": "\u001b[2m2022-01-17 13:12.00\u001b[0m [\u001b[32m\u001b[1minfo     \u001b[0m] \u001b[1mall better now!               \u001b[0m \nStack (most recent call last):\n  File \"D:\\sandbox\\pocs\\dhlogger\\testlogger.py\", line 41, in <module>\n    make_call_stack_more_impressive()\n  File \"D:\\sandbox\\pocs\\dhlogger\\testlogger.py\", line 38, in make_call_stack_more_impressive\n    log.info(\"all better now!\", stack_info=True)", "filename": "testlogger.py", "func_name": "make_call_stack_more_impressive", "level": "info", "lineno": 38, "timestamp": "2022-01-17 07:42:00"}`
My question is
How can I remove the asci color codes in logging.log file while still be able to  show the exceptions in rich format on console? 

Appreciate any pointers or solution.

**Comment by hynek** [comment]
You seem to have configured structlog to log rendered strings into stdlib logging. You have to use https://www.structlog.org/en/stable/api.html#structlog.stdlib.ProcessorFormatter.wrap_for_formatter in your structlog configuration as renderer (aka last processor), such taht your ProcessorFormatters within logging get raw data.

**Comment by sukeshlaghate** [comment]
Thanks that did the trick.
