### ISSUE TITLE
NameError: name 'CallsiteParameter' is not defined

### ISSUE THREAD

**Issue by Ragz875** [hynek/structlog#397]
I use latest structlog package 

      pip3 list | grep 'structlog'
      structlog          21.5.0 
      
my program unable to identify class **structlog.processors.CallsiteParameterAdder**.  

code:
=====
import structlog 
structlog.configure(
        processors=[
            structlog.stdlib.filter_by_level,
            structlog.stdlib.add_log_level_number,
            structlog.stdlib.add_log_level,
            structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M.%S"),
            structlog.stdlib.PositionalArgumentsFormatter(),
            structlog.processors.format_exc_info,
            structlog.processors.UnicodeDecoder(),
            structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
            structlog.processors.CallsiteParameterAdder(
                CallsiteParameter.FILENAME,
                CallsiteParameter.FUNC_NAME,
                CallsiteParameter.LINENO,
            )
        ],
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True,
        #context_class=structlog.threadlocal.wrap_dict(dict),
        context_class=dict 
    )

**Comment by hynek** [comment]
Please import `CallsiteParameter` from `structlog.processors` or change the lines to `structlog.processors.CallsiteParameter.FILENAME` etc – I will fix the example.

**Comment by Ragz875** [comment]
Hello Hynek,
Thanks for quick turn around. 
after adding 'from structlog.processors import CallsiteParameter' not found error has gone. But came up with another error. This error is coming for WARN and above levels.

here is my full code.

===
import logging 
import sys
import structlog 
from structlog.processors import CallsiteParameter

def m_get_logger():
    print('inside m_logger')

    structlog.configure(
        processors=[
            structlog.stdlib.filter_by_level,
            structlog.stdlib.add_log_level_number,
            structlog.stdlib.add_log_level,
            structlog.stdlib.add_logger_name,
            structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M.%S"),
            structlog.stdlib.PositionalArgumentsFormatter(),
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,
            structlog.processors.UnicodeDecoder(),
            structlog.processors.ExceptionPrettyPrinter(),
            
        # https://github.com/hynek/structlog/issues/397
        # issue reported 
            structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
            structlog.processors.CallsiteParameterAdder(
                parameters=[
                    CallsiteParameter.FILENAME,
                    CallsiteParameter.FUNC_NAME,
                    CallsiteParameter.LINENO,
                ]
            ),
        ],
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True,
        context_class=structlog.threadlocal.wrap_dict(dict),
    )
    
    # logger object  
    log = logging.getLogger()

    # setup console handler 
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setFormatter(structlog.stdlib.ProcessorFormatter(processor=structlog.dev.ConsoleRenderer(colors=True)))


    fhandler = logging.FileHandler(filename='app_log.txt', mode='a')
    fhandler.setFormatter(structlog.stdlib.ProcessorFormatter(processor=structlog.processors.JSONRenderer()))

    #fm = logging.Formatter(FORMAT)
    log.addHandler(fhandler)
    #log.addHandler(console_handler)
    log.setLevel(logging.DEBUG)

    logger = structlog.get_logger('my_struct_log')

    return logger


s_log = m_get_logger()
s_log.info('test logging info')
s_log.info('test logging info')
s_log.error('test logging error')
==

error:
====
inside m_logger
Traceback (most recent call last):
  File "m_logging.py", line 62, in <module>
    s_log.info('test logging info')
  File "/Library/Python/3.8/site-packages/structlog/stdlib.py", line 148, in info
    return self._proxy_to_logger("info", event, *args, **kw)
  File "/Library/Python/3.8/site-packages/structlog/stdlib.py", line 213, in _proxy_to_logger
    return super()._proxy_to_logger(method_name, event=event, **event_kw)
  File "/Library/Python/3.8/site-packages/structlog/_base.py", line 203, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/Library/Python/3.8/site-packages/structlog/_base.py", line 160, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/Library/Python/3.8/site-packages/structlog/processors.py", line 710, in __call__
    record: Optional[logging.LogRecord] = event_dict.get("_record")
AttributeError: 'tuple' object has no attribute 'get'
===

if i remove parameters list and pass just CallsiteParameter.* params  then facing other error 
code: 
structlog.processors.CallsiteParameterAdder(
    #            parameters=[
                CallsiteParameter.FILENAME,
                CallsiteParameter.FUNC_NAME,
                CallsiteParameter.LINENO,
    #            ]
           ),

error:
inside m_logger
Traceback (most recent call last):
  File "m_logging.py", line 60, in <module>
    s_log = m_get_logger()
  File "m_logging.py", line 25, in m_get_logger
    structlog.processors.CallsiteParameterAdder(
TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given


Note - Trying to explore structlog new features in my project. Was using stdlib logging before. 
Appreciate your time.

**Comment by hynek** [comment]
CallsiteParameterAdded takes a set of CallSiteParameters: https://www.structlog.org/en/stable/api.html#structlog.processors.CallsiteParameterAdder

I.e. you need to wrap them in `{}`.

**Comment by dineshbvadhia** [comment]
Still confused about how to configure `CallsiteParameterAdded` re the above example:
```
structlog.processors.CallsiteParameterAdder(
                CallsiteParameter.FILENAME,
                CallsiteParameter.FUNC_NAME,
                CallsiteParameter.LINENO,
           ),
```
I'm using the structlog default configuration. How do you get hold of the `CallsiteParameter` values to put into a logger.info() statement after an exception for example?

**Comment by Ragz875** [comment]
> CallsiteParameterAdded takes a set of CallSiteParameters: https://www.structlog.org/en/stable/api.html#structlog.processors.CallsiteParameterAdder
> 
> I.e. you need to wrap them in `{}`.

Hello Hynek,

thanks for your reply. 
Apology for the late reply. I tried placing the key=values in {} but still no luck. I dont know whats wrong here. Please look at the error msg below:

Tried:
```
structlog.processors.CallsiteParameterAdder(
                parameters={   
                    CallsiteParameter.FILENAME,
                    CallsiteParameter.FUNC_NAME,
                    CallsiteParameter.LINENO
                }
            ), 
```

error:
Traceback (most recent call last):
```
  File "p_main.py", line 18, in <module>
    logger.info('Array initialized some key/val', key1 = 'step2')
  File "/Library/Python/3.8/site-packages/structlog/stdlib.py", line 148, in info
    return self._proxy_to_logger("info", event, *args, **kw)
  File "/Library/Python/3.8/site-packages/structlog/stdlib.py", line 213, in _proxy_to_logger
    return super()._proxy_to_logger(method_name, event=event, **event_kw)
  File "/Library/Python/3.8/site-packages/structlog/_base.py", line 203, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/Library/Python/3.8/site-packages/structlog/_base.py", line 160, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/Library/Python/3.8/site-packages/structlog/processors.py", line 710, in __call__
    record: Optional[logging.LogRecord] = event_dict.get("_record")
AttributeError: 'tuple' object has no attribute 'get'
```

**Comment by Ragz875** [comment]
> log = logging.getLogger()

Hi,

look at my example above. first I am configuring the basic logging 

**log = logging.getLogger()**

then on top of stuctlog configuration
 **logger = structlog.get_logger('my_struct_log')**

I am stuck at using CallsiteParameters (added recently)

**Comment by hynek** [comment]
You're probably lacking a final `structlog.stdlib.ProcessorFormatter.wrap_for_formatter,` processor that prepares the log entries for stdlib formatters.
