### ISSUE TITLE
structlog.configure() after bind() ? 

### ISSUE THREAD

**Issue by lcosmin** [hynek/structlog#400]
Not sure if this is an issue or just me not understanding the inner workings of structlog. I have this test code:

```
import structlog

blog = structlog.get_logger().bind(module="blog")
blog.info("blog: hello from before configuring the logger")

structlog.configure(
        processors=[
                structlog.threadlocal.merge_threadlocal,
                structlog.processors.add_log_level,
                structlog.processors.TimeStamper(fmt="iso", key="@timestamp"),
                structlog.processors.JSONRenderer(),
        ],
        context_class=dict,
        logger_factory=structlog.PrintLoggerFactory(),
        cache_logger_on_first_use=False
)

alog = structlog.get_logger()
alog.info("alog: hello")
blog.info("blog: hello again")
```

My expectation is that `blog` would be reconfigured after calling `structlog.configure()` to log JSON too, like `alog` does.

However, this doesn't happen if I have  `.bind(module="blog")` when creating the logger, and it continues to log with the configuration from before calling `configure()`. But if I write `blog = structlog.get_logger()`, everything works as expected. 

Is this normal or a bug?

**Comment by hynek** [comment]
This is normal. Once a logger is bound, it is finalized for performance reasons. The alternative would be for structlog to reinterpret the configuration before each log call which is prohibitive under load.

What you can control is whether or not the logger that has been returned from `get_logger()` is cached too (in production: advisable, in testing: not so much) by passing `cache_logger_on_first_use=True` to `structlog.configure()` (or `structlog.wrap_logger()`).

If you want to pre-populate `blog`, use `get_logger`'s `**initial_values` feature:

```python
>>> import structlog
>>> blog = structlog.get_logger(module="blog")
>>> blog.info("hi")
2022-02-11 16:56.41 [info     ] hi                             module=blog
```
