### ISSUE TITLE
Allow bind() to be used as a context manager

### ISSUE THREAD

**Issue by SwampFalc** [hynek/structlog#402]
So I've been looking all over, since to me this seems so obvious, but...

Can logger.bind() really not be used as a context manager? I mean, I find myself wanting to write code like this quite often:

    high_level_log = structlog.get_logger()
    with logger.bind(phase=1):
        run_phase_one(logger)

The basic idea is to have blocks of code, around which certain values are preset, and which get unbound after the block.

**Comment by hynek** [comment]
Loggers are immutable so context managers make no sense. If you bind something, you get a new logger back. So if you want a temporary logger, just give it a new name.

There’s context managers for loggers with global scope (contextvars/thread-locals).
