### ISSUE TITLE
structlog.threadlocal should be deprecated

### ISSUE THREAD

**Issue by hynek** [hynek/structlog#406]
I didn't realize it originally, but [as confirmed by Yury](https://twitter.com/1st1/status/1483807086341406720), contextvars are a higher-level abstraction that includes threadlocal and therefore we should stop maintaining both.

Greenlets appear to be [supported too](https://greenlet.readthedocs.io/en/latest/contextvars.html), so we can effectively stop maintaining/testing that code.

---

I'm afraid of the shitstorm if we removed it, but I would deprecate it, add a fat banner in the docs steering people to contextvars, and simplify our testing matrix.

cc @MarkusH

**Comment by MarkusH** [comment]
I've started to be a bit more rigorous in the features I'm supporting in my libraries. If there's a better or easier or more general solution, it seems like deprecating the other stuff makes sense.

So, yeah, I'd support deprecating threadlocals.
