### ISSUE TITLE
Structlog integration in linux

### ISSUE THREAD

**Issue by louistwiice** [hynek/structlog#415]
Hi Everyone

I am trying to replace Linux default logger (based on default python logging package) with structlog. Structlog is more convenient me when running python script and logging django. So I would like to integrate into Linux. I haven't found any tuto or links related to that. So if someone could help me it would be great

The default Linux logger used a logging.conf. So maybe editing this file to structlog convention (I don't know)

Thank you again guyz

**Comment by hynek** [comment]
I'm not 100% sure what you mean, since "Linux" means a lot of things. Are you logging to syslog?

**Comment by louistwiice** [comment]
Hi,

Sorry, that wasn't clear. 
I am working on editing all of my log format on different platform to have in rendered in JSON format. Like for example, we use Docker image in production and

**Comment by louistwiice** [comment]
Hi,

For example, is there a way to use struclog as default logger in different platform (Docker for example).

**Comment by hynek** [comment]
You’ve deleted your answer but mentioned Docker. Usually, in modern apps you want to log to standard out and capture the output with external tools.

see https://www.structlog.org/en/stable/logging-best-practices.html

**Comment by louistwiice** [comment]
Hi,

Sorry for the late reply. I have found that structlog has a package that could be installed by apt command. I was trying to check if it was possible to integrate it into our Docker Images.

Yes, I am trying to use it on Docker. To Capture my logs I use EFK (Elasticsearch, Fluentd and Kibana). But the thing is there are two logs:
* Logs from the container (system)
* Logs from our application (add by us when needed)

I have use struclog for my application (Django in Docker) and it seems there are part of my logs which are not in structlog JSON format. And I don't know why. That is why I am asking.

Do you have any tuto or links related to that?

**Comment by hynek** [comment]
You probably mean logs coming from standard library's logging module. There's different ways to integrate them and it's documented here: https://www.structlog.org/en/stable/standard-library.html
