### ISSUE TITLE
BytesLogger crashes in Jupyter Notebook

### ISSUE THREAD

**Issue by steve-marmalade** [hynek/structlog#417]
Hi there, I'm a huge fan of this project, thank you for all of the great work.

I wanted to report a bug a just came across when using structlog + orjson in a Jupyter Notebook.

## Steps to reproduce

- Open a Jupyter Notebook
- Configure structlog per the [Performance example](https://www.structlog.org/en/stable/performance.html#example)
- Try to log something

```python
import logging

import orjson
import structlog

structlog.configure(
    cache_logger_on_first_use=True,
    wrapper_class=structlog.make_filtering_bound_logger(logging.INFO),
    processors=[
        structlog.threadlocal.merge_threadlocal,
        structlog.processors.add_log_level,
        structlog.processors.format_exc_info,
        structlog.processors.TimeStamper(fmt="iso", utc=True),
        structlog.processors.JSONRenderer(serializer=orjson.dumps),
    ],
    logger_factory=structlog.BytesLoggerFactory(),
)
log = structlog.get_logger()

log.info("hello")
```

## Result

Throws `AttributeError: 'OutStream' object has no attribute 'buffer'`

## Expected Result

Print the JSON bytes as usual

## Potential Solution

Based on [this open issue in ipykernel](https://github.com/ipython/ipykernel/issues/786#issuecomment-960636168), it appears that `sys.stdout.buffer` should not be accessed unconditionally.

**Comment by hynek** [comment]
Well in that case I guess you can't use BytesLogger? You can instantiate it with your own bytes-based file, no idea what that would be for IPython though.

**Comment by hynek** [comment]
Closing this because this is not solvable.

Ideally use the higher-level [PrintLogger](https://www.structlog.org/en/latest/api.html#structlog.PrintLogger) if cases like this are likely to happen
