### ISSUE TITLE
What is the lowest boilerplate way to output a second log format to file?

### ISSUE THREAD

**Issue by arthur-st** [hynek/structlog#423]
Essentially, what I wanted to have simultaneously is

1. Default `structlog.get_logger()` experience for the `sys.stdout` with X filtering level;
2. JSON stream to a file with Y filtering level;

I spent an hour on the docs, and couldn't figure out if there is some low-boilerplate way to do this, that wouldn't involve understanding the entire library bottoms-up and constructing a logger from zero.

**Comment by hynek** [comment]
That would be the last stdlib approach: https://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging

The last example does something very similar (it just does colors vs plain, not JSON).

**Comment by arthur-st** [comment]
I see, thank you for responding. I was hoping that there would be something more concise, and so I hadn't investigated that section of the page. The example does work as expected.

**Comment by hynek** [comment]
I wish it was too. :) Sadly these use-cases are a bit kore complicated than they look. :-/
