### ISSUE TITLE
Add more stdlib specific processors and recommend their use

### ISSUE THREAD

**Issue by wbolster** [hynek/structlog#43]
Following discussion in #40, the processors that add the logger name and log level to the event should be added to structlog itself instead of living as mere suggestions in the docs. In addition the use of these processors should be recommended in the configuration example in the docs.  In addition to that, the recently added positional arguments processor from #19 and #34 should also make it into the suggested configuration.

What needs to be done is:

* [x] Move the `add_logger_name()` and `add_log_level()` processors from the suggested documentation changes in from #40 into the `structlog.stlib` module.
* [x] Add tests for those processors
* [ ] Update the recommended configuration in the docs to include these two processors, and  also the positional arguments formatter
* [ ] Rework the documentation changes in #40 so that it reflects the changes above

**Comment by wbolster** [comment]
@hynek comments?

**Comment by hynek** [comment]
sgtm

**Comment by wbolster** [comment]
@hynek the tests can be pretty basic, right? e.g. just something trivial to assert that the key is added to the event_dict should be enough, right? it's not like they affect the whole pipeline.

**Comment by hynek** [comment]
yeah just unit tests.  the nice thing about processors is that they are very simple to test.

**Comment by wbolster** [comment]
Last two open points from the issue description should be covered in #40.

**Comment by hynek** [comment]
yep!
