### ISSUE TITLE
[Dev experience] get_logger returns Any

### ISSUE THREAD

**Issue by 1oglop1** [hynek/structlog#434]
Hi, I'm just playing with `structlog` as well as `mflog` and I found out that `structlog` doesn't play nicely with IDEs. (tested VSCode, PyCharm)

![image](https://user-images.githubusercontent.com/7480694/181429228-5d223a45-8201-4ec7-9d7d-85a749958b51.png)

So I made a workaround but I'm not sure that the type is correct.

![image](https://user-images.githubusercontent.com/7480694/181429850-1e4f8d59-f9d2-41e0-86fb-b958980673ce.png)

It would be nice if there is a return type for `get_logger` or is it not possible?

**Comment by hynek** [comment]
It's not possible, because the type can be set freely.

You can either use a type annotation (since that happens once per file, I don't think that's a problem) or if you use stdlib, there's a structlog.stdlib.get_logger

See https://www.structlog.org/en/stable/types.html

**Comment by 1oglop1** [comment]
Thanks, I'll take a look! 

PS. I just discovered that `make_filtering_bound_logger` breaks `structlog.stdlib.PositionalArgumentsFormatter()`

```
logger.critical("message with templates: %i, %s", 2, "foo")
TypeError: meth() takes 2 positional arguments but 4 were given
```

Is this intended or a bug?

**Comment by hynek** [comment]
`make_filtering_bound_logger` is not meant to co-operate with stdlib. It's a high-performance replacement if you don't need stdlib's flexibility

**Comment by 1oglop1** [comment]
Cool, I do not need the flexibility, I actually like kwargs more.

I'm making a simple logging library that can be used in the CLI app and drop-in other apps. 

The last feature I need is to disable log output by default unless `init_logging` function is called.

I'm not sure how to achieve it yet.

**Comment by hynek** [comment]
I would suggest to fully configure structlog the way you want it and add an own processor at the beginning of the processor chain that raises DropEvent until some global variable has been set that you set in init_logging.
