### ISSUE TITLE
LogCapture(), pytest and logging in threads

### ISSUE THREAD

**Issue by hkokko** [hynek/structlog#436]
I am trying out structlog and it is working out quite nicely. There is an issue that I have not found a solution for. 

I am using the example pytest from https://www.structlog.org/en/21.1.0/testing.html in my code and it is not capturing all the records in the log_capture.  

Application code approach: 
I am configuring the structlog in my application code task (subtask_a.py) in a common function (logger_setup(topic)) where topic is the name of the module and where the logger_setup(subtask_a) is called when the file subtask_a.py is imported to main.py. 

The subtask_a.py is called from apscheduler.   When subtask_a is running it receives messages which cause it to invoke a number of multiprocessing threads  which are function_of_subtask_a within subtask_a. Subtask_a and function_of_subtask_a log all nicely to a log file log_of_subtask_a.log.  They all use the same configuration common function with the same topic. 

All of the above log nicely. 

Test code approach: 
I am testing this from pytest using the testing example from the first line above. It seems that all the events that are sent from the threads of subtask_a are logged into the log file but are not visible in the log_capture. All of the errors etc that are logged from the subtask_a itself ARE visible in the log_capture and in the logs.  Why would the log entries from multiprocessing threads not be visible in the log_capture but are visible in the log files. 

With caplog and normal logging this worked well - I have tried just to change those bits that are required for structlog to work. 

Is there something that I am missing in the usage or configuration here.

**Comment by hynek** [comment]
It seems like your test code doesn’t get properly configured in test. Try inspecting structlog.get_config() and take it from there. If you’re using subprocesses, the issue could be that the test config is applied after the process has been started.

**Comment by rozumalex** [comment]
Hi, @hkokko! I was also struggling with failing tests.

For me capturing logs worked fine when running single test, but as soon as they were running in batch, tests were failing and logs were not captured.

What's more, it looked like only single test was always successful in every thread.

So I'm assuming that when `configure_structlog` is autoused, it configure processor with initial `LogCapture` instance that works for first test where `log_output` fixture is used. In the next test `log_output` recreate `LogCapture` instance, but ` structlog.configure` doesn't make any effect and continue capturing logs to the previously used `LogCapture`.

Something that can work here is making `log_output` fixture `session` based, but only in case that that's fine for you to have logs shared between all the tests.

```
@pytest.fixture(scope="session")
def log_output():
    return LogCapture()


@pytest.fixture(autouse=True)
def configure_structlog(log_output):
    structlog.configure(
        processors=[log_output]
    )
```

**Comment by hynek** [comment]
@rozumalex Your problem sounds like #408 that has been fixed in #412. You should try it again when you get the opportunity.

**Comment by hkokko** [comment]
How should multiprocessing task (the one that is called via Pool) be configured so structlog takes into account LogCapture or capture_logs when those are defined and does not take those into account when they are not defined. I am able to get logging to work from threads but not LogCapture or capture_logs.

**Comment by hynek** [comment]
Processes are isolated from each other, so you have to communicate with the task somehow explicitly.

Would suggest to not test such things across process boundaries though.

**Comment by hkokko** [comment]
Yep. It was cumbersome to try to communicate at this level. Found another way of testing instead of using this log_entries. It is much more straightforward when you start to have more processes. Basically reading the log files directly at end of test...
