### ISSUE TITLE
no color for logs if run via pytest

### ISSUE THREAD

**Issue by The-Alchemist** [hynek/structlog#437]
## Description

If I run my tests via `pytest`, the `ConsoleRender` doesn't seem to work / doesn't seem to be activated, or `pytest` hides it.  Not sure.  Anyone know how `pytest` is capturing stdout in a way that is hiding colors?

## Output

```
# cat color_structlog_test.py                                                                                                      16:47:22
import structlog

logger = structlog.get_logger()


def test_log_something():
    logger.warn('hi', something='something else')

# python3 -m pytest color_structlog_test.py -rA                                                                                    16:47:26
============================================================================= test session starts ==============================================================================
platform darwin -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/user/project/tests/unit
plugins: requests-mock-1.9.3, mock-3.8.2
collected 1 item

color_structlog_test.py .                                                                                                                                                [100%]

==================================================================================== PASSES ====================================================================================
______________________________________________________________________________ test_log_something ______________________________________________________________________________
----------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------
2022-07-29 16:47.31 [warning  ] hi                             something=something else
=========================================================================== short test summary info ============================================================================
PASSED color_structlog_test.py::test_log_something
============================================================================== 1 passed in 0.02s ===============================================================================
#
```

## Screenshot

![image](https://user-images.githubusercontent.com/812287/181841317-52012354-2fba-4b6f-a119-5bac012e7990.png)

**Comment by hynek** [comment]
Colors are only used for interactive TTYs. You can override it by passing `force_color` . See https://www.structlog.org/en/stable/api.html#structlog.dev.ConsoleRenderer

**Comment by RonnyPfannschmidt** [comment]
It might be nice to add a pytest renderer + plugin so that integration similar to the stdlib logging gets possible

**Comment by hynek** [comment]
You mean something like https://www.structlog.org/en/stable/testing.html?

**Comment by RonnyPfannschmidt** [comment]
More something comparable to pytests logging integration, which captures logs per test +also supports live logs even if no capture fixture was used (this is more about test reporting integration than log record assertion)

**Comment by hynek** [comment]
Yeah that would be cool but sounds like a case for a `pytest-structlog` project TBH. Its a bit too much to maintain for me additionally. I'm always trying to offer accordances so people can build cool shit, so I'm not a bottleneck. :-/

**Comment by hynek** [comment]
JFTR I got it wrong in my first comment: force_colors is only meaningful on Windows.

The detection for colors is while configuration. So you only have to configure with colors=True:

https://github.com/hynek/structlog/blob/3494b6fb4a81ce25c9d5d79275fd298d5c76c7c7/src/structlog/_config.py#L37-L42
