### ISSUE TITLE
Log to HTTP API?

### ISSUE THREAD

**Issue by cpach** [hynek/structlog#442]
Can structlog be used to log (some) events to an HTTP API? E.g. Slack.

**Comment by hynek** [comment]
Yes. Anything that you can do in a Python function can happen.

**Comment by cpach** [comment]
I must admit I couldn’t really figure out how to do this from the documentation. Could you please show some examples? That would be very useful. I’m unsure where I would place the “hook” where the web API would be called.

**Comment by hynek** [comment]
Do you want to _only_ send the HTTP request or do you want to do it _in addition_ to regular logging?

**Comment by cpach** [comment]
The latter, i.e. in addition to regular logging.

**Comment by hynek** [comment]
You'll need to write a processor.

Something like this should do:

```python
def post_event_dict(_, __, event_dict):
    try:
        httpx.post(url, post=event_dict)
    except Exception:
        pass  # you probably don't want to lose the log entry

    return event_dict
```

And then make it part of the processor chain, by adding it to the list you're passing to the processors argument of [`structlog.configure()`](https://www.structlog.org/en/latest/api.html#structlog.configure).

More infos on processors: https://www.structlog.org/en/latest/processors.html
