### ISSUE TITLE
Request: Make `_config` a public namespace

### ISSUE THREAD

**Issue by Goldziher** [hynek/structlog#443]
Hi there,

I would like to ask that `_config` be changed to `config`, because I need to rely on this in code. Example test:

```python
from structlog._config import BoundLoggerLazyProxy

from starlite.config import StructLoggingConfig
from starlite.testing import create_test_client


def test_structlog_config() -> None:
    with create_test_client([], logging_config=StructLoggingConfig()) as client:
        assert isinstance(client.app.logger, BoundLoggerLazyProxy)
```

My use case is that I need to determine programmatically what kind of logger the user decided to use - and accordingly generate log messages (using kwargs or stringifying them on my own etc.)

**Comment by hynek** [comment]
You should be able to perform that check using `isinstance(client.app.logger,  structlog.types.BindableLogger)` – no?

It's always been runtime-checkable:

```pycon
>>> import structlog
>>> log = structlog.get_logger()
>>> isinstance(log, structlog.types.BindableLogger)
True
```

**Comment by Goldziher** [comment]
Cheers.
