### ISSUE TITLE
FilteringBoundLogger.{log,alog} missing

### ISSUE THREAD

**Issue by peterschutt** [hynek/structlog#460]
Hi,

I noticed that the methods `log()` and `alog()` aren't included on `typing.FilteringBoundLogger`.

They are added to the methods of the type here:

https://github.com/hynek/structlog/blob/9509a8c24f82e2ebfa70001b5a4d8f6831c64e7d/src/structlog/_log_levels.py#L193

And there is reference to `alog()` in the docstring:

https://github.com/hynek/structlog/blob/9509a8c24f82e2ebfa70001b5a4d8f6831c64e7d/src/structlog/typing.py#L157

I'd be happy to submit a PR if they are intended to be there.

Thanks!

**Comment by hynek** [comment]
Sure, thanks, fire away!
