### ISSUE TITLE
Isolate configuration from python logging?

### ISSUE THREAD

**Issue by philipmat** [hynek/structlog#467]
I'm trying to use `structlog` in combination with another application: `faust-streaming`. It seems the `faust-streaming` is hijacking the python logging config and that affects `structlog` output.

For example, I'm configuring `structlog` with `JSONRenderer` and it outputs JSON correctly before the other application starts.

```python
import faust
import structlog

structlog.configure(processors=[structlog.processors.JSONRenderer()])
logger = structlog.get_logger()
logger.info("structlog configured", message="hello world") # outputs correctly

# set up faust
app = faust.app(...)
topic = app.topic(....)

@app.topic(topic)
async def read_topic():
    logger.info("Reading from topic", topic=topic) # gets prefixed by plain text
```

The `logger.info("structlog configured", message="hello world")` line correctly outputs:  
`{ "event": "structlog configured", "message": "hello world" }`

However, the `logger.info("Reading from topic", topic=topic)` inside `read_topic` has its JSON output prefixed by some text that likely comes from faust:  
`[2022-11-08 15:16:17,123] [1] [WARNING] { "event": "Reading from topic", "topic": "test-topic" }`

I cannot quite find where in the `faust-streaming` code this is happening.

Is there any way to configure `structlog` so that it's isolated from re-configurations of the python standard logging library?

**Comment by hynek** [comment]
The configuration you're showing me doesn't use stdlib logging and should therefore be isolated. Can you verify Faust-streaming isn't configuring structlog? That would be rather unusual though. I suspect you're not showing me your whole config?

**Comment by philipmat** [comment]
This is my whole structlog config:

```python

def setup_logger(settings: Settings):
    # settings is a dataclass that has LOG_MODE:str and LOG_LEVEL:str fields
    # it reads its values from env vars
    if settings.LOG_MODE == "JSON":
        structlog.configure(processors=[structlog.processors.JSONRenderer()])

    structlog.configure(
        wrapper_class=structlog.make_filtering_bound_logger(
            getattr(logging, settings.LOG_LEVEL
        )
    )


settings = Settings()
setup_logger(settings)
logger = structlog.get_logger()
....
```

Is it the `make_filtering_bound_logger` that can would affect this once faust sets up its logging?

The `app` set up with `app = faust.app` exposes a `logger` field. If I print its `app.logger.root.level` it reports `WARNING` (well, `30`).  
If I print `logging.root.level` before `app.faust` it reports `0`. If I print it inside `read_topic` -- so when called by faust -- it reports `30`/`WARNING`.  
Since the messages always seen to be prefixed with `[...] [WARNING]`, I assumed that it's not a coincidence.

I'm confident that neither `faust`  nor `mode` (from whose `mode.utils.logging` `faust` imports a `get_logger` and a `formatter2`) use structlog. Grepping through my virtual env's site-packages shows the only references to `"structlog"` are inside the `structlog` package.

Thank you very much for any thoughts on how to further go into investigating this problem

**Comment by hynek** [comment]
If you configure structlog to use `make_filtering_bound_logger` and faust is using stdlib logging, they don't affect each other. structlog doesn't touch stdlib logging at all.

However if there's concurrency, it's possible that they affect each other in output. In other word: faust might print half a line to stdout and structlog print in between.

I would suggest to try to configure structlog to use stdlib and see if your problems persist. The easiest way is just calling `structlog.stdlib.recreate_defaults() `.

**Comment by philipmat** [comment]
Thank you, I appreciate your patience with this. 

I don't think it's a logging-interference issue. I tried to `pprint(structlog.get_config())` and every singly line of that is prefixed by `[date time] [1] [WARNING]` so something is hijacking it at an even lower level.

**Comment by hynek** [comment]
Ah yes it probably intercepts standard out.
