### ISSUE TITLE
Structlog and logging module not working with pytest

### ISSUE THREAD

**Issue by makeevolution** [hynek/structlog#468]
So I have a testing folder structure (that tests a module ```src``` not shown here) like this:
```
├── tests
│   ├── __init__.py
│   ├── conftest.py
│   ├── test_main.py
```
And have the ```__init__.py``` configure my logging as shown:
```
import structlog, logging, sys
from structlog.testing import LogCapture

logging.basicConfig(filename="test.log", filemode="w")

structlog.configure(
    processors=[LogCapture()],
    context_class=structlog.threadlocal.wrap_dict(dict),
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True
)
```

And my ```test_main.py``` as shown:
```
import logging, structlog, pytest

from src.factories.factories import MyFactory
import src.main
from pathlib import Path
from datetime import datetime

@pytest.mark.parametrize(
    "factory",
    [
        MyFactory(),
    ],
)
def test_main(path_to_results_folder_fixture_in_conftest, factory):
    structlog.get_logger().info("test")
    no_of_files_function = lambda: sum(1 for _ in Path(path_to_results_folder_fixture_in_conftest).iterdir())
    len_before = no_of_files_function()
    src.main.main("sony", factory, path_to_results_folder)
    assert no_of_files_function() == len_before + 1
```

Then I simply run ```pytest test_main.py```. I was expecting the line ```structlog.get_logger().info("test")``` to produce the line ```test``` in the ```test.log```. However, there's only an empty ```test.log``` generated. What am I doing wrong? I have configured logging, but structlog seem to not see it. For more information, nothing is also outputted to stdout/console.

**Comment by hynek** [comment]
Please don't crosspost questions to the bug tracker (https://stackoverflow.com/questions/74373394/structlog-and-logging-module-not-logging-with-pytest/74384835)
