### ISSUE TITLE
What font are you using to render the README demo of show_off.py?

### ISSUE THREAD

**Issue by eabase** [hynek/structlog#471]
I'm using `CaskaydiaCove NF` (monospace) to render it from powershell Code in my `Windows Terminal`, but the demo look very bad with this. The side borders are completely gone.

![image](https://user-images.githubusercontent.com/52289379/201690968-e942f724-24af-48ac-a4bd-9fb896018a46.png)

I also tried in Cygwin using `Lucida Console` (9 pt), but there the corners gets messed up and the **bold** look fuzzy.

![image](https://user-images.githubusercontent.com/52289379/201691964-6ddf4090-4b76-428c-9a8b-8230394bd438.png)

What terminal and font did you use for the demo image shown  on the README page?
 
---

It seem to render ok, using `Cascadia Code` (15pt) in native powershell terminal. 
(But that font is not very good at rendering in **bold**, emoji's & glyphs.)

![image](https://user-images.githubusercontent.com/52289379/201693313-989a2929-6287-4485-b5f5-18afd9a38083.png)

**Comment by hynek** [comment]
The font I'm using is https://berkeleygraphics.com/typefaces/berkeley-mono/ (non-free), but it looks fine with [JetBrains Mono](https://www.jetbrains.com/lp/mono/) or https://rubjo.github.io/victor-mono/ too.

FWIW, this rendering is done by https://rich.readthedocs.io/ – I have no influence over it.

**Comment by eabase** [comment]
@hynek 
Very nice! Thank you! ✨
