### ISSUE TITLE
stuctlog.processors.TimeStamper doesn't seem to work as documented

### ISSUE THREAD

**Issue by placeybordeaux** [hynek/structlog#49]
```
>>> logger = structlog.wrap_logger(logger, processors=[structlog.processors.TimeStamper()])
>>> logger.info("zxcv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/structlog/_base.py", line 176, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
TypeError: msg() got an unexpected keyword argument 'timestamp'
```

Judging by the docs that should work. Not sure what is wrong.

Running on python3, structlog 15.1.0

**Comment by hynek** [comment]
You appear to not have specified a rendering processor.  As it stands, your logger is called `logger.info(**{"event": "zxcv", "timstamp": "the timestamp", …})` which it can’t handle.

You’ll have to add a processor that converts the dictionary into a string if you want to use it with a string-based logger.  For example http://www.structlog.org/en/stable/api.html#structlog.processors.KeyValueRenderer

See also: http://www.structlog.org/en/stable/processors.html#adapting-and-rendering

Feel free to re-open if I misunderstood your problem.

**Comment by placeybordeaux** [comment]
You are right. I figured it out shortly after you commented. I personally find this behavior very confusing, but if this is the intended behavior I won't squabble.

**Comment by hynek** [comment]
I think it’s only confusing if you presume, that the output is always strings.  But you may want to adapt the dictionary to something different or use a logger that actually accepts such a call; saving you a round of formatting etc.
