### ISSUE TITLE
structlog.contextvars with non-async FastAPI dependencies

### ISSUE THREAD

**Issue by dabljues** [hynek/structlog#491]
Hi.

I'm working on a small FastAPI application and I'm trying to move to `structlog.contextvars`. I'm using `structlog==22.3.0`

Basically, up until now, I was doing things wrong. I wasn't using `structlog.threadlocal.merge_threadlocal` or `structlog.threadlocal.bind_threadlocal`. I was just using `logger.bind()`. And not in the good way, in the way that is explicitly discouraged in the docs - so no new logger creation like `logger = logger.bind()`. Just `logger.bind()`, globally.

Anyway, I had some troubles moving to `structlog.contextvars`. I created an issue on FastAPI GH demonstrating it -> [link](https://github.com/tiangolo/fastapi/discussions/5999). But then, I thought that maybe the issue belongs here, not there. I'm really not sure. The code to reproduce it is really small, so I will also copy it here:

```python
import structlog
from fastapi import Depends, FastAPI, Response

LOGGER = structlog.get_logger()


def bind_a():
    structlog.contextvars.bind_contextvars(a="a")


async def bind_b():
    structlog.contextvars.bind_contextvars(b="b")


api = FastAPI(
    dependencies=[Depends(bind_a), Depends(bind_b)],
)


@api.get("/foo")
def foo():
    LOGGER.info("api:get:foo")
    return Response()
```

Just a side note - I wouldn't like to make changes to the `LOGGER` variable. In real code, the bounding would be done in another file, `LOGGER` is in another, so I can't just go for `LOGGER = LOGGER.bind(...)`, because it's not a global variable between files.

## Expected behavior

When calling `/foo` endpoint, I'd expect that the logger would log something like this:

```sh
2023-02-14 14:26:06 [info     ] api:get:foo                    a=a b=b
```

Unfortuately, it only logs:

```sh
2023-02-14 14:26:06 [info     ] api:get:foo                    b=b
```

However, if I make `bind_a` async, both values are bound (`a` and `b`).

I guess at least some of the people are probably familiar with FastAPI, but just to be clear, those two `bind_` functions are global dependencies to the whole API, so the code in those functions is executed each time every endpoint is called (I can make them "local" - I mean add them only to the endpoints I want, doesn't matter in this case, I checked). In production code, I'd use a `try/except` block with `yield`, so when a response from an endpoint is returned, I'd unbind those values.

My first instinct was that this has something to do with FastAPI. And I still may be right, but I'm really not sure anymore. I tried searching through other issues, but I didn't find any similar ones. As you can see, I'm using the default configuration in this short example. In production I'd provide my own, with `structlog.contextvars.merge_contextvars` as the first processor.

So, do you guys know what's happening here? Why does `bind_a` have to be async for the `structlog.contextvars` to work? Am I using `structlog.contextvars` wrong? Or maybe did you encounter the same problem with FastAPI?

**Comment by dabljues** [comment]
Issue resolved: https://github.com/tiangolo/fastapi/discussions/5999

**Comment by hynek** [comment]
I'm traveling for the foreseeable time, but is there something we could / should add to the docs?

**Comment by dabljues** [comment]
Well, I actually think that there should be a mention of this somewhere in the docs. I was reading the documentation from the beginning and when I got to and finished the `Contextvars` chapter, I didn't find the answer to my problem.

FastAPI is pretty widely used and while I didn't find issues when using `structlog.contextvars` with our without async in the usual Python code (as it should be), then maybe it'd be a good idea to include a simple FastAPI example (structlog docs already have a Flask one, right in the chapter about contextvars) - quite like the one I proposed. It's short, easy to grasp. FastAPI/starlette may change this behavior, so it's not that future-proof, but still.

This is not an issue in `structlog` per se, but it may be a good idea to warn people that things like FastAPI (and probably other libraries/frameworks as well) can make it problematic to use `structlog.contextvars`. It doesn't have anything to do with `structlog`, but rather with Python contextvars, but again - structlog uses it and if someone tries to do something like I did, they may encounter an issue exactly like mine.

**Comment by hynek** [comment]
I don’t use FastAPI myself so I don’t feel qualified to produce a best-practice recipe myself, but I’m open to PRs contributing one of course!

That said, it looks like FastAPI “fixed” it by working around it? My cursory understanding is that the problem is centered on the difference of how context vars are implemented in sync vs async?

**Comment by Jdsleppy** [comment]
I wouldn't consider what's in [the related FastAPI issue](https://github.com/tiangolo/fastapi/discussions/5999) to be a good workaround, more like a retreat.  In that issue, the user was able to change a sync dependency (a FastAPI consruct)  to async to work around.  It's easy enough to turn a CPU-bound dependency into an async one, but in my current case I have database access in my dependency so making it async is not trivial.

I wanted to do this eventually anyways, but I didn't think it would be structured logging that forced me to start using an async Postgres driver!  If we wanted to add one, the note in the docs should warn users that setting Structlog context variables in an environment where the flavor of context changes (between threads, asyncio, and/or greenlets)  may cause context variables to be lost.

**Comment by hynek** [comment]
To clarify:

What ya’ll are asking for is a warning in the contextvars docs, that async and threaded codes uses different storage, correct?

**Comment by Jdsleppy** [comment]
I'm not very familiar with stdlib contextvars so there could be more nuance to it, but that is my understanding from what I've read on this problem.  A stab at some wording:

"Contextvars set in one thread or asyncio task will not be available in another thread or asyncio task.  This causes contextvars set from a short-lived thread or task to appear to be lost when the interpreter returns to the main thread.  One example of this is FastAPI, an asyncio web framework that also runs user-defined synchronous functions in a threadpool."

There are GitHub issues in structlog and FastAPI for this problem now so users doing a web search are able to find some help even if it's not in the docs.  A note like the one above would have definitely caught my attention during the tutorial, though, and saved me some time.
