### ISSUE TITLE
Color Output on github actions

### ISSUE THREAD

**Issue by ecs-jnguyen** [hynek/structlog#495]
Hello, I am trying to use structlog in a github action job and I noticed that there isn't any color output. Is there a setting that I'm missing to enable colors in github actions?

Here's my github actions job run:

https://github.com/ecs-jnguyen/test-actions-colors/actions/runs/4357219988/jobs/7616263866

Here is the python code that I'm using:

```python
import structlog

if __name__ == "__main__":
    logger = structlog.get_logger()
    logger.info("hello", name="me", age=123)
    logger.warning("bye", name="me", age=123)
    logger.error("ohno", name="me", age=123)
```

**Comment by hynek** [comment]
structlog checks if the terminal is a tty, which it probably isn't for GHA: https://github.com/hynek/structlog/blob/74cdff93af217519d4ebea05184f5e0db2972556/src/structlog/_config.py#L37-L42

You'll have to configure it by hand and explicitly pass `colors=True`.

**Comment by ecs-jnguyen** [comment]
I've seen a lot of talks about the use of the environment variable `FORCE_COLOR=1` or `FORCE_COLOR=true` to get colors in CI tools like github actions. Could we do the same with structlog so that users don't have to configure the default list of processors for this one setting?

References:
- https://github.com/python/mypy/pull/13814
- https://github.com/pytest-dev/pytest/pull/7466

**Comment by hynek** [comment]
This is an interesting question and transition period. structlog has exploded for use-cases that I never anticipated. CLI output used to be just a perk for development. I guess we [cs]ould accept the new role and make it nicer out of the box…
