### ISSUE TITLE
structlog eats "level" key/val

### ISSUE THREAD

**Issue by wimglenn** [hynek/structlog#509]
Here the key/val "level=2" context is silently lost.

```
>>> import structlog
>>> log = structlog.get_logger()
>>> log.info("going up...", elevator=1, level=2)
2023-05-04 15:23:28 [info     ] going up...                    elevator=1
```

I'm not sure this is actually worth doing anything about, but it might be worth documenting what key/val are permissible.

Another problematic one is the key "event" (you can encounter a `TypeError` about sending multiple values for the argument if you're naively unsplatting some dict of data which happens to have an event key)

**Comment by hynek** [comment]
In hindsight, those should've been prefixed but hard to fix it later.

FWIW [it's documented](https://www.structlog.org/en/stable/api.html#structlog.processors.add_log_level) and there's [a recipe](https://www.structlog.org/en/stable/recipes.html#renaming-the-event-key) for the `event` case.
