### ISSUE TITLE
ProcessorFormatter should be able to pass the message unformatted

### ISSUE THREAD

**Issue by karolinepauls** [hynek/structlog#520]
https://github.com/hynek/structlog/blob/f7145a6a815083a748ec2e41a1d66dd63ce6c411/src/structlog/stdlib.py#L1016

The problematic pipeline is logging ->  ProcessorFormatter -> structlog -> Sentry.

Currently ProcessorFormatter calls `getMessage` on the log record.

This means that the formatted log message from `logging` becomes the "event" field in `structlog`. This causes duplicates if structlog is integrated with Sentry, which groups messages by the "event" field. If the "event" field wasn't formatted, the messages would get grouped correctly.

There should be a flag on ProcessorFormatter that allows it to pass the log message unformatted, like `"event": str(record.msg),` ([`LogRecord.msg` can be anything supporting `__str__`](https://docs.python.org/3/library/logging.html#logging.LogRecord)).

Passing positional args is already supported thanks to the `pass_foreign_args` flag.

**Comment by hynek** [comment]
Could you give me more concrete examples of how this would be used? Adding a bool field to ProcessorFormatter shouldn't be a problem, but I'd like to understand what this is exactly about and how it would be used (which also means how I would document it).

**Comment by karolinepauls** [comment]
Use case: I believe that ProcessorFormatter can only be used as a stdlib logging formatter which sends logs to structlog.

If your loging pipeline is `logging -> ProcessorFormatter -> structlog -> structlog_sentry -> Sentry`, if messages are formatted in structlog, Sentry will not be able to group them. (No we don't send all log messages to Sentry, but I'm skipping the irrelevant branches, like logging to stderr).

Context:

When using Sentry with stdlib logging, Sentry groups captured events by the first argument, so that it doesn't produce an unbounded amount of duplicate events but instead, aggregates them nicely by log message template (`LogRecord.msg`). 

This is a common problem with stdlib logging.

e.g. `log.warning('Something happened %s', num)` is good, since , while `log.warning('fSomething happened {num}')` is bad because it eagerly formats the first argument and will result in a distinct Sentry event for each distinct `num`.

When integrating Sentry with structlog, the "event" key becomes the "message" Sentry aggregates logs:
https://github.com/kiwicom/structlog-sentry/blob/4ce81b131641b830438f16169455ac625382fc19/structlog_sentry/__init__.py#L128
This makes sense because "event" is the first argument, which will not be formatted. Instead, kwargs will be passed to structlog, e.g. `log.error("Something happened", num=num)` will result in the Sentry event message being "Something happened" and that being the deduplication key.

With `ProcessorFormatter` however, the "event" key becomes pre-formatted by the processor and the duplicates start there.


This makes me wonder. I am not the person who set up structlog for us so I don't know the details but: Why the official way to send `logging` to `structlog` is `ProcessorFormatter`? Why cannot it be a logging handler rather than a formatter?

**Comment by hynek** [comment]
hi, sorry for the delay – is #550 what you had in mind?

(let's talk about the last question elsewhere, short answer is that I don't know because most of the stdlib code has been contributed)

**Comment by bcdickinson** [comment]
Just adding a +1 here, because I ran into a similar issue with Rollbar. 

In that case, sadly, I couldn't use `ProcessorFormatter` because Rollbar's `RollbarHandler` (from [pyrollbar](https://github.com/rollbar/pyrollbar)) doesn't actually use a formatter at all, it just sends the payload to the Rollbar API straight from its `emit()` method without attempting to call `format()`. I think maybe this issue has shed some light on why it does that!

**Comment by hynek** [comment]
I'm a bit confused here. Her problem was that ProcessorFromatter formatted the messages – if you don't use it, how is that an +1? 😅

**Comment by bcdickinson** [comment]
Just a +1 for the feature request because I can see how it would be useful :slightly_smiling_face:

#550 looks nearly identical to what I ended doing in my custom code for Rollbar. I guess that code is maybe filling the same niche as `structlog-sentry` does... i.e. converting back from an event_dict format to something compatible with stdlib logging so that 3rd party logging integrations can use it.
