### ISSUE TITLE
Logging to both stdout and file with orjson via BytesLoggerFactory?

### ISSUE THREAD

**Issue by floxay** [hynek/structlog#527]
I have two handlers configured, a `StreamHandler` set to `stdout` and a `WatchedFileHandler`.
Using `JSONRenderer` processor with `json.dumps` and `stdlib.LoggingFactory` works as expected; the logs show up in both places. However after switching to `orjson.dumps` and `BytesLoggerFactory` the log entries only show up on `stdout`, the log file does not change.

I suspect this is because `BytesLogger` writes to `stdout` by default, but I am unsure how to make it output logs to both places then.
Doing `BytesLoggerFactory(file=log_file.open(mode="ab"))` could be a **half** workaround to at least have it log to the file, I guess, but opening a handle like this... does not seem right.

**Comment by hynek** [comment]
I think https://pypi.org/project/multistructlog/ should be adequate?

**Comment by floxay** [comment]
Thanks, but that project appears to be dead for some years now.
If I were to drop logging to `stdout` and log only to a file what is the preferred method doing that with `BytesLogger(Factory)`? Would the mentioned `BytesLoggerFactory(file=log_file.open(mode="ab"))` be OK?

**Comment by hynek** [comment]
Yes that should work! BytesLogger behind every line, so there should be no reason to be uneasy.

You can keep the file handle around and close it manually on application shutdown (e.g., an `atexit` handler) if you want to be a model UNIX citizen!
