### ISSUE TITLE
How can I intercept stdlib logging used in 3rd party library?

### ISSUE THREAD

**Issue by kindaway** [hynek/structlog#536]
Not exactly an issue, but I can't figure it out and came here to get some help:
I have some package installed which has some "logging.info()" in its source code. I'd like these messages to be formatted in a structlog's way. What should I configure to achieve this?
Thanks in advance for any help!

**Comment by hynek** [comment]
There're 4 ways that are documented in https://www.structlog.org/en/stable/standard-library.html#suggested-configurations – pick whichever fits your use case best!
