### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by zmsmith** [hynek/structlog#54]
We'd love to use #52. I'm happy to pitch in if there are any blockers.

**Comment by hynek** [comment]
[Done](https://pypi.python.org/pypi/structlog/15.2.0)!  I was waiting for more features but got busy with other FOSS obligations, sorry.

**Comment by zmsmith** [comment]
Thanks! Definitely no need to apologize. Thank you for all the time it takes to build/maintain FOSS.
