### ISSUE TITLE
How to disable logging?

### ISSUE THREAD

**Issue by PixelSymbols** [hynek/structlog#545]
Could not find any info how to disable logging in docs

**Comment by hynek** [comment]
There's multiple ways; the easiest ist probably:

```python
def drop_all(*_, **_):
    raise structlog.DropEvent

structlog.configure(processors=[drop_all])
```

**Comment by PixelSymbols** [comment]
would be cool if you could just call `disable` and `enable` methods on logger and it would work.

**Comment by hynek** [comment]
Since structlog loggers are immutable, that is impossible. But you can do something like:

```python

def drop_all(*_, ed):
    if "disabled" in ed:
        raise structlog.DropEvent

    return ed


log = logger.bind(disabled=True)

…

log = logger.unbind("disabled")
```
