### ISSUE TITLE
How to configure CallsiteParameter so I can click on log lines in IDE and jump to the correct line in the file?

### ISSUE THREAD

**Issue by suiluj** [hynek/structlog#546]
Hello,

I am trying to configure my development console logger so that I can click on log lines in the output and vscode jumps to the correct line in the code.

At the moment I only have this configuration of the CallsiteParameterAdder:

```python
structlog.processors.CallsiteParameterAdder( 
    [
        structlog.processors.CallsiteParameter.PATHNAME,
        # structlog.processors.CallsiteParameter.FILENAME,
        # structlog.processors.CallsiteParameter.FUNC_NAME,
        structlog.processors.CallsiteParameter.LINENO
    ],
),
```

The problem is that this create a log line like this:

```
2023-09-04T16:29:37.814648Z [info     ] end of python run script.      lineno=209 module=python run script pathname=/workspaces/robot-framework-extension-develepoment/python-run-script/run.py service_name=robot framework
``` 

I would like to have a log line like this:

```
# taken from another issue traceback
File "C:/Users/admin/PycharmProjects/Backtrader Testing V1/main.py", line 782,

# or something similar like this
2023-09-04T16:29:37.814648Z File "/workspaces/robot-framework-extension-develepoment/python-run-script/run.py", line 209 [info     ] end of python run script.    service_name=robot framework

```

I do not understand how to create a custom field which consists of dynamic values.

**Comment by hynek** [comment]
Write a processor that removes those keys and formats them into the string you want.

Something like:

```python
def make_jumpable(_, __, ed):
    ed["location"] = f'File "{ed.pop("pathname")}", line {ed.pop("lineno")}'
    return ed
```

**Comment by suiluj** [comment]
Ah thanks! Now I checked out the other processors and understood how processor classes work.

I created a minimal example which works in vscode. vscode also seems to support the format `filepath:linenumber` for hyperlinks.

I also noticed that it is possible to only use the filename instead of the full file path. Strangely in vscode the jump to line number link text works even for line breaks when using the short version (only filename not file path). But it does not work for line breaks in the long version with the full path. At least on my setup.

Here is my example in case someone is interested:

```python
import logging
import structlog

from structlog.typing import EventDict, WrappedLogger


class LogJump:
    def __init__(
        self,
        full_path: bool = False,
    ) -> None:
        self.full_path = full_path

    def __call__(
        self, logger: WrappedLogger, name: str, event_dict: EventDict
    ) -> EventDict:
        if self.full_path:
            file_part = "\n" + event_dict.pop("pathname")
        else:
            file_part = event_dict.pop("filename")
        event_dict["location"] = f'"{file_part}:{event_dict.pop("lineno")}"'

        return event_dict


structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.StackInfoRenderer(),
        structlog.dev.set_exc_info,
        structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M:%S", utc=False),
        structlog.processors.CallsiteParameterAdder(
            [
                # add either pathname or filename and then set full_path to True or False in LogJump below
                # structlog.processors.CallsiteParameter.PATHNAME,
                structlog.processors.CallsiteParameter.FILENAME,
                structlog.processors.CallsiteParameter.LINENO,
            ],
        ),
        LogJump(full_path=False),
        structlog.dev.ConsoleRenderer(),
    ],
    wrapper_class=structlog.make_filtering_bound_logger(logging.NOTSET),
    context_class=dict,
    logger_factory=structlog.PrintLoggerFactory(),
    cache_logger_on_first_use=False,
)
log = structlog.stdlib.get_logger()

log.info("Hi!", asdf="asdf", fdsa=123456789, abcdefghijklmnopq="987654321")
```

My preferred version would be an extension to the `dev.ConsoleRenderer()`. I will try to adjust the renderer so the `filename:linenumber`(or `filepath:linenumber`) information gets between the timestamp and log level. Then we would "save" space in the console output because we do not use an additional attribute key like "location". Also the file name and line number would be at the same position every time even when the attributes get sorted.

I am still not sure what would be the most elegant way to add this information to the dev console though.

**Comment by hynek** [comment]
I believe this is solved from my side.
