### ISSUE TITLE
Please add documentation for how to configure logging to standard error

### ISSUE THREAD

**Issue by fsc-eriker** [hynek/structlog#551]
I was completely flabbergasted to discover that `structlog` logs to standard output by default. I can understand that this makes sense for a framework which primarily gets used in services which don't normally print data to standard output, but I still found it incredible.

My specific use case is a module which gets imported by a server framework. Whilst developing the module, I run it standalone on the command line, with JSON output to standard output. Obviously, adding `structlog` debugging to the mix ruins this scenario thoroughly.

Making matters worse, I was unable to find out from the documentation how to override this.

Lucky for me, https://github.com/hynek/structlog/issues/525 contains a snippet which works just fine.

```
structlog.configure(logger_factory=structlog.PrintLoggerFactory(sys.stderr))
```

I wish this was more discoverable from the module's official documentation. Searching for "stderr" within the doc pages retrieved nothing particularly useful.

**Comment by hynek** [comment]
I have added [a recipe](https://www.structlog.org/en/latest/recipes.html#switching-console-output-to-standard-error). I would like to note, though, that logging to standard out is part of https://12factor.net/logs, so maybe "incredible" is a bit of a strong word.
