### ISSUE TITLE
question/feature request: Adjustable width in rich_traceback / Passing options to rich

### ISSUE THREAD

**Issue by jvacek** [hynek/structlog#555]
My file paths are quite long, and rich_traceback wraps lines. This breaks the link functionality in terminals, which allow me to directly jump to the file and the line where an exception happened.
<img width="744" alt="image" src="https://github.com/hynek/structlog/assets/1302278/d995319c-e431-4cc1-a72e-deed988ce59f">
_(Instead of being pointed to the file+line, I'm being pointed to the folder above)_

The normal traceback allows me to open these long paths directly
<img width="1101" alt="image" src="https://github.com/hynek/structlog/assets/1302278/12963ee3-ee06-425c-8c8a-4fc6bb2286c0">

It would be nice if there was a way to keep this feature even in the pretty ones, even if the terminal's width is less than the length of the path (like below)
<img width="851" alt="image" src="https://github.com/hynek/structlog/assets/1302278/4bf59cb0-78e5-4d86-8441-078253b4a735">

----

Alternatively, it would be nice if there was a way to pass some options to `rich.console` directly

- https://rich.readthedocs.io/en/stable/console.html#soft-wrapping

**Comment by hynek** [comment]
Can you please check if https://github.com/hynek/structlog/pull/549 does everything you need
