### ISSUE TITLE
Changes to behavior of `runtime_checkable()` in py 3.12

### ISSUE THREAD

**Issue by peterschutt** [hynek/structlog#560]
I came across this - not  sure if you'd consider it a bug but hopefully worth bringing to your attention.

We had some code that tries to handle multiple logging libraries which was essentially doing this:

```py
from structlog import get_logger
from structlog.types import BindableLogger


logger = get_logger()

if isinstance(logger, BindableLogger):
    ...
```
The `isinstance()` check is `True` for python versions <3.12, and `False` on 3.12.

This is due to a change in the way that `typing.runtime_checkable()` works:

> Changed in version 3.12: The internal implementation of [isinstance()](https://docs.python.org/3/library/functions.html#isinstance) checks against runtime-checkable protocols now uses [inspect.getattr_static()](https://docs.python.org/3/library/inspect.html#inspect.getattr_static) to look up attributes (previously, [hasattr()](https://docs.python.org/3/library/functions.html#hasattr) was used). As a result, some objects which used to be considered instances of a runtime-checkable protocol may no longer be considered instances of that protocol on Python 3.12+, and vice versa. Most users are unlikely to be affected by this change.

[`inspect.getattr_static()`](https://docs.python.org/3/library/inspect.html#inspect.getattr_static) doesn't call `__getattr__`, which means it doesn't see the proxied attributes of the underying bound logger.

I think the difference might be that the `_context` attribute doesn't exist on the proxy.

https://github.com/hynek/structlog/blob/d95197c9a02b59139605515a0939d690e87550a2/src/structlog/typing.py#L121-L130

**Comment by hynek** [comment]
The vanilla `get_logger` returns an Any, I suspect that's more likely to be the issue? See also https://www.structlog.org/en/stable/typing.html

**Comment by peterschutt** [comment]
This isn't a static typing issue. It is a runtime issue on python 3.12 where the `BindableLogger` protocol (which is marked `@runtime_checkable`) returns `False` on an `isinstance()` check against an instance of `BoundLoggerLazyProxy`.

**Comment by hynek** [comment]
Ah yes sorry ugh this is ugly I'll see what we can do.

**Comment by peterschutt** [comment]
Thanks @hynek!

**Comment by hynek** [comment]
This should be now fixes – please lmk if you run into other similar issues!

Is this issue something that blocks you?
