### ISSUE TITLE
WriteLogger log rotation

### ISSUE THREAD

**Issue by mssalvatore** [hynek/structlog#562]
What's the recommended way to handle log rotation in structlog? Should something other than Writelogger be used? Is there an established pattern?

**Comment by hynek** [comment]
Generally I consider it bad form to reinvent log rotation in Python. As https://www.structlog.org/en/latest/logging-best-practices.html writes, it's best to write to stdout and then use standard tools for catching & processing log files. For UNIX-like OS that would be syslogd & [logrotate](https://www.structlog.org/en/latest/logging-best-practices.html).

If you're in an environment that can't use any of that, you always have the escape hatch to log out using [standard library logging](https://www.structlog.org/en/stable/standard-library.html#rendering-within-structlog) that has log rotation. But I would consider it only the last resort.

**Comment by mssalvatore** [comment]
Got it. Thanks.
