### ISSUE TITLE
logs reader 

### ISSUE THREAD

**Issue by d33m00n** [hynek/structlog#563]
Hello! Thank you for the excellent project

What do you guys use to read and analyze logs?

**Comment by hynek** [comment]
There is no standard answer to that – people running logs in production usually want a centralized log storage. Self-hosted ones are usually ELK or Graylog (see https://www.structlog.org/en/latest/logging-best-practices.html#centralized-logging) – but there's also (very expensive) hosted versions. I'm not aware of local tools.
