### ISSUE TITLE
Structlog does not work with tqdm

### ISSUE THREAD

**Issue by yauhen-sobaleu** [hynek/structlog#564]
Hello! Is there a way to befriend `structlog` logging with `tqdm`? 

```python
import structlog
import tqdm
from tqdm.contrib.logging import logging_redirect_tqdm

import structlog
import tqdm

def get_logger() -> structlog.stdlib.BoundLogger:
    structlog.configure(
        processors=[
            # show log level
            structlog.stdlib.add_log_level,
            # add time to every log entry
            structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M.%S"),
            # render logs in pretty format (unstructured)
            structlog.dev.ConsoleRenderer(),
            
        ],
    )

    return structlog.get_logger()


logger = get_logger()

if __name__ == '__main__':
    with logging_redirect_tqdm(loggers=[logger]):
        with tqdm.tqdm(total=len(range(10))) as pbar:
            pbar.update(1)

AttributeError: 'BoundLoggerFilteringAtNotset' object has no attribute 'handlers'
```

**Comment by hynek** [comment]
It’s been a while since I used tqdm, but doesn’t it have some kind of print/stdout redirect? You seem to be using their std lib logging integration that is only gonna work if you also use structlog’s. It’s possible it even works if you do nothing because the latest structlog versions use print() by default.

**Comment by yauhen-sobaleu** [comment]
I am trying to solve the issue with Python `print` function not showing logs in real time (as opposed to prints done via `logging` module) using Argo Workflows: https://github.com/argoproj/argo-workflows/issues/3169

The only place I invoke `print` is tqdm progress bar. 

Thus I tried to pipe tqdm output to BoundLogger but I have this weird error.

**Comment by yauhen-sobaleu** [comment]
It seems tqdm just cannot be used in cloud logging: https://github.com/tqdm/tqdm/issues/1319.
Is it still true?

**Comment by yauhen-sobaleu** [comment]
Ok I found exactly what I need! Setting `TQDM_POSITION` env variable to `-1` does the job!

**Comment by gsakkis** [comment]
To save the next person that lands here the 1+ hour it took me to figure it out, to make structlog and tqdm work together:
1. Call `structlog.stdlib.recreate_defaults()`.
   - Optionally pass as `log_level` the `level` you'd pass in `logging.basicConfig`.
3. Get a logger from `structlog.get_logger()`.
4. Wrap your code that uses `tqdm` in a `with logging_redirect_tqdm()` block.   
    - **Important**: don't pass the structlog logger in it; `logging_redirect_tqdm(loggers=[logger])` doesn't work. 

Complete example:
```python
import logging
import time

import structlog
import tqdm
from tqdm.contrib.logging import logging_redirect_tqdm

structlog.stdlib.recreate_defaults(log_level=logging.INFO)
logger = structlog.get_logger()


def main() -> None:
    with logging_redirect_tqdm():
        for i in tqdm.trange(9):
            time.sleep(0.2)
            if i % 2 == 0:
                logger.debug(i)
            if i % 3 == 0:
                logger.info(i)


if __name__ == "__main__":
    main()
```

![Image](https://github.com/user-attachments/assets/61868f61-2352-4a87-9ebf-4597e53c4326)

**Comment by hynek** [comment]
Thanks! I still feel that since we've switched the default logger to using `print()` in 22.1.0 there should be a simpler way, but I currently have no time to investigate it any further. 😬
