### ISSUE TITLE
'LoggerFactory' prevents structlog from logging DEBUG and INFO level logs

### ISSUE THREAD

**Issue by kindaway** [hynek/structlog#574]
```
import logging

import structlog


def log() -> structlog.stdlib.BoundLogger:
    """Get logger configured to output JSON lines to stdout"""
    timestamper = structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M:%S", utc=False)
    structlog.configure(
        processors=[
            structlog.stdlib.add_log_level,
            structlog.stdlib.PositionalArgumentsFormatter(),
            timestamper,
            structlog.processors.format_exc_info,
            structlog.processors.JSONRenderer()
        ],
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True,
    )
    return structlog.get_logger("test_name")


log().info("test_log")
```

Hello! I'm trying to configure structlog to print logs in json format. However when I `set logger_factory` to `structlog.stdlib.LoggerFactory()` it stops printing any logs with DEBUG and INFO level despite not setting any other options (the code above completely reproduces the issue). I'm not sure if this is expected.

On a related note, I tried to add a logger name to the  output. In documentation it is said, that using LoggerFactory makes structlog deduce a logger name (or take it from 1st arg of `get_logger`) and add it to the event_dict. However it doesn't do it even If I add processor `add_logger_name` to the chain. 
Am I not getting something right in the process of configuring structlog XD ?

**Comment by hynek** [comment]
If you configure structlog to use stdlib for output, stdlib has the last say what levels are logged and which not.

If you want to have the logger name as part of the event dict you need `structlog.stdlib.add_logger_name`.
