### ISSUE TITLE
Any examples for configuration to use in Azure Functions

### ISSUE THREAD

**Issue by jashan05** [hynek/structlog#575]
Hello Team,

I am trying to use structlogs to have a structure in my azure function apps. Somehow, in logs of Azure Functions app i dont see any logs after the configuration. Configuration is as follows:

```
import logging
import structlog

structlog.configure(
    wrapper_class=structlog.make_filtering_bound_logger(logging.INFO),
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.format_exc_info,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer()
                                ])
logger = structlog.get_logger()
```

When i try to use any logging statement, it just doesnt appear in Monitor logs of azure functions. Any examples or guidance will be helpful.

Thanks 
Jashan

**Comment by hynek** [comment]
I'm sorry but I have no idea about Azure Functions. You're gonna have to tell us where/how they expect their logs.
