### ISSUE TITLE
"exception" is a possible log level from processors.add_log_level since 23.3.0

### ISSUE THREAD

**Issue by kimsappi** [hynek/structlog#584]
structlog.processors.add_log_level used to report the level of "exception" events as "error", but since 23.3.0 with certain configurations it's possible to get "exception" instead:

```sh
$ pip3 install structlog==23.2.0 && python3 main.py
{'exc_info': True, 'event': 'test', '_record': <LogRecord: root, 40, 223, "{...}">, '_from_structlog': True, 'level': 'error'}

$ pip3 install structlog==23.3.0 && python3 main.py
{'exc_info': True, 'event': 'test', '_record': <LogRecord: root, 40, 217, "{...}">, '_from_structlog': True, 'level': 'exception'}
```

I wonder if this is intentional, since it's not very clearly listed in the changelog. There is "stdlib: structlog.stdlib.BoundLogger.exception()'s handling ofLogRecord.exc_info is now set consistent with logging." but I don't think this change falls into that category.

It seems to be reliant on `wrapper_class=structlog.stdlib.BoundLogger`.

Example code:
```python
import logging.config
import structlog

structlog.configure(
    processors=[
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
)

logging_config = {
    "version": 1,
    "formatters": {
        "json": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processors": [
                structlog.processors.add_log_level,
            ],
        }
    },
    "handlers": {
        "json": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "root": {
        "handlers": ["json"],
    },
}
logging.config.dictConfig(logging_config)
```

**Comment by mvallebr** [comment]
+1 - I was going to open an issue and found this existing one. My test just failed today and I had to revert to 23.2.0 because of this.

**Comment by hynek** [comment]
Yeah this is a result of #572 – is there anything you'd like to happen except of a better changelog entry?

**Comment by kimsappi** [comment]
The `levelname` for CPython `logging.Logger.exception()` still seems to be `"error" (or "ERROR")`:
```python
Python 3.12.1 (main, Dec 19 2023, 20:14:15) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig(format='%(levelname)s: %(message)s')
>>> logging.getLogger('').exception('test')
ERROR: test
NoneType: None
```
At least my expectation would be that provided methods provide the same result as CPython. If you agree, I can try to work on a PR.

The seemingly obvious solution would be:
* add a mapping like already exists for `"warn"` -> `"warning"` or
* try to find `method_name` from `NAME_TO_LEVEL` and use the corresponding name from `LEVEL_TO_NAME`
  * this may face resistance from people who have defined custom level names at the same numeric values as existing levels, if this kind of behaviour used to work

**Comment by hynek** [comment]
Wouldn't that basically undo #572?

I'm trying to wrap my head around it – it seems like it should call Logger.exception, but then transform the error log level before logging? 😳

**Comment by hynek** [comment]
cc @bcdickinson

**Comment by kimsappi** [comment]
I wouldn't say it undoes the previous improvements. This would mostly be an aesthetic change to the displayed log level only, making it reflect built-in `logging` more closely. Python doesn't treat "exception" as a separate log level, but mostly as a shortcut for `logger.error('', exc_info=True)` (in structlog terms). (I have no idea about the details, but that's what it looks like from the outside.)

https://docs.python.org/3/library/logging.html 

> levelname | %(levelname)s | Text logging level for the message ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL').

> exception(msg, *args, **kwargs)
> > Logs a message with level ERROR on this logger.

As for why it may make a difference: people may have existing integrations like searches or filters for metrics or export/storage that are based on the level name.

**Comment by hynek** [comment]
yes: https://github.com/python/cpython/blob/0c3455a9693cfabcd991c4c33db7cccb1387de58/Lib/logging/__init__.py#L1537-L1541

and that's what structlog did previously. But there seems to be some edge cases outlined in #572 re interop between structlog and stdlib.

to be clear, I'm not arguing for breakage here; I'm just trying to find a way to make both parties happy.

**Comment by bcdickinson** [comment]
Thanks for the @ @hynek - sorry that my changes are causing problems for people. 

Changing the reported log level wasn't an intended consequence of my changes on #572 and the fact that it's sometimes showing up as `"exception"` definitely seems like a bug. If there's a way to fix the reported log level and keep the fix to the stdlib-managed `exc_info` that would be ideal.

I'm not sure what the solution should be. It seems like just adding a quick fixup to `add_log_level` like there is for `"warning"`/`"warn"` already might be enough, but I'm not sure that's the correct way to sort it.

**Comment by hynek** [comment]
fixed by #586

**Comment by gsinghsfdc** [comment]
@hynek when doing `capture_logs` in a test, this still shows up as `exception` instead of `error`. Is the plan to keep that as is or was it missed in originally closing this issue?

**Comment by eugenenelou** [comment]
The `capture_logs` problem is a real bug. There is no reason that we should expect something to be different in tests.
