### ISSUE TITLE
`structlog.get_context` breaks from 23.2.0 to 23.3.0

### ISSUE THREAD

**Issue by val-melev** [hynek/structlog#585]
in version `23.2.0` we get
```
$ logger = get_logger(context="a")  
$ get_context(logger)  
{'context': 'a'}
```

in version `23.3.0` we get
```
$ logger = get_logger(context="a")  
$ get_context(logger)  
{}
```

is it wrong to assume stability for `get_context`? Doesn't seem like it'd be internal function. It's also not mentioned in the changelog.

**Comment by hynek** [comment]
hrhm side-effect of #561 – hope it's the only one.

fixed by https://github.com/hynek/structlog/commit/813bc14a2d0fdd0ea539a07ec44e134a6be7b0aa
