### ISSUE TITLE
Add fallback when loading Protocol

### ISSUE THREAD

**Issue by gsemet** [hynek/structlog#588]
Please add a fallback to `typing_extensions` when importing `Protocol`, on old system (ubuntu 18 with python 3.7) i have an exception:

```
File "/root/.shiv/nestor.pyz_01HMA1DW9Y2TXABE7GPJ5DBXCX/site-packages/structlog/typing.py", line 18, in <module>
    from typing import (
ImportError: cannot import name 'Protocol' from 'typing' 
```

Example of fallback:
```python
try:
    from typing import Protocol
except:
    from typing_extensions import Protocol
```

Also i do not understand why forcing the loading of `structlog.typing`, if we are not under `typing.TYPE_CHECKING`, this is useless to do it.

**Comment by hynek** [comment]
structlog has dropped Python 3.7 support in 23.2.0 and that's where the fallback was removed. I'm not entirely sure how you managed to install it anyways, given the metadata says `requires-python = ">=3.8"`.
