### ISSUE TITLE
Question: how to make timestamps be time-since-application-started?

### ISSUE THREAD

**Issue by petemounce** [hynek/structlog#589]
I'm getting to grips with structlog; it has been a great experience due to the fantastic documentation.

I would like to configure my application so that, in dev, timestamps are rendered as the time since the application started, as `{seconds}.{nano}`.

Is there a readily achievable way that can be done...?

**Comment by hynek** [comment]
Readily as in built-in: no. Readily as in possible: absolutely.

Assuming configuration time is precise enough for how long the app is running, you would write an own processor that does something like this:

```python
import time

class RunningForAdder:
    def __init__(self):
        self.running_since = time.perf_counter()

    def __call__(self, _, __, ed):
        ed["running_for"] = time.perf_counter() - self.running_since
        return ed
```
