### ISSUE TITLE
CodeCov no longer working on travis

### ISSUE THREAD

**Issue by Callek** [hynek/structlog#61]
Since you did coverage run --parallel you lost the coverage with travis, because travis is not run on the same machine, so you're not actually getting the coverage from all runs, and thus coveralls is not finding the coverage report itself.

Last cset from coveralls is 85bff22.

c.f. https://travis-ci.org/hynek/structlog/jobs/86011492

**Comment by hynek** [comment]
Thanks!  Fixed by cea0a69.
