### ISSUE TITLE
How to configure different loggers separately?

### ISSUE THREAD

**Issue by Dankko0w0** [hynek/structlog#610]
structlog.configure() seems to be the global setting. I need to create two different loggers with different settings, like:
```
logger1 = structlog.get_logger()
logger2 = structlog.get_logger()

logger1.configure(
    processors=[do_something1],
)
logger2.configure(
    processors=[do_something2],
)
```
Hope someone can give me the right solution, thanks!

**Comment by hynek** [comment]
https://stackoverflow.com/a/78259508/476759
