### ISSUE TITLE
structlog+graylog

### ISSUE THREAD

**Issue by ghazalmohseni7** [hynek/structlog#617]
hi there , im using structlog for logging my project and now I want to add a log reviewer. can structlog be integrated with graylog ? or elk? i didn't find anything useful on internet . thank you

**Comment by hynek** [comment]
We integrate structlog with ELK as documented in <https://www.structlog.org/en/stable/logging-best-practices.html#centralized-logging>.

You should be able to do the same thing with Graylog and there's been tighter integrations like https://github.com/magenta-aps/structlog-gelf but I don't use Graylog so I can't speak to their merit.
