### ISSUE TITLE
Advantages over a database?

### ISSUE THREAD

**Issue by richardasaurus** [hynek/structlog#63]
I saw this and was wondering what's the advantage of using structlog instead of simply storing logs in a database table?

**Comment by hynek** [comment]
structlog is strictly not about storage of log entries but about *transport*.  And only within your own application.  It’s a tool to write structured log entries.  Where you save them (in-memory list, file, Elasticsearch, Postgres…) is completely up to you.

**Comment by richardasaurus** [comment]
:+1:
