### ISSUE TITLE
tmp_bind cleanup in the face of exceptions

### ISSUE THREAD

**Issue by Tinche** [hynek/structlog#64]
The ```tmp_bind``` context manager clean-up logic (the code after the yield) isn't protected by a finally clause, so it doesn't get executed when an exception is raised.

```
>>> from structlog import wrap_logger, PrintLogger
>>> from structlog.threadlocal import tmp_bind, wrap_dict
>>> logger = wrap_logger(PrintLogger(),  context_class=wrap_dict(dict))
>>> try:
...  with tmp_bind(logger, x=5) as tmp_logger:
...   logger = logger.bind(y=3)
...   tmp_logger.msg('event')
...   raise ValueError()
... except:
...  pass
...
x=5 event='event' y=3
>>> logger.msg('event')
x=5 event='event' y=3
```

I would say the expected behavior is for the last logger to just emit ```event='event'```.

If you agree, it's a simple fix that I could contribute.

**Comment by hynek** [comment]
Sounds reasonable to me!  Cleanup should happen in any case.

**Comment by hynek** [comment]
(also hurry up if you want to see it in 16.0.0 :))

**Comment by Tinche** [comment]
Will do as soon as I get some free time (today or tomorrow) ;)

**Comment by Tinche** [comment]
Dealt with in https://github.com/hynek/structlog/pull/65.
