### ISSUE TITLE
FilteringBoundLogger fatal method logs with error level instead of critical

### ISSUE THREAD

**Issue by raqbit** [hynek/structlog#640]
When using `make_filtering_bound_logger`, one of the pre-created `BoundLoggerFilteringAt<level>` instances is used. These instances have the `fatal` & `afatal` aliases mapped[^1] to `error` & `aerror` respectively, even though the Python `fatal` alias is mapped to `critical` in other loggers (including the Python standard library).

(Side note: After diving into structlog internals to figure out why my fatal logs were not going through the processor chain, I figured out that use of the `fatal` method is discouraged[^2])

[^1]: https://github.com/hynek/structlog/blob/87ac2babbd193b3836c5d32c9fa81510c28b82e0/src/structlog/_native.py#L205
[^2]: https://github.com/python/cpython/blob/a8be8fc6c4682089be45a87bd5ee1f686040116c/Lib/logging/__init__.py#L1565

----

```
import structlog, logging
print(structlog.__version__) # 24.4.0
structlog.configure(wrapper_class=structlog.make_filtering_bound_logger(logging.CRITICAL))
structlog.get_logger().critical("something went critically wrong") # [critical ] something went critically wrong
structlog.get_logger().fatal("something went fatally wrong") # Log filtered
```

**Comment by hynek** [comment]
yeah while working on #670, I noticed fatal is not mentioned in the logging docs [**at all**](https://docs.python.org/3.13/library/logging.html).

Since people shouldn't be using it and moving it to critical means that the only side effect are potentially more logs, I think this is fine to change. → #677
