### ISSUE TITLE
A proper way to defer rendering log message?

### ISSUE THREAD

**Issue by MasterGroosha** [hynek/structlog#644]
Hello. First of all, thank you so much for this awesome library, and pardon me for more theoretical question. As there is no "Discussions" tab, going to ask this here.

In the documentation, the author says:
<img width="862" alt="image" src="https://github.com/user-attachments/assets/e4972434-11b1-423b-92a8-ebc196e71093">

Here it is implied, that if you use string interpolation instead of f-strings, this would defer rendering text and if log level is higher that the caller's, then text will not be rendered, possibly saving some time on calling expensive function.

However, this is not really like that, as simply using string interpolation will still make the call:
```python
import logging


def simple_func():
    print("Called!")
    return 5


logging.basicConfig(level=logging.WARNING)

logging.debug(f"Running with number {simple_func()}")
logging.debug("Running with number %s", simple_func())
```

And it is the same with structlog:
```python
import logging

import structlog
from structlog import WriteLoggerFactory
from structlog.types import FilteringBoundLogger


def get_processors() -> list:
    processors = [
        structlog.processors.TimeStamper(),
        structlog.processors.add_log_level,
        structlog.dev.ConsoleRenderer(),
    ]
    return processors


def get_structlog_config() -> dict:
    min_level = logging.INFO

    return {
        "processors": get_processors(),
        "cache_logger_on_first_use": True,
        "wrapper_class": structlog.make_filtering_bound_logger(min_level),
        "logger_factory": WriteLoggerFactory()
    }


def simple_func():
    print("Called!")
    return 5


logger: FilteringBoundLogger = structlog.get_logger()
structlog.configure(**get_structlog_config())


logger.debug(f"Running with number {simple_func()}", extra="extra_f_string")
logger.debug("Running with number %s", simple_func(), extra="extra_interpolate")
```

In both examples, there will be two "Called!" strings in the console.

Am I missing something? Is there any other configuration needed to avoid rendering log text when overall log level is higher? Also, what's the analogue of "[isEnabledFor](https://docs.python.org/3/howto/logging.html#optimization)" in structlog?

Thanks in advance!

**Comment by hynek** [comment]
What you're missing is that normal Python code has no control over over how its function argument values are created. structlog only gets the result of your function call and doesn't know it was created by calling a function.

What the delay means is that the string isn't rendered, based on those arguments unless necessary.

---

The best I can offer you off-cuff is setting some key to a special value and writing a processor that executes your expensive function based on that.

**Comment by trim21** [comment]
you can do this:


```python
logger = get_logger()


class LazyValueLogLine:

    def __init__(self, msg, fn):
        self.msg = msg
        self.fn = fn

    def __repr__(self):
        return self.msg % self.fn()


logger.debug(LazyValueLogLine("hello %s", lambda: "world"))
```

**Comment by trim21** [comment]
OK, I just find that a existing library for this: https://github.com/o3bvv/lazy-string

```python
import structlog
from lazy_string import LazyString


log = structlog.get_logger()


def make_foo() -> str:
    return "foo"


log.info("hello %s", LazyString(make_foo)) # 2024-09-23 00:59:12 [info     ] hello foo
```

**Comment by ashb** [comment]
@hynek stdlib has `isEnabledFor(level)` that we use like this https://github.com/apache/airflow/blob/c1d44f556956d08a137613de81cd4b6a3e2162c3/airflow/dag_processing/manager.py#L1307-L1317

```python
        if self.log.isEnabledFor(logging.DEBUG):
            for processor in self._processors.values():
                self.log.debug(
                    "File path %s is still being processed (started: %s)",
                    processor.file_path,
                    processor.start_time.isoformat(),
                )

            self.log.debug(
                "Queuing the following files for processing:\n\t%s", "\n\t".join(files_paths_to_queue)
            )
```

Would you be open to adding an `is_enabled_for` method onto FilteringBoundLogger? Right now I couldn't find a way at runt time to tell what level a logger is enabled for.

**Comment by hynek** [comment]
Sure, the config should be somehow exposed.
