### ISSUE TITLE
Test formatting when utc is false

### ISSUE THREAD

**Issue by python-mutation-testing** [hynek/structlog#661]
I was performing some mutation testing on structlog when I noticed that the MaybeTimeStamper with the false utc argument is not tested.
For example:

```python
mts = MaybeTimeStamper(utc=False, fmt="iso")
```
This causes the formatting in cases where the utc is false not to be tested.
I'll add a test case for it in a pull request.

**Comment by hynek** [comment]
utc=False is just passed into TimeStamper which tests the case:

https://github.com/hynek/structlog/blob/f3e6fdee0658e9c6ab89aaa8823abe0d78e49b3a/tests/processors/test_renderers.py#L396-L405
