### ISSUE TITLE
Get pure JSON output?

### ISSUE THREAD

**Issue by tejasmanohar** [hynek/structlog#68]
```python
import structlog
import logging
import sys

def levelMapper(log, method, message):
    if (method == 'critical'):
        message['level'] = 'fatal'
    return message

def create(name, level = 'INFO'):
    # set minimum log level
    logging.basicConfig(level=getattr(logging, level))

    structlog.configure(
        processors=[
            structlog.stdlib.filter_by_level,
            structlog.stdlib.add_log_level,
            levelMapper,
            structlog.stdlib.PositionalArgumentsFormatter(),
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,
            structlog.processors.JSONRenderer()
        ],
        context_class=dict,
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True,
    )

    log = structlog.get_logger()
    log = log.bind(program=name)
    log.debug('hi', { 'a': 'b' })

create('test', 'DEBUG')
```
results in
```
DEBUG:__main__:{"level": "debug", "program": "test", "event": "hi"}
```

How do I get pure JSON output? The `DEBUG:__main__` is throwing off my parsing atm.

**Comment by hynek** [comment]
That's coming from the standard library.  The configuration presented at the bottom of http://www.structlog.org/en/stable/standard-library.html should take care of that.

**Comment by tejasmanohar** [comment]
Hey @hynek! I did see that example, but I wasn't able to get it work.

```python
import structlog
import logging
import sys

structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.JSONRenderer()
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

handler = logging.StreamHandler(sys.stdout)
root_logger = logging.getLogger()
root_logger.addHandler(handler)

root_logger.info('hi', { 'xyz': 123 })
```

Executing this logs nothing for me to STDOUT (afaict), but when I change `info` to `warn`, I just see `hi`. That's still not what I was expecting since it isn't pure JSON output.

Let me know what I'm missing here! Thanks in advance :D

**Comment by hynek** [comment]
You’re not supposed to use the root_logger for anything more than configuration.  It’s not a structlog logger.  As for info/debug: use `root_logger.setLevel()` to set it the minimal level of your choice.

**Comment by tejasmanohar** [comment]
@hynek Ah, I see. Still a bit confused though. Assuming you want pure JSON STDOUT and you create the root logger for configuration as done in my example above, what logger do you use to actually print ("It’s not a structlog logger" -> which one is?)? Thanks again 👏

**Comment by hynek** [comment]
You’re configuring structlog to use the logging module from the standard library for output (as opposed to say the PrintLogger that is used by default).

The logging module needs to be configured separately as it will add some junk by default as you noticed.  You achieve that by getting the root logger and configure it.

```python
logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
    stream=sys.stdout,
)
```

should work too.

**Comment by tejasmanohar** [comment]
makes sense. thanks a ton!
