### ISSUE TITLE
Pure JSON output w/o StdLib

### ISSUE THREAD

**Issue by tejasmanohar** [hynek/structlog#69]
@hynek In https://github.com/hynek/structlog/issues/68, you mentioned that it's possible to get pure JSON output by using the logger provided by the `logging` module of Python's standard library. I got this working but noticed that when I set the log level to `DEBUG`, I also see log outputs from 3rd-party libraries I'm using. Is there a way to apply transformations or filter these logs through structlog? Better yet, is there a way to get pure JSON output without using the stdlib logger so that I don't change the minimum log level there & packages I use don't start logging?

**Comment by hynek** [comment]
- JSONifying non-structlog entries is discussed in the FAQ: http://www.structlog.org/en/stable/faq.html
- you can use the PrintLogger and leave out stdlib integration altogether

**Comment by wimglenn** [comment]
Link above is broken.  I guess this is the next best place: http://www.structlog.org/en/stable/standard-library.html#rendering-using-logging-based-formatters
