### ISSUE TITLE
Apply positional arguments to output

### ISSUE THREAD

**Issue by tejasmanohar** [hynek/structlog#70]
http://www.structlog.org/en/stable/api.html#structlog.stdlib.PositionalArgumentsFormatter

Hmm, is there a formatter for applying the 2nd argument (dict) to the JSON output? For example,

`log.info('hi', { 'xyz': 123 })`
`{ "event": "hi", "xyz": 123 }`

**Comment by hynek** [comment]
that’s not a thing for the formatter.  the positional args formatter is to allow format strings in your event.  something you really shouldn’t do, it’s in there to make structlog easier to drop in into existing code bases.

either you write an own logger that handles that case: http://www.structlog.org/en/stable/custom-wrappers.html

or you simple write `log.info('hi', xyz=123)` or `log.info('hi', **{ 'xyz': 123 })`
