### ISSUE TITLE
AttributeError: 'PrintLogger' object has no attribute 'isEnabledFor'

### ISSUE THREAD

**Issue by glasserc** [hynek/structlog#71]
Trying to setup structlog after it has already logged a message can put it into a strange state where logging messages causes exceptions.

```python
import structlog
log = structlog.get_logger()
log.msg('greeted', whom='world', more_than_a_string=[1, 2, 3])

from structlog import get_logger, configure
configure(
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    # Setup logger output format.
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.processors.format_exc_info,
    ])

log.warn("Hey, this isn't cool")
```

Output:

```
whom='world' more_than_a_string=[1, 2, 3] event='greeted'
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    log.warn("Hey, this isn't cool")
  File "/home/ethan/Jobs/Mozilla/tmp/structlog-bug/.venv/lib/python2.7/site-packages/structlog/stdlib.py", line 73, in warning
    return self._proxy_to_logger('warning', event, *args, **kw)
  File "/home/ethan/Jobs/Mozilla/tmp/structlog-bug/.venv/lib/python2.7/site-packages/structlog/stdlib.py", line 119, in _proxy_to_logger
    **event_kw)
  File "/home/ethan/Jobs/Mozilla/tmp/structlog-bug/.venv/lib/python2.7/site-packages/structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/home/ethan/Jobs/Mozilla/tmp/structlog-bug/.venv/lib/python2.7/site-packages/structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/home/ethan/Jobs/Mozilla/tmp/structlog-bug/.venv/lib/python2.7/site-packages/structlog/stdlib.py", line 327, in filter_by_level
    if logger.isEnabledFor(_NAME_TO_LEVEL[name]):
AttributeError: 'PrintLogger' object has no attribute 'isEnabledFor'
```

This makes it difficult to log messages during startup, because logging isn't configured yet, and if we log messages before we configure, later log messages will just crash and burn with this exception.

**Comment by tarekziade** [comment]
`get_logger` does more than returning an object. this will work:

```python
import structlog
log = structlog.get_logger()
log.msg('greeted', whom='world', more_than_a_string=[1, 2, 3])

from structlog import get_logger, configure
configure(
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    # Setup logger output format.
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.processors.format_exc_info,
    ])

log = structlog.get_logger()
log.warn("Hey, this isn't cool")
```

**Comment by tarekziade** [comment]
maybe a better semantic would be to let us pass a logger object to `configure` or have `configure` send back a new logger object ?

**Comment by tarekziade** [comment]
I found another solution that allows us to re-configure an existing logger instance

```python
import structlog

log = structlog.get_logger()
log.msg('greeted', whom='world', more_than_a_string=[1, 2, 3])

structlog.wrap_logger(log,
            logger_factory=structlog.stdlib.LoggerFactory(),
            wrapper_class=structlog.stdlib.BoundLogger,
            processors=[
                structlog.stdlib.filter_by_level,
                structlog.processors.format_exc_info])

log.info("Hey, this isn't cool")
```

**Comment by hynek** [comment]
Heh this is a funny one.

Let me explain first what exactly is happening here:

Because configuration usually happens after the call to `get_logger()`, `get_logger()` doesn’t return an actual logger.

Instead you get a lazy proxy that gets actualized once it is used for the first time: in this case by `log.msg('greeted', whom='world', more_than_a_string=[1, 2, 3])`.  After this call, `log` is an logger with default configuration.  If you leave it out, your example works too.

What’s puzzling to me tho is that the processors list within `log` gets modified by the call to configure (I’m guessing some mutable data fuckup by me) such that the wrapper_class doesn’t fit the processors list anymore and explodes.

***

IOW: don’t use a logger from `get_logger()` *before* configuration.  That will break in any case.  If you need to log before, use `wrap_logger()` which you already found. :)

I will definitely investigate what’s going on here but in this case structlog’s bug only exploded due to your bug. :)

**Comment by glasserc** [comment]
I think there are two problems. The first is that the PrintLogger is incompatible with `filter_by_level` because it doesn't provide an `isEnabledFor` method. For example, this still breaks:

```python
import structlog
from structlog import get_logger, configure
configure(
    # Setup logger output format.
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.processors.format_exc_info,
    ])

log = get_logger()
log.warn("Hey, this isn't cool")
```

The second is what @hynek was getting at, which is that the BoundLoggerLazyProxy created by `get_logger` gets mutated on *first* use, but only for *some* properties and not others. (Specifically, `processors` will be read from global state on every use, but a `_logger` attribute is set on the first use.) It would be nice to have some way to tell a BoundLoggerLazyProxy "hey, we just changed the config, clear your state and reinitialize on the next use". When we are ready to configure structlog, we could just call `log.reset()` or something. One ugly workaround is to unset `log._logger`, for example like this:

```python
import logging
logging.basicConfig(level=logging.WARN)
import structlog
log = structlog.get_logger()
log.msg('greeted', whom='world', more_than_a_string=[1, 2, 3])

from structlog import get_logger, configure
def renderer(logger, name, eventdict):
    return '{} {}'.format(name, eventdict)

configure(
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    # Setup logger output format.
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.processors.format_exc_info,
        renderer,
    ])

log._logger = None
log.warn("Hey, this isn't cool")
```

This works as expected. This would be nice because then our setup code could use the same global "log" variable as the rest of our application.

Using `wrap_logger` doesn't mutate the proxy in any way so it doesn't solve anything.

The only other alternative is for the setup code to just do a different kind of logging. For example, it could call get_logger on its own to get a new proxy, or use an underlying logging library, or just print stuff to the screen. This is of course unfortunate because you have to remember to use this second kind of logging when you are in certain parts of the codebase.

**Comment by hynek** [comment]
FWIW I don’t consider `PrintLogger`’s lack of support for stdlib APIs a problem.   `structlog.stdlib.filter_by_level` only works with stdlib loggers.  That API has simply no meaning outside the stdlib.  Failing silently only covers bugs (you can always write a wrapper around it that catches that problem).

*** 

You’re right that the problem is that the _logger gets cached after a first bind()  (that is implicit if you use the logger although the result is thrown away).  I think that can and should be removed.

***

`wrap_logger` solves insofar that you would use it explicitly to create a logger before logging is configured (I guess that’s what you meant by  “different kind of logging”).

**Comment by glasserc** [comment]
Great, I agree that we should stop caching the _logger attribute. I will try to write up a PR.

**Comment by tarekziade** [comment]
> FWIW I don’t consider PrintLogger’s lack of support for stdlib APIs a problem. 

I felt you wanted to make sure it stayed compatible, e.g. 
http://structlog.readthedocs.io/en/stable/standard-library.html#python-standard-library - e.g. "If you run into incompatibilities, it is a bug"

**Comment by hynek** [comment]
Yes, if you use the stdlib layer.

**Comment by hynek** [comment]
This is fixed indeed.  Thanks everyone for fruitful cooperation. :)

**Comment by glasserc** [comment]
Thanks! Do you know off the top of your head when I might see the fix in an official release of structlog? I'm just trying to decide whether I should get the workarounds merged into our own codebase, or if it would be easier to just wait.

**Comment by hynek** [comment]
I think I may cut a release before PyCon although there’s not much new stuff.

**Comment by Natim** [comment]
> I may cut a release before PyCon

That would be great.

**Comment by hynek** [comment]
https://pypi.python.org/pypi/structlog/16.1.0

**Comment by glasserc** [comment]
Yay, thanks!

**Comment by kalzoo** [comment]
To anyone else who finds this in the future, you'll also see this error when you use any `structlog.stdlib` processors with a `PrintLogger`, like so:

```python
        structlog.configure(
            logger_factory=structlog.stdlib.PrintLoggerFactory(),
            cache_logger_on_first_use=True,
            processors=[
                structlog.processors.StackInfoRenderer(),
                structlog.stdlib.filter_by_level, # will break
                structlog.stdlib.add_logger_name, # will break
                structlog.stdlib.add_log_level, # will break
                structlog.dev.set_exc_info,
                structlog.processors.format_exc_info,
                structlog.processors.JSONRenderer(sort_keys=True),
            ],
        )
```

That makes sense, of course, and is expected `structlog` behavior - just remove those `stdlib` processors - but is a different root issue than the one that's been trouble-shot above.

**Comment by suiluj** [comment]
> ```python
>  logger_factory=structlog.stdlib.PrintLoggerFactory(),
> ```


I noticed that i had to change this to:

```python
logger_factory=structlog.stdlib.LoggerFactory(),
```
