### ISSUE TITLE
Flask example broken? No handlers could be found for logger "some_module"

### ISSUE THREAD

**Issue by iffy** [hynek/structlog#75]
Following the example shown here: http://www.structlog.org/en/stable/examples.html#flask-and-thread-local-data

I get the following output when requesting http://127.0.0.1:5000/login:

```
$ python main.py 
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
No handlers could be found for logger "some_module"
127.0.0.1 - - [03/Aug/2016 22:32:37] "GET /login HTTP/1.1" 200 -
```

I expect to see some logging data like `event="user logged in"`.

---

And the example code isn't runnable without slight modifications:

1. Removing leading `.` from `from .some_module import some_function`
2. Make `def login()` return a string response.

So here's my actual files:

`main.py`:

```
import uuid

import flask
import structlog

from some_module import some_function


logger = structlog.get_logger()
app = flask.Flask(__name__)


@app.route('/login', methods=['POST', 'GET'])
def some_route():
    log = logger.new(
        request_id=str(uuid.uuid4()),
    )
    # do something
    # ...
    log.info('user logged in', user='test-user')
    # gives you:
    # event='user logged in' request_id='ffcdc44f-b952-4b5f-95e6-0f1f3a9ee5fd' user='test-user'
    # ...
    some_function()
    # ...
    return 'hey'

if __name__ == "__main__":
    structlog.configure(
        processors=[
            structlog.processors.KeyValueRenderer(
                key_order=['event', 'request_id'],
            ),
        ],
        context_class=structlog.threadlocal.wrap_dict(dict),
        logger_factory=structlog.stdlib.LoggerFactory(),
    )
    app.run()
```

`some_module.py`:

```
from structlog import get_logger

logger = get_logger()


def some_function():
    # later then:
    logger.error('user did something', something='shot_in_foot')
    # gives you:
    # event='user did something 'request_id='ffcdc44f-b952-4b5f-95e6-0f1f3a9ee5fd' something='shot_in_foot'

```

I'm running with Python 2.7

```
$ pip freeze
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
click==6.6
Flask==0.11.1
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
six==1.10.0
structlog==16.1.0
Werkzeug==0.11.10
wheel==0.24.0
```

Is it just me or is it broken for everyone?

**Comment by hynek** [comment]
wow, I don’t even remember if it was supposed to work or to just be kind of pseudo code :D

**Comment by hynek** [comment]
(FWIW, the .some_module.py import can only work if it's in a *package*)

**Comment by iffy** [comment]
I read the example as pseudo code and applied it to my Flask app, but couldn't get it to work.

I get output when I comment out this line in `main.py`:

```
#logger_factory=structlog.stdlib.LoggerFactory(),
```

I'm guessing Flask is doing something to mess it up maybe?  It's been a while since I've dug into structlog, so I'm kind of changing things blindly.

**Comment by hynek** [comment]
OK I had a look.

First of all: thank for bringing this to my attention, I will make the example more friendly.

The reason log.info didn’t print anything is…that stdlib logging drops INFO-level messages in default config.  If you change it to log.warn, it’s gonna work.  I can’t count the times this behavior baffled even seasoned programmers.  I believe in Python 2 you would have gotten an Exception.

**Comment by hynek** [comment]
Could you check if current master works for you?

**Comment by iffy** [comment]
Works great without any changes!  Thank you, Hynek.
