### ISSUE TITLE
PositionalArgumentsFormatter does not remove empty list of args

### ISSUE THREAD

**Issue by keis** [hynek/structlog#82]
PositionalArgumentsFormatter with remove_positional_args=True is supposed to remove the positional_args from the event dict. However this only happens when positional_args is truthy which is not the case for the empty list. `_proxy_to_logger` takes care not to add these to begin with but you can still hit this unexpected behaviour if setting this attribute somewhere else. In my case using a stdlib logging handler to funnel messages into structlog.

**Comment by hynek** [comment]
This should be fixed now.  Sorry for the lack of feedback.
