### ISSUE TITLE
Using class name instead of module name results in no loggings

### ISSUE THREAD

**Issue by montaro** [hynek/structlog#83]
When I do 
`self.logger = wrap_logger(logger=logging.getLogger(__name__))` it works just fine, however doing
`self.logger = wrap_logger(logger=logging.getLogger(self.__class__.__name__))` no logs appear in the file handler!
Is there any reason for this behaviour or am I doing something wrong?
Thanks!

**Comment by hynek** [comment]
That looks like a stdlib thing to me.  In both cases structlog only receives an object and calls methods on it.

I guess you’ve some configuration that is based on logger names and `__name__` and `self.__class__.__name__` are not equal and therefore and handled differently by `logging`.
