### ISSUE TITLE
Wrapping django loggers

### ISSUE THREAD

**Issue by montaro** [hynek/structlog#84]
I code use structlogs to wrap my loggers in django apps, but is there any way to wrap the logs come from the django.* loggers?

**Comment by hynek** [comment]
I think the second question in http://www.structlog.org/en/stable/faq.html is relevant to your interests.  Also cf. #9.

**Comment by md1023** [comment]
Where did faq go?

**Comment by hynek** [comment]
The contents moved to https://www.structlog.org/en/stable/standard-library.html

If you're interested in Django specifically, check out #175.
