### ISSUE TITLE
Change default serializer twisted.JSONRenderer

### ISSUE THREAD

**Issue by se7encz** [hynek/structlog#86]
Hi, 

is there a way to change serializer for twisted.JSONRenderer ?
Default is too slow. I want to use ujson.

**Comment by hynek** [comment]
It takes a `serializer` option which you can set to `ujson.dumps`.

**Comment by se7encz** [comment]
I'm sorry but I can not imagine how? I am using _twisted_ version of _JSONRenderer_.
 There is no _serializer_ option in _JSONRenderer(GenericJSONRenderer)_ and there is no call to _parent __intit___

**Comment by hynek** [comment]
Have you *tried* it?  The twisted version has no `___init___` on its own so there should be no need to call parent init.

**Comment by se7encz** [comment]
structlog.processors.JSONRenderer(serializer=ujson.dumps)
structlog.twisted.JSONRenderer(serializer=ujson.dumps)

For both above:
_File "/usr/local/lib/python2.7/dist-packages/structlog/processors.py", line 150, in __call__
    **self._dumps_kw)
exceptions.TypeError: 'default' is an invalid keyword argument for this function_

Is there some workaround ?

**Comment by hynek** [comment]
Ah yeah, ujson doesn’t support custom serialization.  Something like

```
structlog.twisted.JSONRenderer(serializer=lambda ed, **kw: ujson.dumps(ed))
```

should get you going.
