### ISSUE TITLE
More examples and stdlib friendly documentation

### ISSUE THREAD

**Issue by symbolix** [hynek/structlog#87]
Hi,

First of all, thank you very much for the effort you have put together in-order to create this module. 

I really would like to start using it for my logging tasks as it looks very promising in terms of the features provided, the scalability options and simply due to the fact that is compatible with the `stdlib` logging module in Python.

As I said, I am keen to start using `structlog`, however, I have been reading the documentation all day long and I feel a bit lost. It is probably normal as with any new API and maybe the examples are a bit Flask and Django oriented. It would be nice to have some simple examples that are oriented for CLI applications.

For example, I got through the first bit and understood the context binding etc. And managed to come up with simple log messages such as:

```bash
016-11-03 15:31.41 greeted                        more_than_a_string=[1, 2, 3] whom='world'
``` 

or

```bash
016-11-03 15:31.41 something                      foo='apple' peer_ip='1.2.3.4' user_agent='banana'
```

But then got stuck at the following questions:

1. How do we format the messages? Where is this gap between the message and the contextual information coming from?

2. How do we change the `logging.level`? With the following code, I am only getting the `ERROR`, `WARNING` and `CRITICAL` levels, but not the `DEBUG` and `INFO`.

```python
    import structlog
    import logging

    log = structlog.get_logger()
    logging.basicConfig(level=logging.DEBUG)

    structlog.configure(
        processors=[
            structlog.stdlib.add_logger_name,
            structlog.stdlib.add_log_level,
            structlog.stdlib.PositionalArgumentsFormatter(),
            structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M.%S"),
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,
            structlog.dev.ConsoleRenderer()  # <===
        ],
        context_class=dict,
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True,
    )

    # Test Levels
    log.info('This is just to let you know.')
    log.debug('This is the expected value.')
    log.error('The operation failed.')
    log.fatal('This is the end of everything!')
    log.warn('You have been warned.')
    log.critical('That is NOT good.')
```

Usually, with the native logging, the following message is a good example for what I am trying to usually get into my logs:

```
[2016-11-02 22:27:36,695] <main>        {myApp :<module>    :29} WARNING : I have to warn you about this!
[2016-11-02 22:27:36,695] <main.entity> {entity:__init__    :20} DEBUG   : Class instance call.
[2016-11-02 22:27:36,696] <main.entity> {entity:get_name    :28} INFO    : PET name is Molly
[2016-11-02 22:27:36,696] <main.entity> {entity:third_party :31} INFO    : Initial message from: __THIRD_PARTY!
```

Could you please help me to understand the `structlog` way of achieving such a result. The **_Development_** section of the docs seems to attempt to address these needs. But as I said, it might be a good idea to include more examples to help us understand the API better.

Thanks.

**Comment by hynek** [comment]
if you’re confused how things fit together and don’t want to read anymore, you may want to watch my talk about structlog https://www.youtube.com/watch?v=Ld45vTmtuqQ or my last year’s pycon talk that also talks about it https://hynek.me/talks/beyond-grep/

as for concrete question:

1. formatting is done by formatters that are just processors
2. structlog only calls into stdlib using the wrapped loggers; any configuration of stdlib's logging itself has to happen using stdlib’s APIs as shown in http://www.structlog.org/en/stable/standard-library.html

**Comment by symbolix** [comment]
Hi,

Thanks for your reply. Please do not get me wrong, I will keep on reading as I am keen to understand how this works. I will definitely look at the other links you have suggested.

Maybe I was not very successful in constructing my question, the intention was not to complain but to ask for help so that I can start understand how exactly `structlog` can be a solution for me.

Right now, I am experimenting with quite a lot of logging APIs, including the native Python logging module. My research covers a wide range of different loggers and solutions. Throughout the process, I did my best trying to understand how the native logging facilities work. So I tried simple, out of box approaches and slightly more complex cases where custom `Formatters`, `Adapters`, `Handlers`, `Filters` and even custom Logging classes (where you would inherit from the `logging.Logger` class and override methods related to record manipulation etc.) are employed.

I am trying to come up with a test case that uses `structlog`, and I feel a bit lost. So if we take a simple situation, where we start with a simple `logging` setup:

```python
# First configure top-level logger using the native logging.
log = logging.getLogger('main')

# Set the global level for the logger.
log.setLevel(logging.DEBUG)

# Configure a console handler "ch".
format_template = u'[%(asctime)-15s] [ctx] {%(module)s:%(funcName)s:%(lineno)s} %(levelname)s: %(message)s'

# Set-up a formatter.
formatter = logging.Formatter(format_template)

# Assign a stream handler.
ch = logging.StreamHandler()

# Attach the formatter to the handler.
ch.setFormatter(formatter)

# Set the logging level on the console handler.
ch.setLevel(logging.DEBUG)

# Attach the console handler "ch".
log.addHandler(ch)
```

So this is the simple intial `stdlib` approach. In a simple block like this, where we would start to get the `structlog` involved? Thanks.

**Comment by hynek** [comment]
I did not mean to imply laziness on your part; I was just pointing to a different medium since that might help make things click.

As per your example, structlog can fit in in different way, depending on your needs.

The simplest one would be to use [`wrap_logger`](http://www.structlog.org/en/stable/api.html#structlog.wrap_logger) on your `log` object:

```
>>> sl = structlog.wrap_logger(log)

>>> sl.info("hi")
[2016-11-08 13:39:17,052] {_base:_proxy_to_logger:177} INFO: event='hi'

>>> sl = sl.bind(kw_binding="works now")

>>> sl.info("hi")
[2016-11-08 13:39:34,047] {_base:_proxy_to_logger:177} INFO: kw_binding='works now' event='hi'
```

Now each call on `sl` goes through structlog and at the end the wrapper logger (`log` is called with the result).  This is using the default structlog settings but as you can see in the API reference, there is a lot you can tweak (including how the a log entry is formatted before it’s handed into the wrapped logger).

***

Obviously wrapping loggers by hand is tedious, therefore there’s a way to configure structlog globally as documented in http://www.structlog.org/en/stable/configuration.html and all you do is calling `structlog.get_logger()`` in your application code.

***

With all that in mind I suggest re-read http://www.structlog.org/en/stable/getting-started.html and work yourself forward chapter by chapter.  As for the inevitable “how do I make other libraries use structlog?” I’d like to point you to  http://www.structlog.org/en/stable/faq.html right away.

And again, as for stdlib integration, http://www.structlog.org/en/stable/standard-library.html is where useful examples are listed.

**Comment by aldanor** [comment]
Same thing here :) I've spent the last few hours trying to come up with a simplest `structlog` example where `log.debug('hello world')` would actually output something to console handler.

The only example out of the docs that seems to work more or less out of the box is [this one](http://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging), via `log.setLevel(logging.DEBUG)`, but it took 30 lines of pre-configuring logging which seems like a bit of an overkill for this. In the other two examples, 

Disclaimer: I've read the docs twice now :)

**Comment by hynek** [comment]
@aldanor you’re asking for stdlib `logging` docs here tho. :)

If you want `log.debug` to work, you have to change the `logging.INFO` to `logging.DEBUG` in 

```python
logging.basicConfig(
    format="%(message)s",
    stream=sys.stdout,
    level=logging.INFO,
)
```

**Comment by aldanor** [comment]
Oh gosh, `format='%(message)s'`, obviously, right - thanks! (I had stdlib logging insert log level and logger name before structlog-formatted messages)

Now I see it's actually mentioned in "Flask Examples" and "JSON Logging" in suggested configurations -- I guess that confused me a bit. Maybe *the* simplest example where you have both console renderer, structlog logger, and logging level set up could be highlighted somewhere :)

Like

```python
import structlog
import logging
import sys

logging.basicConfig(format='%(message)s', stream=sys.stdout, level=logging.INFO)
structlog.get_logger().info('It works')
```

Thanks again :)
