### ISSUE TITLE
SyntaxHighlighter processor

### ISSUE THREAD

**Issue by underyx** [hynek/structlog#88]
It would be really awesome if I could add

```py
structlog.processors.SyntaxHighlighter(language_mapping={'body': 'json', 'xml': 'xml'}, file=sys.stdout)
```

which would try to pop `body` and `xml`, and when they exist write a syntax highlighted version of them to `file`.

**Comment by hynek** [comment]
That’s out of scope for structlog, but if you need something like that, it should be fairly easy: just use http://pygments.org

**Comment by underyx** [comment]
@hynek already implemented it locally, I sorta opened this issue to remind myself to generalize & contribute my code.

I guess I'll publish it as a separate package then 👯‍♂️

**Comment by hynek** [comment]
Please do!  Easy straight-forward extensibility was always a number one priority to me (which I’m paying with higher up front complexity :().  I can’t maintain every processor imaginable but I’d *love* to see them exist on PyPI!

**Comment by underyx** [comment]
@hynek here you go: https://github.com/underyx/structlog-pretty

If you can find the time, please review the project. I'm not sure about the names, etc., so I haven't started with documenting it yet, but the usage should be fairly simple to guess. (Or you can check the tests.)
