### ISSUE TITLE
Add a JSONifier for stdlib logging

### ISSUE THREAD

**Issue by hynek** [hynek/structlog#9]
Especially within frameworks, one hasn’t always the power to control every part of logging.

For Twisted, there is already a [solution in place](http://www.structlog.org/en/latest/twisted.html#bending-foreign-logging-to-your-will), there should be also one for stdlib.

**Comment by hynek** [comment]
@wbolster so any idea how much effort this would take?

Since 15.0 is all about stdlib, it would be nice if this came along with it but my stdlib logging understanding is limited.

**Comment by wbolster** [comment]
actually I don't really understand what this is about.

if you are referring to getting plain json without any noise on stdout for all logging calls, also those from libraries outside the application's control, then that will be covered in #40 with trivial configuration.

**Comment by hynek** [comment]
yeah that’s what i mean; make e.g. pyramid's log messages semi-structured so i don’t have multiple cases in my logstash config.  not sure how #40 helps?

**Comment by wbolster** [comment]
hmm, i see what you mean now. 3rd party libs don't obtain a logger through structlog.get_logger() but through logging.getLogger(). indeed, #40 doesn't help there.

    — Wouter

Hynek Schlawack <notifications@github.com> schreef op 22 januari 2015 16:46:25 CET:

**Comment by wbolster** [comment]
i was thinking a bit about this. my first thought was to add some magic handler to the `logging` module's root logger, and route that into structlog somehow. however, handlers (nor formatter nor filters) don't know much about the originating logger, so it seems non-trivial.

**Comment by hynek** [comment]
Routing into structlog isn’t really necessary I’d say, the approach I took in Twisted would be good enough: catch everything that’s not touched by structlog and jsonify it.   But I guess I’ll leave that for an other time.

**Comment by wbolster** [comment]
But how do you determine that it's not touched by structlog? There's no magic flag or anything else that can be easily tested afaiu. Opportunistically decoding/encoding JSON doesn't sound like a sane way (too much overhead and so on).

**Comment by wbolster** [comment]
Hacky idea: add a formatter that checks whether the first char is a `{`  (start of JSON object), and if not, do some JSON encoding of the message. @hynek, ideas?

**Comment by hynek** [comment]
I believe logging has explicit Context objects, maybe that could be leveraged somehow?  I did something similar for Twisted: https://github.com/hynek/structlog/blob/master/structlog/twisted.py#L189  (their `eventDict` is not related to structlog’s `event_dict`).

**Comment by hynek** [comment]
JFTR, https://github.com/madzak/python-json-logger is a thing that seems to do what we want here.

I hadn’t time to look at it but if someone has, I’d appreciate a summary/feedback/ideas :)

**Comment by wbolster** [comment]
@hynek, do these fields:

https://github.com/madzak/python-json-logger/blob/master/src/pythonjsonlogger/jsonlogger.py#L18

make sense for `structlog`? and how much does it overlap with what `structlog` already does?

**Comment by hynek** [comment]
I’m not sure what you mean but it seems to me that it could work to just pass an event_dict into json-logger and be done?

**Comment by fxfitz** [comment]
I would just like to point out that we've been having this problem in our applications (where we use structlog), however some of the other libraries that we include all use standard library logging. So the majority of the application logs with structlog, but then <insert random other library> logs however it wants to log using standard library logging.

So, this has become a big issue for us. :-(

**Comment by hynek** [comment]
So turns out this is actually pretty simple if you don’t insist on using `logging` for actual output:

```python
import logging

import structlog

######################################################
class StructlogHandler(logging.Handler):
    """
    Feeds all events back into ``structlog``.
    """
    level = logging.DEBUG
    filters = []
    lock = None

    def __init__(self):
        from . import get_logger
        self._log = get_logger()

    def emit(self, record):
        self._log.log(record.levelno, record.msg, name=record.name)
######################################################


root_logger = logging.getLogger()
root_logger.addHandler(structlog.stdlib.StructlogHandler())
root_logger.setLevel(logging.DEBUG)

structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M.%S"),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.dev.ConsoleRenderer()
    ],
    context_class=dict,
    # logger_factory=structlog.stdlib.LoggerFactory(),    # <===
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

logging.getLogger(__name__).warn("logging!")
structlog.get_logger().warn("structlog!")
```

gives you (you’ll need current master):

![2016-01-22 at 17 07](https://cloud.githubusercontent.com/assets/41240/12515846/acb14d2c-c12a-11e5-8816-eedc63f2ebbc.png)

I really don’t care about using `logging` for output but even that could be probably solved by configuring an output logger that gets returned by a special LoggerFactory.

The question is: why even bother?  Log output belongs to stdout/stderr. :)

**Comment by fxfitz** [comment]
I think it makes total sense to do it this way and I think it would definitely work for us.

Once `StructlogHandler` is available on PyPI, we'll update our app to use it. :-)

**Comment by hynek** [comment]
You don’t have to wait.  Just copy and paste those 14 lines into your project. :)

(the dep on master is because of the pretteeee ConsoleRenderer)

**Comment by tejasmanohar** [comment]
@hynek +1 for adding this to the module. Also, it seems that this is incompatible w/ `structlog.stdlib.filter_by_level`?

**Comment by hynek** [comment]
Yes it is because filter_by_level needs a stdlib logger to work.

All these edge cases are the reason why there’s no official solution in structlog yet…

**Comment by multani** [comment]
I had to update the ``Structloghandler.emit()`` method in order to get information about exceptions for libraries logging using stdlib ``Logger.exception()`` method:

```python
        def emit(self, record):
            kwargs = {'name': record.name}
            if record.exc_info:
                kwargs['exc_info'] = record.exc_info
            self._log.log(record.levelno, record.msg, **kwargs)
```

Otherwise, it's cool :+1:

**Comment by hynek** [comment]
JFTR, structlog 17.1 will have a nice way to have consistent logs if you don’t mind using logging for formatting: efae84ea56bd5160de1e494165c245e3b474d7ff

**Comment by hynek** [comment]
Last call for feedback on #105 which will provide a way to intercept log entries within the stdlib.  Once that pull request is merged, I will close this issue forever. :)

**Comment by wbolster** [comment]
i think this issue should be closed

**Comment by fxfitz** [comment]
Agreed; it looks like this is now fixed. Thanks!
