### ISSUE TITLE
structlog.get_logger() vs structlog.getLogger()

### ISSUE THREAD

**Issue by guettli** [hynek/structlog#99]
Thank you for the examples:

http://www.structlog.org/en/stable/examples.html

It contains calls to `structlog.get_logger()` and `structlog.getLogger()`.

Which one is the preferred name?

**Comment by hynek** [comment]
Quoth the API reference:

> CamelCase alias for structlog.get_logger().
>
> This function is supposed to be in every source file – we don’t want it to stick out like a sore thumb in frameworks like Twisted or Zope.

It's just accommodation to the two major Python styles.

**Comment by guettli** [comment]
If I understood you correctly, then `get_logger()` is preferred. 

But if you love CamelCaseThenYouCanUseGetLoggerToo. :-)

**Comment by hynek** [comment]
That depends on what style the code is written it that uses it. :)

In code, it’s literally just `getLogger = get_logger`.

That’s also the reason why getLogger is only used in the Twisted example.

**Comment by guettli** [comment]
Maybe Python should provide a way to make both code styles available everywhere. This way you don't need to write the above assignment (`getLogger = get_logger`)?

What do you think?

**Comment by hynek** [comment]
I think it's a bit of fringe interest. :)  The only reason I go the extra mile here is because structlog has specific Twistef support.
